### ISSUE TITLE
Writing/saving very large xlsx file - Shiny server crashes

### ISSUE THREAD

**Issue by aavanesy** [ycphs/openxlsx#10]
## Expected Behavior
Code is very straightforward.
Reads excel (100k+ rows, 12 columns, both text and numbers), does calculations, prints out same file + output sheet.

## Actual Behavior

Run well on different PC's when running the shiny app locally.
Crashes when run on a Shiny server. Same code runs well with less data.
Nothing in the logs.

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.
  
  2.
  
  3.

## sessionInfo()

Version of openxlsx: latest
Version of R: 3.6.1 deployed on Ubuntu/AWS

**Comment by ycphs** [comment]
Did you check the shiny log? Maybe your app runs out of memory on the server.

**Comment by aavanesy** [comment]
Yes, nothing in the logs.
I tried to run on a t2.medium, a 4Gb ram instance, app crashes still.

**Comment by ycphs** [comment]
Maybe it has something to do with the permission of the file. Is it uploaded interactively in the app?

If not please make sure the app has the permission to access and edit the file.

**Comment by aavanesy** [comment]
The app works perfectly when working with a small file (1-5mb) but crashes with 10+.
Must be a memory issue. Are there any overrides/options I could use? Is 4gb maybe not enough for such size?

**Comment by ycphs** [comment]
maybe this is a solution.

max file size of shiny [Help users upload files to your app](https://shiny.rstudio.com/articles/upload.html)

If this article provides a solution for your problem, please mark the issue as closed.

**Comment by aavanesy** [comment]
That is something I use of course, otherwise uploading a 10+ mb would have been impossible.
My problem is writing back a very large file as xlsx using openxlsx.
I will post a sample app tomorrow.

**Comment by ycphs** [comment]
It seems it works
