### ISSUE TITLE
Too much data in cells

### ISSUE THREAD

**Issue by Arthfael** [ycphs/openxlsx#117]
**Describe the bug**
When writing from a data table with more than the maximum amount of data allowed by Excel, it seems to actually write all of the data into the cells, so on subsequently opening the file for the first time, Excel needs to repair records. No lasting corruption seems done to the data (e.g. no shifting of subsequent cells, formatting corruption, etc...)

**To Reproduce**
1. Create a data table with, in one cell, more than the maximum amount of data allowed by Excel (32,767)
    e.g. df <- data.frame(Col1 = paste(rep(1, 32,768), collapse = ""))
2. Write data to a workbook and save it
3. Open resulting xlsx file in Excel

**Expected behavior**
I would expect that at least optionally it would truncate data, with a warning, and properly format the cells.

**Desktop (please complete the following information):**
Windows Server 2019 Standard
openxlsx: 4.1.4
R version 3.6.1 (2019-07-05)
R studio 1.3.1073

**Comment by ycphs** [comment]
I am working on PR #157.

If a solution like this could work for you please let me know.
