### ISSUE TITLE
write.xlsx() should set proper width for Date and DateTime columns

### ISSUE THREAD

**Issue by shrektan** [ycphs/openxlsx#119]
`write.xlsx()` is great. 

We can call this simple function to dump a data.frame or a list of data.frame to an Excel file. In addition, it keeps the default styles (e.g., font) of the local Excel settings, which is very important to me. In contrast, `writexl::write_xlsx()` will ignore the users's default Excel style settings, and forces to use the font's I don't like...

However, there's a tiny issue I would like to raise, which is **when the data.frame contains Date or DateTime columns, the column width is too narror for Excel to display**. What's worse is, unlike numbers and characters, Excel displays Date/DateTime as `########`, thus users are impossible to view the value at all. It leads to a use case that, whenever I have a data.frame that contains Date/DateTime columns, I have to manually set the width of those columns, again and again, which I believe, is not convnient.

**So my feature request is** : `write.xlsx()` should automatically set a proper width for Date and DateTime columns, so that the user can know the value without adjusting the width first.

Thanks!

### Excel display Date/DateTime columns as `#####` if the width is not suitable

![image](https://user-images.githubusercontent.com/8368933/99634829-131e5b80-2a7c-11eb-9ad8-76a77f65c712.png)

### I have to adjust the width in order to show the values
![image](https://user-images.githubusercontent.com/8368933/99634843-19143c80-2a7c-11eb-9368-97bd74145432.png)

**Comment by ycphs** [comment]
The solution is not so easy. Excel uses in some cases the locale information of the maschine. Therefore the calculation of the column width might be not very accurate. 
A possible solution could be a standard format/style for date and datetime column, where the width can be set more precise.

**Comment by ycphs** [comment]
Maybe this package could help.

[https://github.com/davidgohel/gdtools](gdtools)
