### ISSUE TITLE
CRAN Check Error

### ISSUE THREAD

**Issue by ycphs** [ycphs/openxlsx#132]
The last CRAN checks found errors in the package.

[Error](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/openxlsx-00check.html)

I will take a closer look into that.

**Comment by JanMarvin** [comment]
Looks like Brian Ripley is using the Christmas holidays to changed the R-devel Unicode representation. This is from R 4.0.3 on Arch Linux with icu 68.

```R
> stringi::stri_escape_unicode(tbl_nm)
[1] "\\u6027\\u5225"
> a <- "\\u6027\\u5225"
> stringi::stri_unescape_unicode(a)
[1] "性別"
> 
> a <- "\\U6027\\U5225"
> stringi::stri_unescape_unicode(a)
[1] NA
Warning message:
In stringi::stri_unescape_unicode(a) :
  invalid escape sequence detected; setting NA
```

Edit: the issue was successfully solved by R fixing things in R devel.
