### ISSUE TITLE
openxlsx.dateFormat side effects in openxlsx 4.2.3

### ISSUE THREAD

**Issue by koalaparis** [ycphs/openxlsx#137]
**Describe the bug**
The global option openxlsx.dateFormat has unexpected side effects on date and non-date cells.

**To Reproduce**
```
library(openxlsx)

options("openxlsx.dateFormat" = "dd/mm/yyyy")

wb <- openxlsx::createWorkbook()

sheetName <- "Feuil1"
df <- data.frame(a = 12.1, b = as.Date("2021-01-25"))

openxlsx::addWorksheet(
  wb = wb, 
  sheetName = sheetName)

openxlsx::writeData(
  wb = wb,
  sheet = sheetName,
  x = df)

openxlsx::openXL(wb)
```

**Expected behavior**
| a      | b |
| ----------- | ----------- |
|12,10|25/01/2021|

**Actual behavior**
| a      | b |
| ----------- | ----------- |
|12,10|44 221,00|

**Additional remarks**
I did not encounter this issue on previous openxlsx versions.

**Desktop (please complete the following information):**
OS: Windows 10
openxlsx: 4.2.3
R version 4.0.3
R studio 1.3.1056

Regional settings: French

**Comment by JanMarvin** [comment]
Could you check if this behaves the same with current master? I could not reproduce it 

```R
library(openxlsx)

options("openxlsx.dateFormat" = "dd/mm/yyyy")

wb <- openxlsx::createWorkbook()

sheetName <- "Feuil1"
df <- data.frame(a = 12.1, b = as.Date("2021-01-25"))

openxlsx::addWorksheet(
  wb = wb, 
  sheetName = sheetName)

openxlsx::writeData(
  wb = wb,
  sheet = sheetName,
  x = df)

fl <- "gh_issue_137.xlsx"

saveWorkbook(wb, fl, overwrite = T)
```

<img src="https://user-images.githubusercontent.com/1645626/106358710-1a7ca380-630e-11eb-8d9b-224fa66dfe98.png" width="250">

**Comment by koalaparis** [comment]
Sorry, I retried just after opening RStudio and got the same (correct) result as you.

Actually, by trying to make the code 'minimal' I had omitted some options that were still active in the submitted example.

Please try the following code: I executed it in a new RStudio session and got the wrong result below.

```
library(openxlsx)

generateWb <- function(){
  wb <- openxlsx::createWorkbook()
  
  sheetName <- "Feuil1"
  df <- data.frame(a = 12.1, b = Sys.Date())
  
  openxlsx::addWorksheet(
    wb = wb, 
    sheetName = sheetName)
  
  openxlsx::writeData(
    wb = wb,
    sheet = sheetName,
    x = df
  )
  
  openxlsx::openXL(wb)
}

options("openxlsx.numFmt" = "#,##0.00")
options("openxlsx.dateFormat" = "dd/mm/yyyy")
generateWb()
```

![image](https://user-images.githubusercontent.com/68401797/106443437-c6dc9800-647c-11eb-8003-1d603b666031.png)

**Comment by JanMarvin** [comment]
I can confirm this, but have no solution. The thing is `openxlsx` does not store/create style ids and is not able to attach them either.

There should be an xml node attribute  `s="1"` for one numeric format and `s="2"` for the other (as both are numerics internally and only the format is different). Currently `openxlsx` is unable to store this information, and I'm unsure if it ever was. In theory something like this:

```R
wb$worksheets[[1]]$sheet_data$style_id <- c("0","0","1", "2")
```

Should create a vector identifying the correct style id, but it's either not used or overwritten. The entire style handling in `openxlsx` is currently borked.
