### ISSUE TITLE
createStyle() without default fontName/fontSize/fontColour or parameter in conditionalFormatting() to omit these from style used

### ISSUE THREAD

**Issue by gjaldb** [ycphs/openxlsx#139]
**Is your feature request related to a problem? Please describe.**
conditionalFormatting() using a style with fontSize = NULL, will replace font size set by addstyle(), as it default to workbook base Name/Size/Colour when condition is activated in excel.

**Describe the solution you'd like**
Ability to create a style without any default fontSize, 

**Describe alternatives you've considered**
Alternatively a parameter in conditionalFormatting() to not apply fontName, fontSize, fontColour

**To Reproduce**
wb <- createWorkbook()
addWorksheet(wb, "Iris")
writeData(wb, sheet = 1, x = iris)
style_font <- createStyle(fontName = "Arial", fontSize = 13, fontColour = "red",  textDecoration = "bold")
style_highlight <-createStyle(bgFill = "green")
addStyle(wb, 1, style = style_font, rows = 1:150, cols=1, gridExpand = T)
conditionalFormatting(wb, 1, cols=1:ncol(iris), rows=1:nrow(iris), rule='$E1=="y"', style = stylehighlight)
openXL(wb)
#Enter y anywhere in column E/5

**Expected behavior**
According to createStyle() documention, the behaviour is as expected, as createStyle() with fontSize = NULL it will default to workbook base font size (Defaults to 11) (and same for fontName and fontColour).
While the textdecoration = "bold" is not affected, as is has no default. 

The strange thing is that Excel itself does no allow setting fontSize and font(name) (but it allows colour) when creating a conditional formatting (in Excel), and one thus cannot alter the font size of the conditionalFormatting created by createStyle() in {openxlsx}.

**Comment by JoshuaSturm** [comment]
Your example is working as intended (i.e, styling set by set_font is preserved) on Ubuntu 20.10 and LibreOffice 7.0.3.1.
Will have to test on Windows with Excel.
