### ISSUE TITLE
How do I set a page horizontally or vertically through the pageSetup() function？

### ISSUE THREAD

**Issue by chuxinyuan** [ycphs/openxlsx#140]
**page horizontally or vertically**

Even though I set the margins to be equal to left and right, I still want the data to print horizontally centered or vertically centered. this is a simple example:

```r
library(openxlsx)
wb = createWorkbook()
addWorksheet(wb, "example")

pageSetup(
  wb, 
  "example",
  orientation = "portrait",
  scale = 97,
  left = 0.7,
  right = 0.7, 
  top = 0.75,
  bottom = 0.75,
  header = 0.3, 
  footer = 0.3,
  fitToWidth = TRUE,
  fitToHeight = TRUE,
  paperSize = 9,
  printTitleRows = NULL, 
  printTitleCols = NULL
)

writeData(wb, "example", mtcars[, 1:4])
saveWorkbook(wb, "example.xlsx", overwrite = TRUE)

# Excel to PDF
library(RDCOMClient)
xlFile = here::here("example.xlsx")
xlApp = COMCreate("Excel.Application")
xlApp[["Visible"]] = TRUE 
wb = xlApp[["Workbooks"]]$Open(Filename = xlFile)
sht = wb[["Worksheets"]]$Item(1)
sht$Select()

pdfFile = here::here("example.pdf")
if (file.exists(pdfFile) == TRUE)  file.remove(pdfFile)

xlApp[["ActiveSheet"]]$ExportAsFixedFormat(
  IgnorePrintAreas = FALSE,
  Type = 0,    # 导出为PDF
  Filename = pdfFile)

xlApp$Quit() 
```

**the solution I'd like**

PageSetup () adds two arguments with which to center horizontally and vertically, maybe it is halign and valign. The default is FALSE

**Comment by chuxinyuan** [comment]
Has the problem been solved？

**Comment by chuxinyuan** [comment]
请不要关闭这个问题。

**Comment by JanMarvin** [comment]
Hi @chuxinyuan , this requires setting the printer option. While this might be possible with `openxlsx` it was never implemented. In `openxlsx2` you can do it like this:

``` r
library(openxlsx2)
wb <- wb_workbook() %>% 
  wb_add_worksheet() %>% 
  wb_add_data(x = mtcars[, 1:4]) %>% 
  wb_page_setup(
    orientation = "portrait",
    scale = 97,
    left = 0.7,
    right = 0.7, 
    top = 0.75,
    bottom = 0.75,
    header = 0.3, 
    footer = 0.3,
    fitToWidth = TRUE,
    fitToHeight = TRUE,
    paperSize = 9,
    printTitleRows = NULL, 
    printTitleCols = NULL
  )

# currently there is no nice user facing function
wb$worksheets[[1]]$set_print_options(horizontalCentered = "1", verticalCentered = "1")

wb %>% wb_save("test.xlsx")
```

**Comment by chuxinyuan** [comment]
> Hi @chuxinyuan , this requires setting the printer option. While this might be possible with `openxlsx` it was never implemented. In `openxlsx2` you can do it like this:
> 
> ```r
> library(openxlsx2)
> wb <- wb_workbook() %>% 
>   wb_add_worksheet() %>% 
>   wb_add_data(x = mtcars[, 1:4]) %>% 
>   wb_page_setup(
>     orientation = "portrait",
>     scale = 97,
>     left = 0.7,
>     right = 0.7, 
>     top = 0.75,
>     bottom = 0.75,
>     header = 0.3, 
>     footer = 0.3,
>     fitToWidth = TRUE,
>     fitToHeight = TRUE,
>     paperSize = 9,
>     printTitleRows = NULL, 
>     printTitleCols = NULL
>   )
> 
> # currently there is no nice user facing function
> wb$worksheets[[1]]$set_print_options(horizontalCentered = "1", verticalCentered = "1")
> 
> wb %>% wb_save("test.xlsx")
> ```

谢谢你的解决方案，非常棒！不过有些时候重新来过不是很划算。事实上可以考虑对于生成的结果利用`openxlsx2`进行进一步设置：

```r
library(openxlsx2)
wb = wb_load("example.xlsx")
wb$worksheets[[1]]$set_print_options(
  horizontalCentered = "1", 
  verticalCentered = "1"
)
wb_save(
  wb, "mtcars.xlsx",
  overwrite = TRUE
)
```
