### ISSUE TITLE
openXL will not open file on network drive that does not allow execution

### ISSUE THREAD

**Issue by romanzenka** [ycphs/openxlsx#141]
`openxlsx::openXL(path)` fails to open Excel if the path leads to a disk that does not allow execution (in my case it is a network drive that is secured to not allow executables to run on it).

**To Reproduce**
 - Save Excel spreadsheet on a network drive
 - run `openxlsx::openXL(path)` with path to the spreadsheet

**Expected behavior**
The Excel application opens, displaying the spreadsheet.

**Desktop:**
 - OS: Windows 10
 - Version: 4.2.3

**Additional context**

I get the following error message:
```
Access is denied.
Warning message:
In shell(file) :
  'X:/path/file.xlsx' execution failed with error code 1
```

I believe the error is in using the `shell` function to open the file, instead of `shell.exec` that will look up file association first, based on the extension, then run the application directly.

**Comment by ycphs** [comment]
The `openXL` function is a bit tricky. Depending on the OS the command differs, but if you could propose a solution or improvement for Windows along with tests to verify the results it would be great.

Yes you are right currently it is using `shell`.
