### ISSUE TITLE
Add encoding argument in write.xlsx

### ISSUE THREAD

**Issue by cgpeltier** [ycphs/openxlsx#143]
I'd love the option to specify the encoding when writing to .xlsx. I often work with international names with accents and need to specify a latin1 encoding. 

While `write.csv()` allows this, the users I share these files with are often using Excel to look at the data, and csv's occasionally render incorrectly in Excel due to parsing issues. As a result, saving .xlsx files with a latin1 encoding would be ideal. 

Thanks!

**Comment by JanMarvin** [comment]
I'm not sure, but aren't xlsx files already utf-8 only? Thus an issue can only arise if writing from a non utf-8 R session. Either way, since we depend on stringi already, we might run a check on the encoding of the strings and recode to utf-8 if required.
