### ISSUE TITLE
Strings >= 32kb produce broken Excel files

### ISSUE THREAD

**Issue by epruesse** [ycphs/openxlsx#145]
**Describe the bug**

Cells containing strings longer than 32767 characters (2^15-1) cause Excel to report a broken file ("We found a problem with some content ..." message).

**To Reproduce**

```R
broken <- data.frame(text=paste(collapse="", letters[rep(1, 2^15)]))
write.xlsx(df, file="broken.xlsx")

works <- data.frame(text=paste(collapse="", letters[rep(1, 2^15 - 1)]))
write.xlsx(df, file="works.xlsx")
```

**Expected behavior**

This appears to be an Excel limitation. The "repair process" simply truncates the strings. Since longer strings won't be visible in Excel in any case, `openxlsx` can simply truncate the strings itself, producing correct xlsx files. It probably suffices to issue a warning if any truncation happens.

**Comment by ycphs** [comment]
I am with you. Your proposed solution of truncating the string with data exceeding 32767 characters sounds good, but it should be done only with a warning.

**Comment by ycphs** [comment]
Please check PR #157

**Comment by epruesse** [comment]
I commented there:

https://github.com/ycphs/openxlsx/pull/157#discussion_r616951290

**Comment by epruesse** [comment]
Basially - the thing is that Excel makes it look like the `xlsx` file is broken if it contains any strings longer than 32kb-1, or even malicuous. You have to let excel "repair" the file, which will truncate the strings. I assume it's somewhere in the xlsx standard too, as a maximum length, so it's possible libreoffice behaves similarly.

I'd just make the limit configurable, and then always truncate and issue a warning. That's much simpler for the user than having to dig through data.frames to ellipsize strings.
