### ISSUE TITLE
Addition of TopN and BottomN conditioning formatting options

### ISSUE THREAD

**Issue by vkatti** [ycphs/openxlsx#146]
**Is your feature request related to a problem? Please describe.**
I am a heavy user of this package and love you guys for it. I just felt it missed the topN, bottomN options. So I forked the package and built out the functionality. The RMD CHECK passes with Zero errors and my testing seems to work. However I get some notes and warnings that look like they may be my development environment related. I am on  windows 10 environment with
R 4.0.3. 

I get the following notes and warnings:
```
> checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    'cond_format_test.xlsx'

> checking compiled code ... NOTE
  Note: information on .o files for i386 is not available
  Note: information on .o files for x64 is not available
  File 'V:/Shared/Dropbox/07_Learning/openxlsx.Rcheck/openxlsx/libs/i386/openxlsx.dll':
    Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
    Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
    Found 'printf', possibly from 'printf' (C)
  File 'V:/Shared/Dropbox/07_Learning/openxlsx.Rcheck/openxlsx/libs/x64/openxlsx.dll':
    Found 'abort', possibly from 'abort' (C), 'runtime' (Fortran)
    Found 'exit', possibly from 'exit' (C), 'stop' (Fortran)
    Found 'printf', possibly from 'printf' (C)
  
  Compiled code should not call entry points which might terminate R nor
  write to stdout/stderr instead of to the console, nor use Fortran I/O
  nor system RNGs. The detected symbols are linked into the code but
  might come from libraries and not actually be called.
  
  See 'Writing portable packages' in the 'Writing R Extensions' manual.
   WARNING
  'qpdf' is needed for checks on size reduction of PDFs

0 errors v | 1 warning x | 2 notes x
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.
```
I know how to fix the first note, but I need help with the other 2. My sesion info is as follows:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3
```

**Comment by JanMarvin** [comment]
These are most likely from Rcpp. Basically you can't use a few c functions in R. R cmd check found abort, exit and printf in the code. Use rprintf() and avoid abort and exit. This is R telling you not to write code that might eventually kill R itself. afaik it's stated somewhere in the writing r extensions manual and iirc there is no way around it if you want your code on CRAN.

**Comment by vkatti** [comment]
As far as I know, I have not explicitly used abort, exit or printf in my code. I just copy pasted existing code with few modifications to get this new functionality. How do I get someone to review my code to help fix this?

**Comment by JanMarvin** [comment]
I kinda thought so, might be warnings from the existing code.
clone this repo via github (locally and via the website). modify .git/config to point to your cloned repo. add your local changes to a new branch (git add ..., git branch -b ..., git commit -m ... and git push). one you've pushed this branch to your github clone, you can create a pull request via github

**Comment by vkatti** [comment]
Alright, let me try this. Will update the progress. Thank you for the help.

**Comment by vkatti** [comment]
Created a PR #147  for your review.

**Comment by JanMarvin** [comment]
Coding looks good to me. If the CI likes it, I assume it'll be included soon :+1:

**Comment by ycphs** [comment]
Thank you for your PR. I already merged it, but could I trouble you, @vkatti,  to provide also some tests?

**Comment by vkatti** [comment]
Hello @ycphs,

While writing some tests for this  functionality, I noticed an Excel quirk which is unhandled in the my current code. It is ok if I further modify the topN bottomN functionality to handle this?? I would raise another PR with the fixed code and the tests for it. Sounds good?

**Comment by ycphs** [comment]
Yes of course

**Comment by vkatti** [comment]
Quick question: who is supposed to "close" this issue. You or me? Since I raised it and provided a solution too, I am now wondering who should ideally do this. What is the etiquette here?
