### ISSUE TITLE
New Feature: setActiveSheet

### ISSUE THREAD

**Issue by cwolcott** [ycphs/openxlsx#154]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select the current **active sheet** before saving the workbook.  By default the **first sheet** is active.

**Describe the solution you'd like**
setActiveSheet(wb, sheet="ABC")

**Describe alternatives you've considered**
worksheetOrder(wb) <- c(3, 1, 2)
But there is an issue described in [#102](https://github.com/ycphs/openxlsx/issues/102#issue-706468373)

**Comment by ycphs** [comment]
I started my work on this topic. You are welcome to contribute. 

Please check PR #169
