### ISSUE TITLE
Error in is.nan(tmp) : default method not implemented for type 'list'

### ISSUE THREAD

**Issue by KptnKermit** [ycphs/openxlsx#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[test.xlsx](https://github.com/ycphs/openxlsx/files/6217835/test.xlsx)

**Comment by KptnKermit** [comment]
Sorry, 

I've seen, that there are no infos provided. 
Now supplemented.

Expected Behavior
Write Data into a Table

Actual Behavior
writeData and WriteDateTable stops with error:
Error in is.nan(tmp) : default method not implemented for type 'list'

Steps to Reproduce the Problem
(please attach an example xlsx file if possible)

Code:

Export File
dir.create("001_Export")
setwd("./001_Export")

excel_overview_file <- createWorkbook()
excel_overview_income <- addWorksheet(wb = excel_overview_file, sheetName = "Income")
excel_overview_orig <- addWorksheet(wb = excel_overview_file, sheetName = "Cumulated costs")
excel_overview_fixed <- addWorksheet(wb = excel_overview_file, sheetName = "Fixed costs")
excel_overview_variable <- addWorksheet(wb = excel_overview_file, sheetName ="Variable costs")
excel_overview_fixcats_monthly <- addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Monthly")
excel_overview_varcats_monthly <- addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Monthly")
excel_overview_fixcats_yearly <- addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Yearly")
excel_overview_varcats_yearly <- addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Yearly")
excel_overview_finanz <- addWorksheet(wb = excel_overview_file, sheetName = "Steuerausgleich")
#excel_origin <- addWorksheet(wb = excel_file, sheetName = "Original data")
excel_overview_title <- ("001a_Finanzdaten_kumuliert.xlsx")

writeDataTable(wb = excel_overview_file, x = income, sheet = excel_overview_income, withFilter = TRUE, keepNA = FALSE, na.string = NULL)

saveWorkbook(overwrite = TRUE, excel_overview_file, excel_overview_title)

Used Data.Frame: Attached as test.xlsx

**Comment by KptnKermit** [comment]
Attached file came with first post

**Comment by ycphs** [comment]
I tried to refine your code:
``` 
excel_overview_file <- createWorkbook()
addWorksheet(wb = excel_overview_file, sheetName = "Income")
addWorksheet(wb = excel_overview_file, sheetName = "Cumulated costs")
addWorksheet(wb = excel_overview_file, sheetName = "Fixed costs")
addWorksheet(wb = excel_overview_file, sheetName ="Variable costs")
addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Monthly")
addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Monthly")
addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Yearly")
addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Yearly")
addWorksheet(wb = excel_overview_file, sheetName = "Steuerausgleich")
#excel_origin <- addWorksheet(wb = excel_file, sheetName = "Original data")
excel_overview_title <- ("001a_Finanzdaten_kumuliert.xlsx")

writeDataTable(wb = excel_overview_file, x = income, sheet = excel_overview_income, withFilter = TRUE,
               keepNA = FALSE, na.string = NULL)

saveWorkbook(overwrite = TRUE, excel_overview_file, excel_overview_title)
```

The basic idea is that you create one workbook and then you just add the sheets without assigning it to a new variable, because the sheet is added to the workbook structure inernally.

Please let me know if that helps. Maybe you could let me know what the code should do.

**Comment by KptnKermit** [comment]
Hi, 


Unfortunately no change, same error. 


Basically I just try to export a bunch of DataFrames into an excel for further use, e.g. sharing data to people without R and for personal documentation. The Excel file I sent you for trials (test.xlsx) is exactly one of these data frames exported with write.csv2. In fact, the export of data with write.csv2 in the same script is working fine.


The whole script is importing bank account data of different accounts (cdv import), consolidate and categorize the entries and finally visualise it via ggplot.
In past years I used the xlsx library, always with Java linked problems on Mac. 

After a new clean install of MacOs on my computer (Big Sur) and re-install of R / RStudio I changed to openxls and produced the sent error. 


Can you explain, why this error is occuring? Maybe I have then the chance to check the rest of the script for adaption.


I hope this helps. If you need further informations, please let me know.


Best regards


Werner


  Dr. Werner Pessenhofer, ***@***.***
M +43 650 66 27 617

**Comment by ycphs** [comment]
```
excel_overview_file <- createWorkbook()
addWorksheet(wb = excel_overview_file, sheetName = "Income")
addWorksheet(wb = excel_overview_file, sheetName = "Cumulated costs")
addWorksheet(wb = excel_overview_file, sheetName = "Fixed costs")
addWorksheet(wb = excel_overview_file, sheetName ="Variable costs")
addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Monthly")
addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Monthly")
addWorksheet(wb = excel_overview_file, sheetName = "Fixcats_Yearly")
addWorksheet(wb = excel_overview_file, sheetName = "Varcats_Yearly")
addWorksheet(wb = excel_overview_file, sheetName = "Steuerausgleich")
#excel_origin <- addWorksheet(wb = excel_file, sheetName = "Original data")
excel_overview_title <- ("001a_Finanzdaten_kumuliert.xlsx")

writeDataTable(wb = excel_overview_file, x = iris

, sheet = excel_overview_income, withFilter = TRUE,
               keepNA = FALSE, na.string = NULL)

saveWorkbook(overwrite = TRUE, excel_overview_file, excel_overview_title)
``` 
the code above and the resulting file doesn't show any error.
[001a_Finanzdaten_kumuliert.xlsx](https://github.com/ycphs/openxlsx/files/6260804/001a_Finanzdaten_kumuliert.xlsx)

**Comment by ycphs** [comment]
You have the following code in the example

```
writeDataTable(wb = excel_overview_file, x = income, sheet = excel_overview_income, withFilter = TRUE,
               keepNA = FALSE, na.string = NULL)
```

`writeDataTable` expects an index or the sheet name for the variable sheet.

the following two lines should create an equal result for your code:
```
writeDataTable(wb = excel_overview_file, x = income, sheet =  "Income", withFilter = TRUE,
               keepNA = FALSE, na.string = NULL)
```
or
```
writeDataTable(wb = excel_overview_file, x = income, sheet =  1, withFilter = TRUE,
               keepNA = FALSE, na.string = NULL)
```

**Comment by KptnKermit** [comment]
If I change the dataset to "iris", everything works fine, so it seems to be related to the data structure.
Maybe this issue is related: https://github.com/awalker89/openxlsx/issues/100

**Comment by KptnKermit** [comment]
> str(income)
'data.frame':	132 obs. of  13 variables:
 $ IBAN         : chr  "AT444300000000043522" "AT444300000000043522" "AT444300000000043522" "AT444300000000043522" ...
 $ Buchungsdatum: POSIXlt, format: "2019-08-13" "2019-07-31" "2019-07-19" "2019-06-28" ...
 $ Valutadatum  : POSIXlt, format: "2019-08-13" "2019-07-31" "2019-07-19" "2019-06-28" ...
 $ Waehrung     : chr  "EUR" "EUR" "EUR" "EUR" ...
 $ Betrag       : num  2.45 6983.45 1.84 18169.2 2.51 ...
 $ Buchungstext : chr  "SEPA-Gutschrift" "SEPA-Gutschrift" "SEPA-Gutschrift" "SEPA-Gutschrift" ...
 $ Umsatztext   : chr  "GMI -Gesellschaft fuer Mahn- und Inkassowesen mbH IBAN: DE94 2659 0025 1009 1904 01 Auftraggeberreferenz: EII72"| __truncated__ "HIGH TECH COATINGS GMBH Dr.-Mitterbauer-Strasse 3 4663 Laakirchen Österreich IBAN: AT30 1506 0009 3103 4565 Loh"| __truncated__ "GMI -Gesellschaft fuer Mahn- und Inkassowesen mbH IBAN: DE94 2659 0025 1009 1904 01 Auftraggeberreferenz: EII72"| __truncated__ "HIGH TECH COATINGS GMBH Dr.-Mitterbauer-Strasse 3 4663 Laakirchen Österreich IBAN: AT30 1506 0009 3103 4565 Loh"| __truncated__ ...
 $ Verursacher  : chr  "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" ...
 $ Kategorie    : chr  "Inkasso" "Gehalt Miba" "Inkasso" "Gehalt Miba" ...
 $ costtype     : chr  "Variable Kosten" "Variable Kosten" "Variable Kosten" "Variable Kosten" ...
 $ week         : POSIXct, format: "2019-08-12 00:00:00" "2019-07-29 00:00:00" "2019-07-15 00:00:00" "2019-06-24 00:00:00" ...
 $ month        : POSIXct, format: "2019-08-01" "2019-07-01" "2019-07-01" "2019-06-01" ...
 $ year         : POSIXct, format: "2019-01-01" "2019-01-01" "2019-01-01" "2019-01-01" ...
 - attr(*, "na.action")= 'omit' Named int [1:72] 54 56 57 60 61 62 63 64 65 67 ...
  ..- attr(*, "names")= chr [1:72] "NA" "NA.1" "NA.2" "NA.3" ...
>

**Comment by KptnKermit** [comment]
> str(income)
'data.frame':	132 obs. of  13 variables:
 $ IBAN         : chr  "AT4443000000000XXXX" "AT4443000000000XXX" "AT4443000000000XXX" "AT4443000000000XXX" ...
 $ Buchungsdatum: POSIXlt, format: "2019-08-13" "2019-07-31" "2019-07-19" "2019-06-28" ...
 $ Valutadatum  : POSIXlt, format: "2019-08-13" "2019-07-31" "2019-07-19" "2019-06-28" ...
 $ Waehrung     : chr  "EUR" "EUR" "EUR" "EUR" ...
 $ Betrag       : num  2.45 6983.45 1.84 18169.2 2.51 ...
 $ Buchungstext : chr  "SEPA-Gutschrift" "SEPA-Gutschrift" "SEPA-Gutschrift" "SEPA-Gutschrift" ...
 $ Umsatztext   : chr  "GMI -Gesellschaft fuer  __truncated__ ...
 $ Verursacher  : chr  "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" "Neutral / Ueberweisungen" ...
 $ Kategorie    : chr  "Gehalt" "Gehalt" "Überweisung" ...
 $ costtype     : chr  "Variable Kosten" "Variable Kosten" "Variable Kosten" "Variable Kosten" ...
 $ week         : POSIXct, format: "2019-08-12 00:00:00" "2019-07-29 00:00:00" "2019-07-15 00:00:00" "2019-06-24 00:00:00" ...
 $ month        : POSIXct, format: "2019-08-01" "2019-07-01" "2019-07-01" "2019-06-01" ...
 $ year         : POSIXct, format: "2019-01-01" "2019-01-01" "2019-01-01" "2019-01-01" ...
 - attr(*, "na.action")= 'omit' Named int [1:72] 54 56 57 60 61 62 63 64 65 67 ...
  ..- attr(*, "names")= chr [1:72] "NA" "NA.1" "NA.2" "NA.3" ...
>

**Comment by KptnKermit** [comment]
Can I do something to solve or to round this issue?

**Comment by KptnKermit** [comment]
go round

**Comment by JanMarvin** [comment]
I assume its because of this (github search of the project for `which(is.nan(tmp)` ) and might have something to do with a data.frame with nested lists? At least `df[[i]]` is a list at some point during this evaluation. 

This line seems to check each row for missing values and stumbles over a list in at least one of the rows.

https://github.com/ycphs/openxlsx/blob/8b9d5af3b528ba53c940a6194b2875553f4ebef0/R/workbook_write_data.R#L27-L36

[Edit:] You might wanna run an adaption of this on your data.frame to spot and correct the issue in your data: `lapply(iris, class)`

**Comment by KptnKermit** [comment]
Running apply(income, class) produces following output:
 lapply(income,class)
$IBAN
[1] "character"

$Buchungsdatum
[1] "POSIXlt" "POSIXt" 

$Valutadatum
[1] "POSIXlt" "POSIXt" 

$Waehrung
[1] "character"

$Betrag
[1] "numeric"

$Buchungstext
[1] "character"

$Umsatztext
[1] "character"

$Verursacher
[1] "character"

$Kategorie
[1] "character"

$costtype
[1] "character"

$week
[1] "POSIXct" "POSIXt" 

$month
[1] "POSIXct" "POSIXt" 

$year
[1] "POSIXct" "POSIXt"

**Comment by JanMarvin** [comment]
Hi @KptnKermit,

thanks for the output. The issue is that your input data contains lists (as mentioned previously). Two of your columns are of type `POSIXlt` which is a list only shown to the user as a single line in the data.frame. I have pushed a pull request #189 that will handle this.

Until then you could use this to convert your dates 
```r
# function to check for POSIXlt, returns a single line named logical vector
isPOSIXlt <- function(data) sapply(lapply(data, class), FUN = function(x) any(x == "POSIXlt"))

# convert any POSIXlt to POSIXct
income[isPOSIXlt(income)] <- lapply(income[isPOSIXlt(income)], as.POSIXct)
```

Just to show what a POSIXlt looks like
```r
> income$Buchungsdatum[[1]]
[1] "2019-08-13 UTC"
> unlist(income$Buchungsdatum[[1]])
  sec   min  hour  mday   mon  year  wday  yday isdst 
    0     0     0    13     7   119     2   224     0 
```

**Comment by KptnKermit** [comment]
Worked perfectly, thanks for your kind support. Best regards Werner
