### ISSUE TITLE
writeFormula: limitations of supported functions?

### ISSUE THREAD

**Issue by b4D8** [ycphs/openxlsx#160]
Is there a limitation in available functions?
If so could you please provide information about this in the documentation?

If not, I don't understand why I can't make `CONCAT()` and `TEXTJOIN()` work for instance.

I got many function to work fine (with english naming and comma separators) but those two don't seem to be recognized by LibreOffice (returns `#NAME?` error)...

**To Reproduce**

```r
workbook <- openxlsx::createWorkbook()
openxlsx::addWorksheet(workbook, "worksheet")
test <- c('TEXTJOIN("",1,$B2:$Z2)','CONCAT($B3:$Z3)','SUM($B4:$Z4)')
openxlsx::writeFormula(workbook, sheet = "worksheet", x = test, startCol = 1, startRow = 2)
openxlsx::saveWorkbook(workbook, getwd(), overwrite = TRUE)
```

What makes me think it might be a bug:
- the `SUM()` function in the above minimal reproducible example do work so syntax is right
- the functions `CONCAT()` and `TEXTJOIN()` do work when I manually revalidate each one of them with the "Function Wizard"... 

Am I missing something? 

Thanks for you help.

**Environment:**
Debian 10 / LibreOffice 7.0.4.2 / R 4.0.4

**Comment by JanMarvin** [comment]
Might not be a complete solution, but it seems that these are somehow newer Excel functions implemented differently. Both work as expected, if `_xlfn.` is added added as prefix to the function name. A working minimal example below. Unless there is a complete Excel function list, we could match with, I assume it is up to the user to figure these out.

```r
workbook <- openxlsx::createWorkbook()
openxlsx::addWorksheet(workbook, "worksheet")

ltrs <- matrix(1:26, nrow = 4, ncol = 26, byrow = T)
writeData(wb = workbook, sheet = "worksheet", x = ltrs, colNames = FALSE)

test <- c('_xlfn.TEXTJOIN("",1,$B2:$Z2)','_xlfn.CONCAT($B3:$Z3)','SUM($B4:$Z4)')
openxlsx::writeFormula(workbook, sheet = "worksheet", x = test, startCol = 1, startRow = 6)

openxlsx::saveWorkbook(workbook, "/tmp/test.xlsx", overwrite = TRUE)
```

**Comment by JanMarvin** [comment]
Here is a list: [excel functions alphabetical](https://support.microsoft.com/en-us/office/excel-functions-alphabetical-b3944572-255d-4efb-bb96-c6d90033e188)

Including version indicators. I assume the list could be used to parse the `writeForumla` input to insert `_xlfn.` if required. Though I leave this for someone else to figure out.
