### ISSUE TITLE
textWrap gives corrupted sheet

### ISSUE THREAD

**Issue by SHAESEN2** [ycphs/openxlsx#17]
Hey,

When I use wrapText=TRUE I obtain a corrupted file:

```{r}
wb <- createWorkbook()

addWorksheet(wb, "Expenditure", gridLines = FALSE) 

writeData(wb, sheet = 1, USPersonalExpenditure, rowNames = TRUE)

bodyStyle <- createStyle(fontSize=10, border="TopBottomLeftRight", borderColour = "black" , wrapText=TRUE)
headerStyle <- createStyle(fontSize=14, border="TopBottomLeftRight", borderColour = "black", textDecoration="bold")

addStyle(wb, sheet = 1, bodyStyle, rows = 2:6, cols = 1:6, gridExpand = TRUE)
addStyle(wb, sheet = 1, headerStyle, rows = 1, cols = 1:6, gridExpand = TRUE)

setColWidths(wb, 1, cols=1, widths = 21) ## set column width for row names column

saveWorkbook(wb, "addStyleExample.xlsx", overwrite = TRUE)

```
I attached a file with and without text wrapping for your convenience.

[addStyleExample_wrapF.xlsx](https://github.com/ycphs/openxlsx/files/3887894/addStyleExample_wrapF.xlsx)

[addStyleExample_wrapT.xlsx](https://github.com/ycphs/openxlsx/files/3887899/addStyleExample_wrapT.xlsx)

**Comment by ycphs** [comment]
Could you please provide a functional example. 
`USPersonalExpenditure` has no assigned values.

**Comment by SHAESEN2** [comment]
```{r}
USPersonalExpenditure <- data.frame(
  `1940` = c(22.2, 10.5, 3.53, 1.04, 0.341),
  `1945` = c(44.5, 15.5, 5.76, 1.98, 0.974),
  `1950` = c(59.6, 29, 9.71, 2.45, 1.8),
  `1955` = c(73.2, 36.5, 14, 3.4, 2.6),
  `1960` = c(86.8, 46.2, 21.1, 5.4, 3.64),
  stringsAsFactors = FALSE,
  check.names = FALSE)
```

**Comment by JoshuaSturm** [comment]
I've been having the same issue. Excel has always been able to repair the file automatically, but it's become a nuisance, so I've been trying to fix it.

The error log pointed to /xl/styles.xml as the culprit. I renamed my corrupted xyz.xlsx to xyz.zip, opened the styles file, and found this.

![Capture](https://user-images.githubusercontent.com/22535419/69648694-c905c400-1039-11ea-9d9a-491fcf386717.PNG)

In the center, there should be a space before "wrapText"; I believe this is what's causing the issue.

I'm trying to determine how that style is generated, and I'll submit a pull request if/when I find it.

**Comment by SHAESEN2** [comment]
Hey JoshuaSturm,

I checked and tested your fix. It solved the issue. 

Thank you for the help. Very much appreciated !!!
