### ISSUE TITLE
c++ exception when importing a data column with mixed type

### ISSUE THREAD

**Issue by Chris-Stockbridge** [ycphs/openxlsx#172]
A column with mixed date and text types causes a c++ exception.

**To Reproduce**
1. Create an XLSX file with two cells. One filled with a date and set to "Date" display type, the other with text such as '2001'.
2. Attempt to import this file using read.xlsx()
3. See that it fails with an error message of:
`Error in read_workbook(cols_in = cell_cols, rows_in = cell_rows, v = v,  (myScript.R#95): c++ exception (unknown reason)`

**Expected behavior**
Any of:
1) Return an error specifying what happened (possibly including the row/column with the error)
2) Return NA for invalid dates and issue a warning
3) Return the column as text. Items with a date format can be returned as the text representation of that date.

**Comment by Chris-Stockbridge** [comment]
I am almost certain the issue comes from the line
`datetmp[ri] = Rcpp::Date(atoi(dt_str.substr(5,2).c_str()), atoi(dt_str.substr(8,2).c_str()), atoi(dt_str.substr(0,4).c_str()) );`
in buildMatrixMixed()

Would you consider a fix such as:
```
try{
    datetmp[ri] = Rcpp::Date(atoi(dt_str.substr(5,2).c_str()), atoi(dt_str.substr(8,2).c_str()), atoi(dt_str.substr(0,4).c_str()) );
}catch(const std::out_of_range& orr) {
    std::cerr << "Out of range trying to read date. " << orr.what() << "\n" << dt_str << "\nrow: " << ri << "\ncol: " << i << "\n";
    datetmp[ri] = NA_REAL;
}
```
or would it be better to `throw;` instead of replacing the offending element with an NA value?

**Comment by ycphs** [comment]
I think a the package would benefit from a fix you proposed, because having the information of the location of the error should help the users to locate and solve the issue conveniently.

Do you want me to create a PR, or would you like to create one?

**Comment by Chris-Stockbridge** [comment]
After giving it more thought I am leading towards outputting an error and then failing so that the user can fix the issue on their own, and there is no data loss, even if they ignore the message. If you like that solution I can create the PR for it.
