### ISSUE TITLE
Output of `writeComment()` is note rather than comment in Excel 365

### ISSUE THREAD

**Issue by MokeEire** [ycphs/openxlsx#173]
**Describe the bug**
Using `writeComment()` to add a comment to a workbook writes a _note_ instead of a comment in Excel 365 (Windows 10). Both have merit, but it would be great to be able to make comments as well as notes.

**To Reproduce**
```
test = createWorkbook()
addWorksheet(test, "Test")
writeComment(test, "Test", 1, 1, createComment("This is a note"))
saveWorkbook(test, "test.xlsx")
```

An example of the difference between the two:

![excel_notevcomment](https://user-images.githubusercontent.com/19700454/114234531-c0164980-9933-11eb-94a3-0d3c86423ea7.png)

**Comment by JMPivette** [comment]
A bit of information if someone wants to fix this issue:
https://support.microsoft.com/en-us/office/the-difference-between-threaded-comments-and-notes-75a51eec-4092-42ab-abf8-7669077b7be3

In Excel 365, what is called `note` is in fact exactly the same thing as `comment` in earlier versions of Excel. 
What is called `comment` in Excel 365 is a new feature that is also called `threaded comment` 

`threaded comment` are a bit more complicated than `note` . in Addition to the text itself , there are relationship to a person, a parent ` threaded comment` (in case of reply) and a date.

You can explore the structure by unzipping you workbook:
![image](https://user-images.githubusercontent.com/46813298/114676107-3c7ca400-9d09-11eb-9915-9d03fbb2a498.png)

Not sure someone will try to implement this feature knowing the complexity versus the benefit but I might be wrong :-)
