### ISSUE TITLE
Format a subset of text within a cell

### ISSUE THREAD

**Issue by Michael-Sheppard** [ycphs/openxlsx#177]
There doesn't seem to be any documentation or examples of applying formatting to a subset of text within a cell. I know how to use conditionalFormatting to apply formatting to an _entire cell_, but it would be great if I could make a particular sentence within a cell bold. 

Example: 

This text should fall within one cell. This sentence should not be bold. **This sentence should be bold.** 

Does this functionality not exist?

**Comment by JanMarvin** [comment]
Closing because it is a duplicate of #46 . There I explained how it can be done (though untested). For further discussion please use #46.
