### ISSUE TITLE
Request: Add conditionalFormatting parameter stopIfTrue

### ISSUE THREAD

**Issue by cwolcott** [ycphs/openxlsx#178]
**Is your feature request related to a problem? Please describe.**
Can not set the option to Stop processing conditional formatting if the current rule evaluates to TRUE.

**Describe the solution you'd like**
  Add an additional parameter to function conditionalFormatting. Default is FALSE
`   conditionalFormatting(wb, tabMeanTemp, rows=2:17, cols=4:25, type="contains", rule="LFT", style=cfLftStyle, stopIfTure=TRUE)`

**Describe alternatives you've considered**
None

**Additional context**
Excel screen shot of the "Stop if True" parameter

<img width="732" alt="conditionalFormatting stopifTrue" src="https://user-images.githubusercontent.com/3777526/115131247-9b217680-9fc4-11eb-89aa-7d28264c714e.png">

**Comment by klar-C** [comment]
Hi - is there an approximate time-line? Or maybe a workaround?

**Comment by JGWestie** [comment]
Also interested in this feature.
