### ISSUE TITLE
write.xlsx doesn't accept argument tableName

### ISSUE THREAD

**Issue by bwelman** [ycphs/openxlsx#187]
Steps to reproduce:
write.xlsx(iris, file = "test.xlsx", asTable = TRUE, tableName = "mytable")

Version of openxlsx: 4.2.3

**Comment by ycphs** [comment]
Could you please provide a file with the actual result and one with the expected?

**Comment by bwelman** [comment]
library(openxlsx)
write.xlsx(iris, file = "irisdata.xlsx", asTable = TRUE, sheetName="data", tableName ="tableIris")

The result is an excel file with a correct sheetname but with tablename "Table3" and I expected a tablename "tableIris".
According to the documentation writeDataTable is used, and that function has an argument tableName.
