### ISSUE TITLE
New feature: buildWorkbook()

### ISSUE THREAD

**Issue by jmbarbone** [ycphs/openxlsx#192]
I've been toying with a bit of a rewrite of `write.xlsx()` which separates the building and saving process.  Ideally, a (named) list with `...` params could be passed to something like `buildWorkbook()` which would generate a `Workbook` object that can then be further modified before saving -- often something I personally find myself doing and could see a general utility.  `write.xlsx()` would then essentially be shorthand for ...

```r
wb <- buildWorkbook(data_list, ...)
saveWorkbook(wb, file)
```
... when finer edits would not be necessary.

The process of this would involve a better method of passing/matching parameters -- would would resolve issues like like #187 and wouldn't require additional edits when new params are added -- without changing the current use of `write.xlsx()`

**Comment by ycphs** [comment]
There exists already a function for your request. 

[createWorkbook](https://ycphs.github.io/openxlsx/reference/createWorkbook.html)

If it doesn't fit your needs, please let me know.

**Comment by jmbarbone** [comment]
`createWorkbook()` just initializes the `Workbook` object.  The proposed `buildWorkbook()` would essentially extract the initial part of `write.xlsx()` in which the workbook is built according the input (e.g., data.frame, list) and the additional params passed to futher functions like `writeData`, `writeDataTable`, and `setColWidths` but will not try to save the object.

You can see some of the development here:  
https://github.com/jmbarbone/openxlsx/blob/writexlsx-params/R/writexlsx.R#L124-L128
https://github.com/jmbarbone/openxlsx/blob/writexlsx-params/R/build_workbook.R

**Comment by ycphs** [comment]
Now I understand your request correctly.

The idea is good and I fully support the concept. 

Writing the data seems quite straightforward to implement as you have shown. I expect more difficulties when it comes to styles, widths, heights and other layout topics.

What is your idea to cover the layout topics?

**Comment by JanMarvin** [comment]
I like the idea and it will solve the issue of duplicated code in the write functions.
