### ISSUE TITLE
conditionalFormatting highlighting error

### ISSUE THREAD

**Issue by ponnet** [ycphs/openxlsx#193]
Hello,
Below please find the attempt to highlight neighboring cells that differ from each other. The problem at hand is to find differences between old and new versions of data frame (I only need to highlight the 2nd column but still working on that). The screenshot below shows that once I skip the column headers, the first row gets highlighted despite identical values.

```
wb <- createWorkbook()
addWorksheet(wb, "Summary")
negStyle <- createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE")
writeData(wb, "Summary", tibble(id = as.character(c(1:10)),nonid = as.character(c(1:5,7:11))), startCol = 1, startRow = 1, rowNames = F)
conditionalFormatting(wb,"Summary", cols = 1:2, rows = 2:11,
                                rule = "$A1!=$B1", 
                                style = negStyle)
saveWorkbook(wb, 'file.xlsx', overwrite = TRUE)
```
Here is the screenshot:
![image](https://user-images.githubusercontent.com/25302978/119902884-d7c28500-bf15-11eb-836a-02f6af375eb4.png)

Thanks - any help is greatly appreciated!
Is there a way just to pass indexes (such as [1,2]) that will highlight row 1 column 2?

**Comment by ycphs** [comment]
Hi,

If you compare the values of the second row on wards with the conditional formatting, it should be the expected result.

```
wb <- createWorkbook()
addWorksheet(wb, "Summary")
negStyle <- createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE")
writeData(wb, "Summary", tibble(id = as.character(c(1:10)),nonid = as.character(c(1:5,7:11))), startCol = 1, startRow = 1, rowNames = F)
conditionalFormatting(wb,"Summary", cols = 1:2, rows = 2:11,
                      rule = "$A2!=$B2", 
                      style = negStyle)
saveWorkbook(wb, 'file1.xlsx', overwrite = TRUE)
```

A1 and B1 are the header information.

**Comment by ponnet** [comment]
Thanks so much!

 Is there a way to pass indexes of a cell to be highlighted as well?




> Hi,
> 
> If you compare the values of the second row on wards with the conditional formatting, it should be the expected result.
> 
> ```
> wb <- createWorkbook()
> addWorksheet(wb, "Summary")
> negStyle <- createStyle(fontColour = "#9C0006", bgFill = "#FFC7CE")
> writeData(wb, "Summary", tibble(id = as.character(c(1:10)),nonid = as.character(c(1:5,7:11))), startCol = 1, startRow = 1, rowNames = F)
> conditionalFormatting(wb,"Summary", cols = 1:2, rows = 2:11,
>                       rule = "$A2!=$B2", 
>                       style = negStyle)
> saveWorkbook(wb, 'file1.xlsx', overwrite = TRUE)
> ```
> 
> A1 and B1 are the header information.

**Comment by ycphs** [comment]
Please take a look, if the [getCellRefs](https://ycphs.github.io/openxlsx/reference/getCellRefs.html) function helps.
