### ISSUE TITLE
Number stored as text error persists after numFmt

### ISSUE THREAD

**Issue by ayushnoori** [ycphs/openxlsx#195]
Hi there - thanks for creating such a useful package! `openxlsx` has proved invaluable in my efforts to present data in a readable fashion.

I am currently attempting to create a formatted table from an R `data.frame`. I use `writeData()` along with multiple `addStyle` and `mergeCell` calls. Some columns are of mixed type (i.e., contain both text and numbers). When I write to the Excel file, I get the `Number Stored as Text` error.

![image](https://user-images.githubusercontent.com/43010710/120947550-bec78a00-c6f4-11eb-96fd-faaca0161b27.png)

I have attempted to resolve by running:
```
addStyle(wb, "my_sheet", style = createStyle(numFmt = "NUMBER"), rows = i, cols = j, stack = T, gridExpand = T)
```
before I save the workbook, to no avail - where `wb` is my workbook object and (`i`, `j`) are the coordinates of the numeric cells  in the `data.frame`. While I see the the format change to `Number` in the top Excel window (see screenshot below), the error still persists. I have also tried with `numFmt = GENERIC`, which does not work.

![image](https://user-images.githubusercontent.com/43010710/120947468-86c04700-c6f4-11eb-8702-c543e33f34a4.png)

I would be grateful for advice on how to resolve at your earliest convenience.

**Comment by ayushnoori** [comment]
Hi @ycphs, kindly following up on this issue. Thanks for your advice!

**Comment by jmbarbone** [comment]
From what I believe I understand the formatting is not the issue as it is applied after the data are written and types defined.  If you try to apply a Number format in a workbook with numbers stored as text it won't actually convert.

The entire column is defined when building the sheet data as the column type of the R data.frame.  I suppose it may be possible to implement a check for a custom class that would attempt to build the sheet data with mixed types.

**Comment by jmbarbone** [comment]
I've made some edits in a forked branch here: https://github.com/jmbarbone/openxlsx/compare/master...195-numbers-as-text

This _works_ but when opening up the xlsx file there's a warning because of a problem with the content.  It appears to recover the data correctly but obviously that's not ideal.

```r
devtools::load_all()
x <- head(iris, 5)
x$mixed <- structure(list("a", 2, 3, "d", NA), class = "openxlsx_mixed")
wb <- createWorkbook()
addWorksheet(wb, 1)
writeData(wb, 1, x)
openXL(wb)
```

**Comment by Moohan** [comment]
Just re-opening this as I am currently searching for a solution / workaround to this issue. 

There is this question/answer on SO: [Automatically - "Convert numbers stored as text to numbers"](https://stackoverflow.com/questions/52040942/automatically-convert-numbers-stored-as-text-to-numbers) but I think that's a pretty horrible solution.

Our current solution is to just manually dismiss the warnings before onward distribution.
