### ISSUE TITLE
Improve speed using stringi package

### ISSUE THREAD

**Issue by GegznaV** [ycphs/openxlsx#2]
I think this pull request is worth attention awalker89/openxlsx#440: extra speed gives more value.

**Comment by ycphs** [comment]
Currently the checks fail. Maybe you could check the saveWorkbook method.

**Comment by ycphs** [comment]
@noamross, it would be great if you could apply the changes here as well.

**Comment by noamross** [comment]
Hi @ycphs. I'm happy to do this though it will take me a bit to get to it. First I wanted to confirm that you've contacted the original maintainer and CRAN about taking over maintenance - I just want to make sure we aren't fragmenting code ecosystem!

**Comment by ycphs** [comment]
Hi,

I tried to contact him with via mail and linkedin. Do you have another possibility to contact the original maintainer? I just thought that it is a pity that the package has the status orphaned on CRAN.

**Comment by noamross** [comment]
I don't have any better contact for them.  I agree - I would suggest making a small update fixing the current CRAN notes and submitting to take over the maintenance before doing major updates.

**Comment by ycphs** [comment]
Published on CRAN

Looking for new enhancements and features.
