### ISSUE TITLE
Writing hyperlink formula after upgrading to version 4.2.4

### ISSUE THREAD

**Issue by kbzsl** [ycphs/openxlsx#200]
**Describe the bug**
I found an issue when writing an hyperlink formula (`writeFormula`) after upgrading the `openxlsx` from 4.2.3 -> 4.2.4.

**To Reproduce**
Here is an example code:
```
library(dplyr)
library(openxlsx)

channels <- tribble(
  ~channel, ~homepage,
  "ABC", "https://www.abc.net.au/",
  "BBC", "https://www.bbc.com/",
  "CBC", "https://www.cbc.ca/"
)

channels <- channels |> 
  mutate(formula = paste0(
    '=HYPERLINK("', 
    homepage, 
    '", "', 
    channel, 
    '")')
  )

wb <- createWorkbook()
addWorksheet(wb, "channels")
writeDataTable(wb, "channels", channels, tableName = "channels")
writeFormula(wb, "channels", channels$formula, startRow = 2, startCol = 1)
freezePane(wb, "channels", firstRow = TRUE)
setColWidths(wb, "channels", cols = 1:ncol(channels), widths = "auto")
saveWorkbook(wb, file = here::here("temp",  "channels.xlsx"), overwrite = TRUE)
```

**Screenshots**

screenshot when using 4.2.3 (desired outcome):

![openxlsx_4 2 3](https://user-images.githubusercontent.com/15076626/122732952-06195300-d27d-11eb-8852-fbc2b31b22ac.png)

screenshot when using 4.2.4

![openxlsx_4 2 4](https://user-images.githubusercontent.com/15076626/122732968-0a457080-d27d-11eb-9ad8-53c7d302fecf.png)

**Comment by ycphs** [comment]
I will take a look at it
