### ISSUE TITLE
Is it possible to add the option save with ”read-only recommended”?

### ISSUE THREAD

**Issue by kbzsl** [ycphs/openxlsx#201]
![read-only](https://user-images.githubusercontent.com/15076626/122735192-17635f00-d27f-11eb-83f8-71445e43d9cb.png)

**Comment by ycphs** [comment]
Could you please provide two files one with the option active and one default file?

**Comment by kbzsl** [comment]
Here are the files.

[no_option.xlsx](https://github.com/ycphs/openxlsx/files/6685590/no_option.xlsx)

[read-only_option.xlsx](https://github.com/ycphs/openxlsx/files/6685591/read-only_option.xlsx)

**Comment by kbzsl** [comment]
It’s most probably the `<DocSecurity>2</DocSecurity>` in the `docProps\app.xml`.
Please refer to: [DocumentSecurity Class](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.extendedproperties.documentsecurity?view=openxml-2.8.1)

In the Excel,  this option can be found in the `Save As` menu, at  the `Tools | General Options`.

**Comment by ycphs** [comment]
Thank you for your input. That was really helpful.

**Comment by JanMarvin** [comment]
I've pushed a draft to implement this in #202. The `DocSecurity` string is correctly written, but I could not test the functionality with LibreOffice.
