### ISSUE TITLE
Cannot read .xlsm files

### ISSUE THREAD

**Issue by david-f1976** [ycphs/openxlsx#205]
`read.xlsx()` has been updated so that an error is produced if the file extension of the file being read is not .xlsx. I have been reading .xlsm files without issue in prior releases.

This is on 4.2.4 of openxlsx; it was working on 4.2.3.

**Comment by ycphs** [comment]
If you install the development version, the bug should be fixed.

```
install.packages(c("Rcpp", "devtools"), dependencies = TRUE)
require(devtools)
install_github("ycphs/openxlsx")
```

**Comment by david-f1976** [comment]
Working here now thanks
