### ISSUE TITLE
write.xlsx "_xb025_" result error

### ISSUE THREAD

**Issue by ghost** [ycphs/openxlsx#206]
**Describe the bug**

write.xlsx xb025 result error

**To Reproduce**

```
test_char <- "_topic_ext_xb025_tm"
df <- data.frame(col = test_char)
openxlsx::write.xlsx(df, "~/Downloads/test_char.xlsx")
```

**Expected behavior**
It should be save "_topic_ext_xb025_tm"

**Screenshots**
It should be like this:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/30428489/123189475-72d85b80-d4d0-11eb-80a8-96ce0af55c83.png">

Actually result: Error

<img width="207" alt="image" src="https://user-images.githubusercontent.com/30428489/123189496-7bc92d00-d4d0-11eb-8869-a074e3f21176.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - openxlsx version: Documentation for package ‘openxlsx’ version 4.2.4

**Comment by ycphs** [comment]
it seems that the issue only appears with Microsoft office. libreoffice doesn't have this behavior.

Maybe it is a bit more complicated.

**Comment by ghost** [comment]
> it seems that the issue only appears with Microsoft office. libreoffice doesn't have this behavior.
> 
> Maybe it is a bit more complicated.

Could it be Microsoft's problem?

**Comment by ycphs** [comment]
At least it looks like that.

**Comment by ycphs** [comment]
As far as I checked it is an issue just with Micrcosoft.
