### ISSUE TITLE
read.xlsx() can no longer parse .xlsm files

### ISSUE THREAD

**Issue by dseynaev** [ycphs/openxlsx#209]
we were using openxlsx `4.2.3` before and successfully parsing `.xlsm` files with `read.xlsx`

in `4.2.4` we see:
```
openxlsx can only read .xlsx files
```

my guess is this was introduced here:
https://github.com/ycphs/openxlsx/commit/86070beda7d12defa1c0fba622c2f58312d1256c#diff-43a394a441eb434c8b24866cf52453aa6dbca568a67a60e98d08ebaab8124603L119-L121

is it intended for `read.xlsx` to not support `.xlsm`? or was the regex pattern improperly generalized?

**Comment by JanMarvin** [comment]
Hi @dseynaev , the change was most likely unintended. Could you create a pull request to modify this regex?

**Comment by ycphs** [comment]
I think we can close the issue

**Comment by jormercury** [comment]
Thanks for fixing this, I had to instruct several people to downgrade to 4.2.3. Is it possible to release a stable version with this fix soon? It seems to me like a simple fix, but with large consequences for anyone trying to read in xlsm files using openxlsx.
