### ISSUE TITLE
Writing hyperlinks leads to garbled output with version 4.2.4

### ISSUE THREAD

**Issue by arnhew99** [ycphs/openxlsx#212]
**Describe the bug**
Attempting to write (internal) hyperlinks is generating erroneous pseudo-hyperlinks.

**To Reproduce**
```
require(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, "Overview")
writeData(wb, "Overview", "Overview", rowNames=FALSE, colNames=FALSE, startCol=1, startRow=1)
writeFormula(wb, "Overview", x='=HYPERLINK(\"#Overview!A1\",\"Overview\")',startCol=1,startRow=3)
writeFormula(wb, "Overview", x=makeHyperlinkString(sheet = "Overview", row = 1, col = 1, text="Overview"),startCol=1,startRow=4)
saveWorkbook(wb, file="test_hyperlink.xlsx", overwrite=TRUE)
```

**Expected behavior**
See screenshot - should write "Overview" with a hyperlink back to A1 of sheet named Overview. Instead we get a sort-of hyperlink where R/openxlsx appears to have garbled the hyperlink string

**Screenshots**
![openxlsx_hyperlink_broken](https://user-images.githubusercontent.com/1764807/123998489-7173cb00-d9c9-11eb-93b5-1ced4c44f283.png)
![openxlsx_hyperlink_working](https://user-images.githubusercontent.com/1764807/123998492-720c6180-d9c9-11eb-90b7-7846ba32c456.png)

**Additional context**
Appears to be a bug introduced in 4.2.4. The code works fine in 4.2.3 (on R 4.1.0 and on R 4.0.2)

**Comment by ycphs** [comment]
the development version already has the relevant fix for this issue.

#203 

Please report if the fix doesn't work for you. Please try the following

```
require(devtools)
install_github("ycphs/openxlsx")
```

**Comment by arnhew99** [comment]
Great, that fix works. Thank you!
