### ISSUE TITLE
Version 4.2.4 cause text rotation formating lost on saving workbook.

### ISSUE THREAD

**Issue by GordonAn** [ycphs/openxlsx#228]
**Version 4.2.4 cause  text rotation formating lost on saving workbook**

After loading a workbook with text rotation 90 degree,   Direct saving the workbook without any change. The resulted Excel file, when opened in Excel, the text become horizontal and column width also changed.  In versino 4.2.3, the text rotation formating is kept without any problem.   I am using R on windows, and with Excel 360.

** The following 3 lines of codes will reproduce the issue**

library("openxlsx")  
packageVersion("openxlsx")  #Needs version4.2.4 to reproduce the issue
 
Wb<-loadWorkbook("InputTestFile_V424NotkeepTextRotation.xlsx")
saveWorkbook(Wb, file="Output_V424NotkeepTextRotation.xlsx", overwrite = TRUE, returnValue = TRUE)
#Verision 4.2.3 works fine
#Version 4.2.4 lost text rotation format and column Width
 

**Expected behavior**
The text rotation formatting be kept.

**Screenshots**
If applicable, add screenshots to help ex
![lost text rotation on saving](https://user-images.githubusercontent.com/30178216/125599720-4d97f415-b49c-4fc2-a637-0586bae1d319.jpg)
plain your problem.

**Desktop (please complete the following information):**
 - OS:  Windows
  
The attached is the input excel and the output 
[InputTestFile_V424NotkeepTextRotation.xlsx](https://github.com/ycphs/openxlsx/files/6815037/InputTestFile_V424NotkeepTextRotation.xlsx)
[Output_V424NotkeepTextRotation.xlsx](https://github.com/ycphs/openxlsx/files/6815039/Output_V424NotkeepTextRotation.xlsx)

**Comment by gigsterdev9** [comment]
This happened to me too. Existing formatting is altered on an Excel file once a workbook is opened and then saved on to. Rolling back to 4.2.3 appear to have addressed the issue for me.

**Comment by s-fleck** [comment]
I'm having the same issues, for me even very basic formatting (bold, centred, etc...) gets lost

**Comment by JanMarvin** [comment]
A potential fix is in #237 could any of you test this please?

**Comment by JanMarvin** [comment]
Should be fixed in https://github.com/ycphs/openxlsx/commit/0fc1c08ceebfa6a9fd50cd54c4bb55459b2900a5
