### ISSUE TITLE
Error with Rcpp package

### ISSUE THREAD

**Issue by bensenmansen** [ycphs/openxlsx#229]
**Describe the bug**
Since a couple days using read.xlsx to import an excel-sheet to a dataframe produces the following error for me:

Error in getChildlessNode(xml = workbookRelsXML, tag = "Relationship") : 
  function 'Rcpp_precious_remove' not provided by package **'Rcpp'**

Re-install of openxlsx, rcpp, RStudio and R for Windows did not help. 

**Desktop**
 - OS: Windows 10
 - R: 4.1.0 
- RStudio: 1.4.1717

**Comment by JanMarvin** [comment]
Hi @bensenmansen , could you please provide the output of `sessionInfo()`. Most likely the problem should go away once you reinstall and reload `Rcpp`, see [this SO](https://stackoverflow.com/a/68429226/12340029).

**Comment by bensenmansen** [comment]
Thank you very much for the quick reply. I realise a mistake in my post above. So far, I was not able to reinstall rcpp due to access restrictions to some of the required folders by my organisation. Will try to solve it this way first.
