### ISSUE TITLE
Clarification documentation makeHyperlinkString

### ISSUE THREAD

**Issue by SHAESEN2** [ycphs/openxlsx#23]
I was interesting in creating an external link to a docx file in an excel cell. I went through your examples and this was the one that came closest:

```{r}
## Link to file - Text to display
writeFormula(wb, "Sheet1", startRow = 3
  , x = makeHyperlinkString(sheet = "testing", row = 3, col = 10
    , file = system.file("loadExample.xlsx", package = "openxlsx"), text = "Link to File."))
```
In the corresponding excel file I got following formula: =HYPERLINK("[]'testing'!J3", "Link to File."). However, it is not really clear what this is accomplishing. An additional comment in the R file that explains this would be helpful.

Next, I played around with it and found that if I change the formula to: =HYPERLINK("[C:/path to file.docx]", "Link to File."), I created a hyperlink to the actual file.

Perhaps an example like this can be added to the documentation?

```{r}
## Link to external file - Text to display
openxlsx::writeFormula(wb, "Sheet1", startRow = 10, startCol=1,
                      x= "=HYPERLINK(\"[C:/Users]\", \"Link to an external file\")")
```
![LinkToExtern](https://user-images.githubusercontent.com/47894155/70302124-89d73000-17fc-11ea-8bbb-288ac5dc78e3.png)
Kind regards.

**Comment by ycphs** [comment]
It would be great to receive a pull request.

Looking forward to it.

**Comment by ycphs** [comment]
thank you for providing the PR #29

**Comment by SHAESEN2** [comment]
Thanks for accepting the PR #29
