### ISSUE TITLE
InsertImage's startrow and starcol limits initial position of image

### ISSUE THREAD

**Issue by AlvaroMCMC** [ycphs/openxlsx#234]
I want to center an image in excel but cannot place it where I want since `insertImage` only allows to place it at first at some specific row/column. In the end, I want to center an image within a range of cells.

Desired functionality: being able to put an image in any position, not only some specific row or col.

![image](https://user-images.githubusercontent.com/21317475/127387999-6ace9ce4-583d-4e21-bdd8-2f4cc67093f3.png)

**Comment by ycphs** [comment]
Unfortunately it seems quite difficult to do that.

The heights and widths of the affected area can be changed independently and would require changing of the positioning after every adaption heights or widths. 

Is there an option in excel to do that?

**Comment by AlvaroMCMC** [comment]
Yes, but with VBA (you can set Top, left, height, width in pixels).

Here an example using VBA:
```
Dim ws As Worksheet
Dim targetCell As Range
Dim picture1 As Picture

Set ws = ActiveSheet 'replace with actual worksheet if possible
Set targetCell = ws.Range("B10")
Set picture1 = ws.Pictures.Insert(fileName1)

With picture1
    .Height = targetCell.MergeArea.Height 'set height first because width will change
    .Top = targetCell.Top
    .Left = targetCell.Left + (targetCell.MergeArea.Width - .Width) / 2
End With
```
