### ISSUE TITLE
v4.2.4 breaks number formatting with borders

### ISSUE THREAD

**Issue by epanormaalijakauma** [ycphs/openxlsx#248]
**Describe the bug**
`write.xlsx(x, file)`-function crashes when `x` contains a column with class `percentage` or `accounting` and an optional parameter `borders = "columns"` is used.

Error message:
```r
Error in if (this.sty$numFmt$numFmtId == 9999) { : 
  argument is of length zero
```

**Expected behavior**
An Excel file output with percent/accounting-formatted column with borders.

**Troubleshooting**
It looks like commit e33ab30e4554e178441e97378d3dce9febdfec8d (v4.2.4) breaks the functionality in `R/borderFunctions.R` due to a possible typo in `colStyle$numFmt`. In the list, there is `numFmtIs = ...` that should be – at least as far as I understand – `numFmtId = ...`. The same applies for both accounting and percentage styles, whereas the others seem to be fine.

**Comment by JanMarvin** [comment]
Hi @Styyrmanni , would you like to open a pull request for this? Otherwise, could you provide steps to reproduce the issue? Thanks

**Comment by epanormaalijakauma** [comment]
Hi @JanMarvin! Here's a very minimal example of the bug:
```r
library(openxlsx)

# Basic data frame
df <- data.frame(number = 1:3, percent = 4:6/100)

# No problems with write.xlsx()
write.xlsx(df, "no_formatting.xlsx", borders = "columns")

# Change column class to percentage
class(df$percent) <- "percentage"

# This time write.xslx() crashes
write.xlsx(df, "percent_formatting.xlsx", borders = "columns")
```

I can also work on a pull request to suggest a fix for this because the reason for malfunction is quite clear based on the troubleshooting above.
