### ISSUE TITLE
What does printerSettings do?

### ISSUE THREAD

**Issue by JanMarvin** [ycphs/openxlsx#253]
I want to understand what this `printerSettings.bin` does. Looking at differences between a Microsoft 365 created xlsx from the example from #231, I found that this `printerSettings.bin` is not included in the MS365 xlsx. Since StackOverflow tells me that it's something Excel creates for printers, can we simply remove it?

https://github.com/ycphs/openxlsx/blob/fade98238d35ab677b78e6daf1c66b1901aa2f15/R/baseXML.R#L424-L426

**Comment by ycphs** [comment]
Then let's remove it
