### ISSUE TITLE
Loading/Saving empty sheets or sheets with "&" in their name

### ISSUE THREAD

**Issue by mictru** [ycphs/openxlsx#254]
**OS:** Windows 10, x86_64-w64-mingw32
**R-Version:** 4.0.5 x86_64
**OpenXSLX-Version:** 4.2.4
**Excel Version:** 2019, 16.0, 32 Bit

**Describe the bug**
Loading a workbook `loadWorkbook` and saving it using `saveWorkbook` corrupts the file if the loaded workbook (only?) contains an totally empty sheet or a sheetname containing "&"

**To Reproduce "empty sheet"**
1. Create a new file with an empty sheet using Excel. Save the file
2. Load the file in r with `wb <- loadWorkbook("path/to/file.xlsx")`
3. Write the file back to disk `saveWorkbook(wb, "path/to/file.xlsx", overwrite = T)`
4. Open the file with Excel (you'll get an error message)

**To Reproduce "& in sheet names"**
1. Create a new, empty excel file with Excel. _Add a space to the first cell (to prevent the first bug)_ and name the sheet "alpha & bravo"
2. Load the file in r with `wb <- loadWorkbook("path/to/file.xlsx")`
3. Write the file back to disk `saveWorkbook(wb, "path/to/file.xlsx", overwrite = T)`
4. Open the file with Excel (you'll get an error message)

**Expected behavior**
Writing an empty sheet to an excelfile (or updating an excelfile that contains an empty sheet) should not produce an error.
Don't know if the excel file format specification allows "&" in sheet names, but since its possible to name the sheet like that in Excel I guess its valid so that should not corrupt the file.

**Comment by JanMarvin** [comment]
most likely the issue with & in the filename is solved in #278

**Comment by JanMarvin** [comment]
might be related to #286
