### ISSUE TITLE
read.xlsx crashes at getCellInfo

### ISSUE THREAD

**Issue by kongkong2006** [ycphs/openxlsx#259]
**Describe the bug**
read.xlsx keeps running when reading a workbook. The rupbuild of the workbook is 4505 (rupBuild="4505").

**Expected behavior**
The workbook should be read in one minute as there are only about 3000 rows * 200 columns.

**Screenshots**
NA

**Example files**
The file is not sharable.

**Comment by JanMarvin** [comment]
Hi @kongkong2006 , thanks for the report. Could you tell us a bit more about this file? Can you read it with different start rows? Can you read different sheets from this workbook? Have you tried reading it with current master or with the latest CRAN version? Can you tell us how the file was created and why you expect that `getCellInfo()` is failing? Can you describe the contents of the file, only cells with numerics, characters and formulas or anything excel specific like images, pivot tables etc.?

**Comment by kongkong2006** [comment]
Thanks for your quick response.
My R version is 4.0.3 and openxlsx is 4.2.4. I
used trace(openxlsx::read.xlsx, browser) to debug.
rupbuild in the worksheet.xml is 4505. There are no error messages.
The workbook only has one worksheet, including a lot of missing data and
mixed numeric and character columns. There are no other complicated things.
I got it from other people. I don't know how they created it. I opened it
with excel 2016 and saved it as a new file.
read.xlsx has no problem reading the new file.

**Comment by JanMarvin** [comment]
Hm, thanks. I'll try to look into it, unfortunately that's not a lot to work with.

**Comment by JanMarvin** [comment]
Could you try the broken file with out current master? (something along the following: `devtools::install_github("ycphs/openxlsx")`.) There have been a few changes to `getCellInfo()` since the last CRAN release, it might be that the issue is already solved.

**Comment by kongkong2006** [comment]
Thanks! Yes, it works partially. We got the dataset. It should have 174
columns and we only got 34. The first column becomes the third column.
Most of the colnames become [1] "X1"     "X2"... it has one more record
than it should have.
Here is the warning message.
Warning message:
In read.xlsx.default("???.xlsx",  :
  NAs introduced by coercion

**Comment by JanMarvin** [comment]
Might be either some kind of inlineStr problem if your file contains characters (I merely implemented the most basic option) or something else is broken like the file without column row names. I fear there is not much we can do without an example file. If opening and saving with Excel works, that might be your best option for now.

PS: I close this issue, feel free to comment/open if something new comes up.

**Comment by kongkong2006** [comment]
Got it. Thanks for your efforts!
