### ISSUE TITLE
functions used from package dependencies require updating. zip::zip()

### ISSUE THREAD

**Issue by andybeet** [ycphs/openxlsx#26]
functions used from package dependencies require updating.

When i run: 
`openxlsx::saveWorkbook()`
i receive the following warning:

Error message: "Note: zip::zip() is deprecated, please use zip::zipr() instead"

 - OS: Windows 10
- Rstudio: 1.2.1335
- R: 3.6.1
- openxlsx: 4.1.3

**Comment by JoshuaSturm** [comment]
Thanks for submitting.

This has been resolved in [09306ce](https://github.com/ycphs/openxlsx/pull/11); updating openxlsx to 4.1.4 should remove the warning.

**Comment by jennaallen** [comment]
Thank you for looking into this issue and for creating such a great package.

I just updated to 4.1.4. When I run 

`saveWorkbook(wb, file = tmp_path, overwrite = TRUE)`

I now get the error 

`Error in zipr(zipfile = tmpFile, include_directories = FALSE, files = list.files(path = tmpDir,  : 
  unused argument (include_directories = FALSE)`
