### ISSUE TITLE
cloneWorksheet returns an error

### ISSUE THREAD

**Issue by RMachineLearningLLC** [ycphs/openxlsx#27]
## Expected Behavior
Clone a sheet on a created workbook

## Actual Behavior
library(openxlsx, lib.loc = "C:/Program Files/R/R-3.3.3/library")
> wb <- createWorkbook("Fred")
> addWorksheet(wb, "Sheet 1")
> cloneWorksheet(wb, "Sheet 2", clonedSheet = "Sheet 1")
Error in wb$cloneWorksheet(sheetName = sheetName, clonedSheet = clonedSheet) : 
  could not find function "validateSheet"

The function validateSheet() is called by: 

wb$cloneWorksheet
Class method definition for method cloneWorksheet()
function (sheetName, clonedSheet) 
{
    clonedSheet = validateSheet(clonedSheet)
    if (!missing(sheetName)) {
        if (grepl(pattern = ":", x = sheetName)) 
            stop("colon not allowed in sheet names in Excel")
........
}

## sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.1.4

loaded via a namespace (and not attached):
[1] tools_3.3.1   Rcpp_1.0.2    stringi_1.4.3 zip_2.0.4    
  - Version of openxlsx:  4.1.4
  - Version of R: 3.3.3

Thanks for looking into it.

David

**Comment by ycphs** [comment]
Hi David,

I tried it to reproduce the error.

Please try to reinstall the package.

I tested the package on RHub with the new test for the cloneWorksheet function.
[rhub Windows Server test](https://builder.r-hub.io/status/openxlsx_4.1.4.9000.tar.gz-9ea2deced92b4a1880879b35dff479ba)

Instead of copying an empty worksheet I recommand to use addWorksheet.

**Comment by ycphs** [comment]
The current development version doesn't have the issue.

Please check.
