### ISSUE TITLE
Function to convert column letters in Excel into integers

### ISSUE THREAD

**Issue by tri-ton** [ycphs/openxlsx#273]
I use openxlsx and show it to colleagues for many years and each time we discuss with someone that it would be great to specify columns in read.xlsx() as letters, not numbers. This fact is the only reason I recently started to show people also the package readxl, where you can easily specify a range like 'A3:G11' for import (but no possibility to omit certain rows or columns from the range prevents me from showing readxl only). Of course, R1C1 style in Excel is a workaround to quickly find out the column numbers, but it is not convenient at all.

I've just figured out that there is the function int2col() in openxlsx and some function like col2int() with kind of inverted behavior would be very convenient to use for that (could not find anything like this in the package). I would expect supplying this function with a single string like "B:F, K, O, X:AD".

Would it be possible to add such a function to the package? Thanks a lot!

**Comment by JanMarvin** [comment]
Hi @tri-ton , yes it's possible, I might have an implementation lying around and there should be an internal function you can use already.

**Comment by JanMarvin** [comment]
PR in #274 
It's not entirely what you requested. You need to specify the entire range, since R does not know that Excel expects the change from Z to AA, but additional wrappers might be added. This was just a function I had lying around and copy-pasted it over.

**Comment by JanMarvin** [comment]
Once this pull request is merged, you can adapt it to your needs. For the example you've given above (`"B:F, K, O, X:AD"`) you can use `strsplit` and `int2col`, `col2int` to customize the output to your needs.

**Comment by tri-ton** [comment]
Hi Jan, thanks a lot for the pull request and sorry for the delayed response. I needed some time to check everything and write the wrapper as you suggested. It sounds perfectly reasonable that `col2int` now behaves fully opposite to `int2col`, so I suggest adding additional short function `c2i` with the simplified input like (`"B:F K O X:AD"`). I have zero experience with GitHub, so here is my code suggestion:
```
#' @name c2i
#' @title Convert a range of Excel columns to integers
#' @description Converts a series of Excel column labels to integers.
#' @param x A character string
#' @export
#' @examples
#' c2i(LETTERS)
c2i <- function(x) {
  
  if (!is.character(x)) {
    stop("x must be character")
  }

  u <- strsplit(x, split=" ", fixed=TRUE)[[1]]
  p <- strsplit(u, split=":", fixed=TRUE)
  q <- c()
  for (i in 1:length(p)) {
    if (length(p[[i]]) == 1) q <- c(q, cell_ref_to_col(p[[i]]))
    else q <- c(q, cell_ref_to_col(p[[i]][1]):cell_ref_to_col(p[[i]][length(p[[i]])]))
  }
  q

}
```
Should I place a pull request or something? I can also prepare a draft for the help page (probably `c2i` and `col2int` should be on the same page or even together with `int2col`).

Speaking of the help page, I've noticed unexpected behavior of `col2int` with small characters like `c("a", "c", "aa")` (I would expect `"A"` and `"a"` working equally on the first thought) and with `:` in inputs like `col2int("A:B")`. If it should work this way, probably small characters are to be mentioned in the man.

**Comment by JanMarvin** [comment]
Hi @tri-ton , feel free to open a pull request. Personally I have no use for such a function (at least not immediately hence haven't written one), but I see that it might be useful if correctly embedded. We can discuss the interface once there is a pull request. Using whitespace as separator seems kinda odd, but that's just a minor thing. If you open the pull request, please add some unittests and of course you're welcome to improve the current man pages.
