### ISSUE TITLE
Automatic time format conversion

### ISSUE THREAD

**Issue by hloefflerwirth** [ycphs/openxlsx#284]
Hi, thanks for your great work on this useful package!

I encountered a problem when loading the following spreadsheet:

![grafik](https://user-images.githubusercontent.com/32058202/139829503-c73364ef-4c41-4019-8b29-22ebf87ae57a.png)

When loading the data using 
`tab <- openxlsx::read.xlsx("name.xlsx")`

the character strings resembling time (such as "15:06:01") are fomated into fuzzy numbers:

![grafik](https://user-images.githubusercontent.com/32058202/139830246-80d6cff7-8390-482f-a8de-ff55ce4ce11b.png)

Is there a simple way to suppress this? Thanks in advance :)

**Comment by JanMarvin** [comment]
Do we somehow lose a `G`? Could you share the xlsx or create a reproduceable example? It might be that the value in the Excel file is different an has some kind of format attached to it. You could see if you can convert it to a string in Excel to see if the issue remains.

Edit: you might run it with `detectDates=TRUE` if this is the issue. Kinda hard to spot
Edit2: I'm unaware how we handle dates that are time stamps. There is no direct R representation for this hours minute second variables. Though I'm aware of some tidyverse package that provides such feature, you might have a look.

**Comment by JanMarvin** [comment]
You can use the following, it depends on the `hms` package.

```R
hms::as_hms(x * 24 * 60 * 60)
```

where x is the value you want to convert.

Edit: you can wrap the output in `as.character` to add it to your output. I won't add the hms package as a dependency to the package, due to the unfortunately large amount of dependencies average tidyverse packages bring along. Enough of the many edits :)

**Comment by JanMarvin** [comment]
there is optionally `openxlsx::convertToDateTime()`, but it creates a POSIX date with 1899-12-31.

**Comment by hloefflerwirth** [comment]
Thank you!
Indeed, there are no G suffixes in some cells, which is part of the information.

I also wrote a little workaround using the the package's conversion function. Given the data loaded from xlsx is this 
![grafik](https://user-images.githubusercontent.com/32058202/139836788-d22c5693-398b-4a26-9f2a-648382f35e58.png)

`conversion <- sapply(strsplit(as.character(openxlsx::convertToDateTime(tab$d))," "),tail,1)`
`tab$d[which(!is.na(conversion))] <- conversion[which(!is.na(conversion))]`

This substitutes all mistakenly converted elements:
![grafik](https://user-images.githubusercontent.com/32058202/139836910-08537f30-515e-4653-85de-0fc0b9b0d557.png)

However, it would be nice to have an option to deactivate all unwanted conversions, if even possible (I don't know how xlsx handles and stores data).

Thanks and best regards!
