### ISSUE TITLE
tag in [Content_Types] refers to empty drawing, triggering error in OpenXml

### ISSUE THREAD

**Issue by acobolew** [ycphs/openxlsx#285]
**Describe the bug**
When there are no drawing objects, the xlsx file contains no /xl/drawings folder but the [Content_Types].xml still contains a tag that refers to a file in that folder. The file will still open OK in Excel, but it will throw an error message in OpenXls: "Specified part does not exist in the package." Files created directly by Excel that don't have drawings do not have the offending tag in [Content_Types].xml

**To Reproduce**
```
library(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, 'Sheet1')
saveWorkbook(wb, 'drawing.in.content.types.but.no.drawing.file.in.xlsx.xlsx')
# Creates  xlsx file with tag in [Content_Types].xml that refers to PartName /xl/drawings/drawing1.xml
# However, there is no /xl/drawings folder and therefore no /xl/drawings/drawing1.xml file
# Excel opens the file OK, but OpenXls throws an error with the following error message:
# "Specified part does not exist in the package"
# 
# If the [Content_Types].xml file is edited to delete the offending tag then the file opens fine in OpenXml
# and also still opens fine in Excel
```

**Expected behavior**
A file that will import into Openxls error-free

**Screenshots**

**Example files**
The R code above produces [drawing.in.content.types.but.no.drawing.file.in.xlsx.xlsx](https://github.com/ycphs/openxlsx/files/7465331/drawing.in.content.types.but.no.drawing.file.in.xlsx.xlsx), which triggers the error in OpenXml.
If that file is opened in Excel, where an immediate "File | Save As" produces [file.saved.by.excel.xlsx](https://github.com/ycphs/openxlsx/files/7465332/file.saved.by.excel.xlsx) then that new file does *not* have the offending tag in [Content_Types].xml

**Additional context**
I have forked-and-cloned openxlsx and pushed a fix to acobolew/openxlsx in branch remove-empty-drawing-from-Content_Types . I will submit a PR with the fix

**Comment by acobolew** [comment]
The /xl/worksheets/_rels/sheet1.xml file has a similar issue, with >= two tags referring to ../drawings even when ../drawings folder is missing. I will expand the PR to address this as well

**Comment by JanMarvin** [comment]
Sure thing, take your time. Could have pushed to the pull request too.

**Comment by acobolew** [comment]
Fork renamed to  remove-refs-to-missing-drawings-from-xml . With today's commit to that fork, the files I create without drawings using now import to OpenXls successfully, so I hope my modifications to method writeSheetDataXML are correct ;)

Will make new PR and show it as addressing issue #285

**Comment by JanMarvin** [comment]
@acobolew I've made a pull request of my own starting from your suggestions. Though it should pass the checks, additional testing is required especially with imported files containing vml imports. The approach I've chosen simply overwrites whatever is in the workbooks vml, if a comment is detected.
