### ISSUE TITLE
Invalid format string in loadWorkbook

### ISSUE THREAD

**Issue by tlapak** [ycphs/openxlsx#293]
As of R 4.1.0 the following bit throws a warning if `extLinksXML` is not empty since the format string does not contain any conversion specifications. I _think_ its last part should read `Target="externalLinks/externalLink%s.xml"` but I haven't tested that or thought through the logic of what's being done exactly.

https://github.com/ycphs/openxlsx/blob/08de207e0c069d75429ecec10f5d6d1b92e9cd46/R/loadWorkbook.R#L449-L452

**Comment by JanMarvin** [comment]
Hi @tlapak , thanks. Makes sense. Could you prepare a pull request and test it?
