### ISSUE TITLE
Multiple groupRows?

### ISSUE THREAD

**Issue by bfreed3** [ycphs/openxlsx#294]
It seems you can only group one set of rows per worksheet with this function. I want to create 3 separate, non-nested groups in the iris data set by Species. Can this currently be done?

**Comment by zykezero** [comment]
In my experience multiple grouped rows in openxlsx will cause the workbook to crash.

**Comment by JanMarvin** [comment]
@bfreed3 currently not possible, though I've implemented such functionality via #297 please have a look if that solves your problem. I've added examples based on the iris dataset.
