### ISSUE TITLE
Missing values generated with setColWidths()

### ISSUE THREAD

**Issue by dkoltg** [ycphs/openxlsx#296]
Hi, 
Since this morning I get an error message telling me that NA values are generated when I create an xlsx-file out of my tables. Going through the code it looks like the bug must be related to the setColWidths() part as all the other parts don't lead to the error message. Here my code 

```
wb <- createWorkbook("File")

## Add some worksheets
addWorksheet(wb, "Tab1")
addWorksheet(wb, "Tab2")

hs1 <- createStyle(halign = "LEFT", wrapText = TRUE, valign = "TOP")

writeData(wb, "Tab1", tab_arztpraxis, colNames = T, rowNames = F,  headerStyle = hs1)
writeData(wb, "Tab2", tab_apotheken, colNames = T, rowNames = F,  headerStyle = hs1)
setColWidths(wb, "Tab1",col=1,widths = "auto")
setColWidths(wb, "Tab2",col=1,widths = "auto")
setColWidths(wb, "Tab1",cols=2:4,widths=10)
setColWidths(wb, "Tab2",cols=2:4,widths=10)



## Freeze Panes
freezePane(wb, "Tab1", firstRow = TRUE)
freezePane(wb, "Tab2", firstRow = TRUE)


## Save workbook
saveWorkbook(wb, "File.xlsx", overwrite = TRUE)
```

Thanks for having a look at it.

**Comment by JanMarvin** [comment]
Hi @dkoltg , unless you've updated anything (did you?), it might be because of your input data. Could you please prepare a minimal reproduceable example. Examples were given in the bug report template you'd choose to ignore.

**Comment by dkoltg** [comment]
Hi, I went several times through my data and couldn't find anything there. I updated the openxlsx package because of an error message in creating a wb yesterday. Could that have an impact?

**Comment by JanMarvin** [comment]
Unless we know your specific setup (your previous version, data and minor things like the operating system) this is kinda hard to tell. My best guess is a very specific "maybe". I'll look into it

**Comment by dkoltg** [comment]
I use R-version 4.0.3 and update or at least tried to update openxlsx to version 4.2.3 (I had some problems with updating the package rio which was recommended in a stackoverflow-post regarding the issue with creating a wb). Do you need any other information?

**Comment by JanMarvin** [comment]
The following works for me just fine (using master branch). Could you have a look if the issue remains on master or tell us about your input data. Is it a data frame and where do you see the missing values?

```R
wb <- createWorkbook("File")

addWorksheet(wb, "Tab1")
addWorksheet(wb, "Tab2")

hs1 <- createStyle(halign = "LEFT", wrapText = TRUE, valign = "TOP")

# the only modification mtcars and cars instead of your data sets
writeData(wb, "Tab1", mtcars, colNames = T, rowNames = F,  headerStyle = hs1)
writeData(wb, "Tab2", cars, colNames = T, rowNames = F,  headerStyle = hs1)

setColWidths(wb, "Tab1",col=1,widths = "auto")
setColWidths(wb, "Tab2",col=1,widths = "auto")
setColWidths(wb, "Tab1",cols=2:4,widths=10)
setColWidths(wb, "Tab2",cols=2:4,widths=10)

freezePane(wb, "Tab1", firstRow = TRUE)
freezePane(wb, "Tab2", firstRow = TRUE)

saveWorkbook(wb, "File.xlsx", overwrite = TRUE)
```

**Comment by dkoltg** [comment]
Hi, it works again, thanks for your help.
