### ISSUE TITLE
Add excel dataTable examples to writeFormula()

### ISSUE THREAD

**Issue by zykezero** [ycphs/openxlsx#299]
Hello!

I really enjoy openxlsx it's been great to use, I want to contribute something that I think would be valuable for the documentation. 
I saw that there is a label for "documentation" so I hope that this is appropriate.

It's regarding dataTable formulas. These formulas have a lot of benefit and I think the documentation should include at least 1 example and as well as explaining how to write the "at this row" / [@[column]] so that when we pass it through writeDataTable that excel is able to read the formula.

#### dataTable formula differences ####
|   |     A       |  B   |      C        |
|---|-------------|------|---------------|
| 1 | SalesPrice  | COGS | SalesQuantity |
| 2 |     20      |  5   |      1        |
| 3 |     30      |  11  |      2        |
| 4 |     40      |  13  |      3        |

Given a basic table like the above, a similarly basic formula for "Total_Sales" would be "=A2 * C2" with the row value changing at each row.
An implementation for this formula using openxlsx::writeFormula would look this (taken from current documentation)
lets say we've read in the data and assigned it to the table "company_sales"
```{r}
#### write in the formula
company_sales$Total_Sales       <- paste(paste0("A", 1:3 + 1L), paste0("C", 1:3 + 1L), sep = " + ")
#### add the formula class
class(company_sales$Total_Sales) <- c(class(company_sales$Total_Sales), "formula")
```
Then we create the workbook, worksheet, and use writeDataTable()

One of the advantages of the excel dataTable syntax is that we don't have to specify row numbers or columns as letters.
The table also grows dynamically, adding new rows as new data is appended and extending formulas to the new rows.
Excel dataTables have named columns that we can use instead of letters.
When writing the formulas within the dataTable in excel we would use the following syntax `[@[column_name]]` to reference the current row.
So the "Total_Sales" formula written in excel in dataTable would look like this;
`=[@[SalesPrice]] * [@[SalesQuantity]]`

If we are writing the formula outside of the dataTable we have to reference the table name.
In this case lets say the table name is 'daily_sales'
`=daily_sales[@[SalesPrice]] * daily_sales[@[SalesQuantity]]`

However, if we were to pass this as the text for the formula to be written it would cause an error because the syntax that excel requires for selecting the current row is different.

We can import an excel file that uses the dataTable formula to view what excel requires.
```{r}
library(openxlsx)
company_sales_wb <- openxlsx::loadWorkbook("company_sales.xlsx")
#### accessing the table
company_sales_wb$tables

#### We care about what is inside the <calculatedColumnFormula> tags.
## name=\"dataTable_Total_Sales\" totalsRowFunction=\"sum\" dataDxfId=\"2\">
## <calculatedColumnFormula>daily_sales[[#This Row],[SalesPrice]]*daily_sales[[#This Row],[SalesQuantity]]</calculatedColumnFormula>
```

Now we can see that excel replaces `[@[SalesPrice]]` with `daily_sales[[#This Row],[SalesPrice]]`
We must then use this syntax when writing formulas for dataTable

```{r}
#### creating example data
example_data <- 
  data.frame(
    SalesPrice = c(20, 30, 40), 
    COGS = c(5, 11, 13),
    SalesQuantity = c(1, 2, 3)
  )

#### Because we want the dataTable formula to propagate down the entire column of the data
#### we can assign the formula by itself to any column and allow that single string to be repeated for each row.

#### base R method
example_data$GrossProfit       <- "grossprofit[[#This Row],[SalesPrice]] - grossprofit[[#This Row],[COGS]]"
example_data$Total_COGS        <- "grossprofit[[#This Row],[COGS]] * grossprofit[[#This Row],[SalesQuantity]]"
example_data$Total_Sales       <- "grossprofit[[#This Row],[SalesPrice]] * grossprofit[[#This Row],[SalesQuantity]]"
example_data$Total_GrossProfit <- "grossprofit[[#This Row],[Total_Sales]] - grossprofit[[#This Row],[Total_COGS]]"

class(example_data$GrossProfit)       <- c(class(example_data$GrossProfit),       "formula")
class(example_data$Total_COGS)        <- c(class(example_data$Total_COGS),        "formula")
class(example_data$Total_Sales)       <- c(class(example_data$Total_Sales),       "formula")
class(example_data$Total_GrossProfit) <- c(class(example_data$Total_GrossProfit), "formula")


#### Tidyverse method
library(tidyverse)
#### add formula column
example_data <-
  example_data %>%
  mutate(
    GrossProfit = "grossprofit[[#This Row],[SalesPrice]] - grossprofit[[#This Row],[COGS]]",
    Total_COGS  = "grossprofit[[#This Row],[COGS]] * grossprofit[[#This Row],[SalesQuantity]]",
    Total_Sales = "grossprofit[[#This Row],[SalesPrice]] * grossprofit[[#This Row],[SalesQuantity]]",
    Total_GrossProfit = "grossprofit[[#This Row],[Total_Sales]] - grossprofit[[#This Row],[Total_COGS]]"
  )

#### We can use the base R method of assigning the formula to each column as above.
#### Or use purrr::walk to assign the formula class using a list of column names.
#### Using `<<-` to pass the formula class to escape the local environment of walk.
walk(c("GrossProfit", "Total_COGS", "Total_Sales", "Total_GrossProfit"), function(col_var)
  class(example_data[[col_var]]) <<- c(class(example_data[[col_var]]), "formula")
)


#### Create the workbook with openxlsx::createWorkbook
example_workbook <- createWorkbook()

#### Add a worksheet to contain the dataTable
addWorksheet(
  wb        = example_workbook,
  sheetName = 'GrossProfit'
)

#### Add the dataTable
writeDataTable(
  wb         = example_workbook,
  sheet      = 'GrossProfit',
  x          = example_data,
  tableStyle = openxlsx_getOp("tableStyle", "TableStyleMedium2"),
  startCol   = 1,
  startRow   = 1,
  tableName  = 'grossprofit'
)

saveWorkbook(example_workbook, "write_dataTable_Formula_example.xlsx", overwrite = TRUE)
```

And if we open write_dataTable_Formula_example.xlsx to view the table we created we can see that the formula has worked.

|   |     A       |  B   |      C        |D|E|F|G|
|---|-------------|------|---------------|-|-|-|-|
| 1 | SalesPrice  | COGS | SalesQuantity |GrossProfit|	Total_COGS|	Total_Sales|	Total_GrossProfit|
| 2 |     20      |  5   |      1        |15|	5|	20|	15|
| 3 |     30      |  11  |      2        |19|	22|	60|	38|
| 4 |     40      |  13  |      3        |27|	39|	120|	81|

We can also see that it has replaced `[#This Row]` with `@`.
(escaping COGS because someone's user name is COGS)

|   |     A       |  B   |      C        |           D             |               E               |                  F                  |                  G                 |
|---|-------------|------|---------------|-------------------------|-------------------------------|-------------------------------------|------------------------------------|
| 1 | SalesPrice  | COGS | SalesQuantity |  GrossProfit            |	         Total_COGS           |	         Total_Sales                |	        Total_GrossProfit          |
| 2 |     20      |  5   |      1        |=[@SalesPrice] - [@\COGS] |	=[@\COGS] \* [@SalesQuantity]  |	=[@SalesPrice] \* [@SalesQuantity]  | =[@[Total\_Sales]] - [@[Total\_COGS]]|
| 3 |     30      |  11  |      2        |=[@SalesPrice] - [@\COGS] |	=[@\COGS] \* [@SalesQuantity]  |	=[@SalesPrice] \* [@SalesQuantity]  | =[@[Total\_Sales]] - [@[Total\_COGS]]|
| 4 |     40      |  13  |      3        |=[@SalesPrice] - [@\COGS] |	=[@\COGS] \* [@SalesQuantity]  |	=[@SalesPrice] \* [@SalesQuantity]  | =[@[Total\_Sales]] - [@[Total\_COGS]]|

For completion, the formula as we wrote it appears as;

|           D             |               E               |                  F                  |                  G                 |
|-------------------------|-------------------------------|-------------------------------------|------------------------------------|
|  GrossProfit            |	         Total_COGS           |	         Total_Sales                |	        Total_GrossProfit          |
|=grossprofit[[#This Row],[SalesPrice]] - grossprofit[[#This Row],[COGS]] |	=grossprofit[[#This Row],[COGS]] \* grossprofit[[#This Row],[SalesQuantity]]  |	=grossprofit[[#This Row],[SalesPrice]] \* grossprofit[[#This Row],[SalesQuantity]]  | =grossprofit[[#This Row],[Total\_Sales]] - grossprofit[[#This Row],[Total\_COGS]]|
|=grossprofit[[#This Row],[SalesPrice]] - grossprofit[[#This Row],[COGS]] |	=grossprofit[[#This Row],[COGS]] \* grossprofit[[#This Row],[SalesQuantity]]  |	=grossprofit[[#This Row],[SalesPrice]] \* grossprofit[[#This Row],[SalesQuantity]]  | =grossprofit[[#This Row],[Total\_Sales]] - grossprofit[[#This Row],[Total\_COGS]]|
|=grossprofit[[#This Row],[SalesPrice]] - grossprofit[[#This Row],[COGS]] |	=grossprofit[[#This Row],[COGS]] \* grossprofit[[#This Row],[SalesQuantity]]  |	=grossprofit[[#This Row],[SalesPrice]] \* grossprofit[[#This Row],[SalesQuantity]]  | =grossprofit[[#This Row],[Total\_Sales]] - grossprofit[[#This Row],[Total\_COGS]]|

**Comment by JanMarvin** [comment]
Thank you @zykezero! Would you be willing to create a vignette out of this? (Preferably without the tidyverse references as these might become outdated before I end this comment, looking at their development speed :smile:, though that's just me.)
We already have two other vignettes and your contribution might get lost here.

**Comment by zykezero** [comment]
Haha yeah, no problem. I started putting it together and accounting for the differences but I've encountered something.

Some dataTable formulas will have have "@" prepended in such a way that excel even considers it an error.
```
library(openxlsx)
[company_sales_dataTable_Formula_example.xlsx](https://github.com/ycphs/openxlsx/files/7573750/company_sales_dataTable_Formula_example.xlsx)

#### creating example data
example_data <- 
  data.frame(
    SalesPrice = c(20, 30, 40), 
    COGS = c(5, 11, 13),
    SalesQuantity = c(1, 2, 3)
  )
example_data$GrossProfit       <- "daily_sales[[#This Row],[SalesPrice]] - daily_sales[[#This Row],[COGS]]"
example_data$Total_COGS        <- "daily_sales[[#This Row],[COGS]] * daily_sales[[#This Row],[SalesQuantity]]"
example_data$Total_Sales       <- "daily_sales[[#This Row],[SalesPrice]] * daily_sales[[#This Row],[SalesQuantity]]"
example_data$Total_GrossProfit <- "daily_sales[[#This Row],[Total_Sales]] - daily_sales[[#This Row],[Total_COGS]]"

#### Using `<<-` to pass the formula class to escape the local environment of lapply.
lapply(c("GrossProfit", "Total_COGS", "Total_Sales", "Total_GrossProfit"), function(col_var)
  class(example_data[[col_var]]) <<- c(class(example_data[[col_var]]), "formula")
)

#### Create the workbook with openxlsx::createWorkbook
company_sales_example <- createWorkbook()

#### Add a worksheet to contain the dataTable
addWorksheet(
  wb        = company_sales_example,
  sheetName = 'daily_sales_wks'
)

#### Add the dataTable
writeDataTable(
  wb         = company_sales_example,
  sheet      = 'daily_sales_wks',
  x          = example_data,
  tableStyle = openxlsx_getOp("tableStyle", "TableStyleMedium2"),
  startCol   = 1,
  startRow   = 1,
  tableName  = 'daily_sales'
)

#### sum dataTable examples
addWorksheet(
  wb        = company_sales_example,
  sheetName = 'sum_examples'
)
### Note: dataTable formula do not need to be used inside of dataTables. dataTable formula are for referencing the data within the dataTable.
sum_examples <-
  data.frame(
    description = c("sum_SalesPrice", "sum_product_Price_Quantity"),
    formula = c(
      "sum(daily_sales[[#Data],[SalesPrice]])",
      "sum(daily_sales[[#Data],[SalesPrice]] * daily_sales[[#Data],[SalesQuantity]])"
    )
  )
class(sum_examples$formula) <- c(class(sum_examples$formula), "formula")

writeData(
  wb       = company_sales_example,
  sheet    = 'sum_examples',
  x        = sum_examples,
  startCol = 1,
  startRow = 1
)

#### dataTable referencing
addWorksheet(
  wb        = company_sales_example,
  sheetName = 'dt_references'
)
### Adding the headers by themselves.
writeFormula(
  wb       = company_sales_example,
  sheet    = 'dt_references',
  x        = "daily_sales[[#Headers],[SalesPrice]:[Total_GrossProfit]]",
  startCol = 1, ## because this formula will populate to the right we only need to insert it in A1.
  startRow = 1
)
### Adding the raw data by reference and selecting them directly.
writeFormula(
  wb       = company_sales_example,
  sheet    = 'dt_references',
  x        = "daily_sales[[#Data],[SalesPrice]:[Total_GrossProfit]]",
  startCol = 1, ## 
  startRow = 2  ## Just as the above the rest of the data will be populated so we only need the correct placement.
)

saveWorkbook(company_sales_example, "company_sales_dataTable_Formula_example.xlsx", overwrite = TRUE)
```

**Comment by JanMarvin** [comment]
Once you have something working, please add it to a rmarkdown file and open a pull request. If you're not familiar, just clone openxlsx via the GitHub Webinterface and push your local branch upstream.

**Comment by jilliant** [comment]
Thanks for this @zykezero, 🥇 this example is really helpful
