### ISSUE TITLE
CRAN publication fails

### ISSUE THREAD

**Issue by ycphs** [ycphs/openxlsx#3]
Currently the Publication on CRAN fails. The error message is the following:

read_workbook.cpp:570:29: warning: '%d' directive writing between 1 and 10 bytes into a region of size 5 [-Wformat-overflow=]
    read_workbook.cpp:506:31: warning: '%d' directive writing between 1 and 10 bytes into a region of size 5 [-Wformat-overflow=]

Looking forward get support fixing the issue.

**Comment by iagogv3** [comment]
Probably you have tried already, but just in case, in the working version on CRAN line 494 is `    char name[6];` Also in current line 574.

**Comment by ycphs** [comment]
I changed it and tried to upload for submission.

I got the following warning:

read_workbook.cpp:576:29: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 5 [-Wformat-overflow=]
  576 |       sprintf(&(name[0]), "X%d", i+1);
      |                             ^~
read_workbook.cpp:576:27: note: directive argument in the range [1, 2147483647]
  576 |       sprintf(&(name[0]), "X%d", i+1);
      |                           ^~~~~


Maybe you can help? The details of the test can be seen at the [cran test results](https://win-builder.r-project.org/incoming_pretest/openxlsx_4.1.2_20191028_095506/)

**Comment by iagogv3** [comment]
I don't know, but I would try to change both `for(int i=0; i < nCols; i++)` by `for(unsigned short i=0; i < nCols; i++)`, following [this answer](https://stackoverflow.com/questions/51697753/how-to-suppress-sprintf-warning-directive-writing-between-1-and-11-bytes-into).
And also `int nCols = *std::max_element(cols.begin(), cols.end()) + 1;` by `unsigned short nCols = *std::max_element(cols.begin(), cols.end()) + 1;`

**Comment by ycphs** [comment]
I tried, but now I have the following massage. Unfortunately the next error appears.

warning: ‘__builtin___sprintf_chk’ may write a terminating nul past the end of the destination [-Wformat-overflow=]

[details](https://win-builder.r-project.org/incoming_pretest/openxlsx_4.1.2_20191028_145917)

**Comment by iagogv3** [comment]
I have just seen, if I am not wrong, that if one declares variable `i` as `unsigned short`, later in `sprintf` should specify `%hu` (or just `%h`?) instead of `%d`. I would try this.

**Comment by iagogv3** [comment]
Could you solve this issue?

**Comment by ycphs** [comment]
Yes I managed to publish the new version on CRAN.

Thank you for your help.
