### ISSUE TITLE
"Worksheet by that name already exists" error - specify name?

### ISSUE THREAD

**Issue by RickPack** [ycphs/openxlsx#30]
Might addWorksheet specify the name of the worksheet associated with the "Worksheet by that name already exists" error? I use this package in functions that create many worksheets so this would help identify my mistake.

**Comment by ycphs** [comment]
Please check the current dev branch [styler](https://github.com/ycphs/openxlsx/tree/styler).

This version should perform the request.

The following snippet should help you install the development version of openxlsx.
`
install_github("ycphs/openxlsx",ref="styler")
`
