### ISSUE TITLE
How to justify text when horizontally alignining it ?

### ISSUE THREAD

**Issue by andresmorago** [ycphs/openxlsx#305]
**Is your feature request related to a problem? Please describe.**
I would like to be able to justify the text on the cell 

**Describe the solution you'd like**
Align the text so its justified on the cell (green text)
![image](https://user-images.githubusercontent.com/13720514/144655214-0e34c3be-3423-468e-9255-2a2dbf10e2c3.png)

**Describe alternatives you've considered**
In addition to `right`, `left`, `center`, Implement a `justify` option under the `halign` parameter
```
bldStyle_body_comments  <- createStyle(fontSize = 12, 
  fontColour = "black", 
  valign="center", 
  wrapText = T, 
  haligh="justify")
```

**Additional context**

**Comment by JanMarvin** [comment]
Hi @andresmorago , I've added a fix in #306, will merge it with master once the CI checks are green. it was simply overlooked when adding the check. Thanks for the report.
