### ISSUE TITLE
Excel fail to open the output created from openxlsx with slicer

### ISSUE THREAD

**Issue by radiance88** [ycphs/openxlsx#313]
**Describe the bug**
I created a simple excel file "Slicer_test.xlsx", with some random data, a pivot table and a slicer.
Nothing wrong when using R openxlsx. I simply use loadWorkbook to load it and then saveWorkbook to save it as another file.
Then when I open the new file it says 'We found a problem with some content in the file. Do you want us to try to recover".
If I click "Yes", it says "The workbook cannot be opened or repaired because it is corrupt"
**To Reproduce**

wb <- loadWorkbook("Slicer_test.xlsx")
saveWorkbook(wb,"Slicer_test_saved.xlsx")

**Expected behavior**
I expect Excel should be able to open the output file with no problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/9069384/148888524-194e131c-2411-4dec-84cf-e466c48d644a.png)
![image](https://user-images.githubusercontent.com/9069384/148888725-1b7e64af-1d80-45a1-85bc-d098d760807a.png)

**Example files**
If applicable, add example files to help explain y
[Slicer_test.xlsx](https://github.com/ycphs/openxlsx/files/7844027/Slicer_test.xlsx)
our problem (`openxlsx` and/or `Excel` created files)

**Comment by JanMarvin** [comment]
Thanks, confirmed. In the created file `xl/workbook.xml` contains multiple entries of `extLst`. That is not supposed to happen and Excel most likely does not like that. I guess I imported that because we were losing some extLst entries, now we have them duplicated. Oh boy

**Comment by JanMarvin** [comment]
A fix for now:
```R
# import your Slicer_test.xlsx
wb <- openxlsx::loadWorkbook("~/gh_issue_313.xlsx")
# keep only the last extLst (the openxlsx created one in this case)
wb$workbook$extLst <- wb$workbook$extLst[2]
# works in ms365
openxlsx::saveWorkbook(wb, "test.xlsx", overwrite = TRUE)
```

**Comment by JanMarvin** [comment]
For some reason `openxlsx` decided, that it wants some `extLst` (most likely due to the slicer found on a sheet), though we failed to check if there are extLst elements we could merge with or even overwrite. Appending seems like the worst idea in this case as it leads to broken files for Excel. If bitten by this: they work fine with LibreOffice.
