### ISSUE TITLE
feature request: allow "format painter" functionality

### ISSUE THREAD

**Issue by deschen1** [ycphs/openxlsx#319]
I often have use cases where I write data to an existing workbook/worksheet in new columns (e.g. assume a new month of data when I already have Jan-Aug or sth. like that and now want to add Sep).

Usually, these worksheets contain some formatting. Some in the sense of that it would not be feasible to create Styles manually and then apply to the new data/column.

So instead, it would be great if there was just some sort of "format painter" function that would do that for me, similar to what I can do directly in Excel. I.e. ideally I would select an input_range like "sheet1!A1:A30" and and output_range like "sheet_new!C1:C30" and would get the styles copied over.

Sorry if such a function already exists and I'm just missing where it is and how to use it.

This is also related to the following SO post: https://stackoverflow.com/questions/70754569/openxlsx-copying-the-same-style-to-a-new-column-added-to-a-worksheet

**Comment by JanMarvin** [comment]
It's already in development for a future release 🤫

**Comment by deschen1** [comment]
oh that's great to hear. You probably don't want to set expectations by sharing some sort of roadmap/timings? But I would of course be curious if we are talking about Q1 2022 or end of year or "whenever I feel like it".

**Comment by JanMarvin** [comment]
I'd say first half of 2022, but as volunteers we are not on anyone's payroll: So it depends :smiley:
