### ISSUE TITLE
Contitional formating on selected rows

### ISSUE THREAD

**Issue by jayieh** [ycphs/openxlsx#324]
```
DF2wb <- as.data.frame(matrix(rexp(200), 10, 4)) #create data frame with random values

colnames(DF2wb) <- c("cf1","cf2","no","cf3") #name columns of DF

wb <- buildWorkbook(DF2wb) #create workbook from DF

#create conditional formating, based of grep of colnames
conditionalFormatting(wb, 1, grep("cf", colnames(DF2wb)), 1:nrow(DF2wb)+1, type = "colourScale", style = c("blue", "white", "red"))

#write workbook to file
saveWorkbook(wb, file = "conditional_formating_test.xlsx", overwrite = T)
```

I was trying to use conditional formatting only on a selected number of discontinuous columns with openxlsx 4.2.5.

As you can see in the code above, I'd like to use a grep and only apply the formatting on columns carrying names matching a certain pattern - col 1, 2 and 4 - in this example. 

When opening the xlsx file, the formatting is applied on all columns 1-4.

Is it possible to create a conditional formatting on selected rows only?

**Comment by JanMarvin** [comment]
Hi @jayieh (and greetings to Münster), the issue is that the conditional format is applied to the entire range of cells. We simply pick min and max column.

https://github.com/ycphs/openxlsx/blob/110fb4fec0a461a2367dabf8f2c5f203b99f977d/R/conditional_formatting.R#L697-L698

This results to the observed behavior

```R
> wb$worksheets[[1]]$conditionalFormatting
A2:D11
[[zip]]
```

You can circumvent this using the following

```R
library(openxlsx)

DF2wb <- as.data.frame(matrix(rexp(200), 10, 4)) #create data frame with random values

colnames(DF2wb) <- c("cf1","cf2","no","cf3") #name columns of DF

wb <- buildWorkbook(DF2wb) #create workbook from DF

# create conditional formating, based of grep of colnames
columns <- grep("cf", colnames(DF2wb))
# identify consecutive columns
columns <- split(columns, cumsum(c(1, diff(columns) != 1)))

# create conditional formatting based on the consecutive columns
for (column in columns) {
  conditionalFormatting(wb, 1, column, 1:nrow(DF2wb)+1, type = "colourScale", style = c("blue", "white", "red"))
}

#write workbook to file
saveWorkbook(wb, file = "conditional_formating_test.xlsx", overwrite = T)
```

I'm not sure that such behavior is a common enough request that it justifies a pull request.

**Comment by jayieh** [comment]
Hi @JanMarvin ,

thanks for your reply. 

Your suggested code only partially adresses the issue: I'd like to have the same CF applying to all columns (1, 2 and 4 in the example).

This fix does the job for me now, by modifiying the conditionalFormatting after it was created by the function:

```R
cf <- wb$worksheets[[1]]$conditionalFormatting #get conditional formating as object

names(cf) <- paste0(LETTERS[as.integer(grep("cf", rownames(DF2wb)))],":",LETTERS[as.integer(grep("cf", rownames(DF2wb)))], collapse = " ") #manually introduce columns of interest as name for cf

wb$worksheets[[1]]$conditionalFormatting <- cf #overwrite original formating
```

This is a quite common use case for me. So I'd be happy to see a "discontinuous" conditional formating implemeted :)
