### ISSUE TITLE
check.names behavior

### ISSUE THREAD

**Issue by r2evans** [ycphs/openxlsx#33]
ycphs, thank you for taking over maintenance of this package!

There is a bug-report/feature-request on the previous repo that I think merits revisiting: https://github.com/awalker89/openxlsx/issues/102, namely:

> When loading a table from an Excel worksheet using read.xlsx, spaces in column names are still converted to dots (.), even when check.names = FALSE is specified. The reason is most likely due to the fact that column names are modified using the function clean_names at loading. For example, I saw the following line in readWorkbook.R:
> 
> m <- .Call("openxlsx_readWorkbook", v, r, string_refs, isDate, nRows, colNames, skipEmptyRows, origin, clean_names, PACKAGE = "openxlsx")

I am not the OP.

---

My suggestion was to provide a slow transitional change of the default behavior:

> 1. In package `.onLoad` (or `.onAttach`?), mention the default change. This message should stay throughout transition period.
> 
> 2a. In `readWorkbook`, if `check.names` not specified and "bad column name" found, convert as before but provide a warning. (If `check.names` is being specified, then no warning, just do as it asks.)
> 
> 2b. On a subsequent transitional version, if `check.names` is again not specified, then provide a warning but do not convert the column name.

Alex stated a concern that *"changing this could upset a lot of people"*, though I do not completely agree. I replied:

> If you change the default behavior from `FALSE` to `TRUE`, then you shouldn't be impacting current users: if they don't specify `check.names` and are not trying to keep spacey-names, then they won't notice a difference. If they do specify it and haven't raised an issue yet, then it perhaps doesn't impact them (at all or enough to be the squeaky wheel).

---

I think more of the comments there are also noteworthy:

- @pooranis said

    > Can this behavior be modified slightly? I think perhaps having a separate option, e.g. clean.names, which defaults to the current behavior of replacing spaces would be helpful for users who are used to this. And then check.names could behave as usual, and setting both to FALSE will turn off any column renaming

    (While I do not agree with `clean.names`, it's another opinion.)

- @WilDoane said

    > this behavior changes the user's data, irreversibly ...
    >
    > Opening a workbook and saving it out again should be (IMHO) an identity operation: same data out as in, barring other user caused changes.

**Comment by kummerer94** [comment]
It would be great if this could be picked up again. In the original issue, a lot of people commented, signalling quite some interest. While I would like to help, I sadly have no knowledge of C++. For the time being: upvote this if you have the same problem and would like this to be improved. This could help with prioritization.
