### ISSUE TITLE
writeData with a date messes up existing cell styles (numFmt)

### ISSUE THREAD

**Issue by kainhofer** [ycphs/openxlsx#330]
**Describe the bug**
I have an excel file with several cells with custom number format ("+0;-0;0").

Loading and saving that workbook with openxlsx works fine. However, as soon as writeData with a date object is used to insert a date anywhere in the file, the cells with the custom number format are turned into date cells. (See the screenshots below).

Digging deeper into the XML, the reason is that date cells are inserted as numeric cells with a custom number format. Unfortunately, that new custom number format for date cells uses the same numFmtId as my custom number format (styles.xml inside the .xlsx file):
![image](https://user-images.githubusercontent.com/4689419/155242406-9cd8890d-d8ab-4d35-8317-dc50fbac730f.png)

**To Reproduce**
R code to reproduce (with the attached sample file):
```{R}
library(openxlsx)
fmt = openxlsx::loadWorkbook("openxlsx_numberformat_date.xlsx")

# unmodified file can be saved and the format is preserved:
openxlsx::saveWorkbook(fmt, "openxlsx_numberformat_date_out.working.xlsx", overwrite = TRUE) 
openXL("openxlsx_numberformat_date_out.working.xlsx")

# Inserting a date object ANYWHERE in the file messes up the format:
openxlsx::writeData(fmt, 1, x = as.Date("2021-01-01"), xy = c(1,1))
openxlsx::saveWorkbook(fmt, "openxlsx_numberformat_date_out.broken.xlsx", overwrite = TRUE)
openXL("openxlsx_numberformat_date_out.broken.xlsx")
```

**Expected behavior**
The existing cell number format should be preserved.

**Screenshots**
Original file (in LibreOffice): 
![image](https://user-images.githubusercontent.com/4689419/155241935-5e696d10-d585-478d-9c37-89c396a76300.png)

After openxlsx inserts a date in some other cell:
![image](https://user-images.githubusercontent.com/4689419/155242033-403efd14-005d-4fa0-8f52-1f9c20172fb6.png)

**Example files**
[openxlsx_numberformat_date.xlsx](https://github.com/ycphs/openxlsx/files/8121035/openxlsx_numberformat_date.xlsx)

**Additional context**
As mentioned above, inserting a date object with writeData will add a custom number format to the cells. 
However, the function classStyles (file helperFunctions.R) creates that style by a call to createStyle(numFmt = "date").
Unfortunately, the createStyle function (file wrappers.R) hard-codes the numFmtId to 165:
```{R}
  if (numFmt != "general") {
    if (numFmt %in% validNumFmt) {
      style$numFmt <- numFmtMapping[[numFmt[[1]]]]
    } else {
      style$numFmt <- list("numFmtId" = 165, formatCode = numFmt) ## Custom numFmt
    }
  }
```
This hard-coded ID causes duplicate IDs for both the existing number format and the new date format. 

The proper solution would be to detect the highest used numFmtId in the workbook and make sure that the ID used is higher than any of the used IDs.

**Comment by JanMarvin** [comment]
Hi @kainhofer , thanks for the report and the digging. I've previously stumbled over this hard coded 165 myself. I circumvented this in my local code and can post my patch later. However, it's not something that fixes the core issue (was to lazy to do so).
Edit: a gosh, you've already have added a pull request. That's even better!
