### ISSUE TITLE
createWorkbook "Created" date is offset by timezone difference

### ISSUE THREAD

**Issue by michael-m52** [ycphs/openxlsx#332]
**Describe the bug**
The "Created" date and time that appears in the Info section is out by the timezone offset. It is 5pm here now, when I ran the code, screenshot is showing "4am tomorrow"

It appears that createWorkbook creates coreProperties > dcterms:created with local time, but Excel is expecting UTC

**To Reproduce**
```
library("openxlsx")
wb=createWorkbook()
print(wb$core)
saveWorkbook(wb,"test.xlsx",overwrite = T)
```

Output of wb$core

`<coreProperties xmlns=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><dc:creator>michael-m52</dc:creator><cp:lastModifiedBy>michael-m52</cp:lastModifiedBy><dcterms:created xsi:type=\"dcterms:W3CDTF\">2022-02-28T17:00:36Z</dcterms:created></coreProperties>
`

**Expected behavior**
Screenshot below should show 5pm

**Screenshots**
![image](https://user-images.githubusercontent.com/53463423/155933422-8002073c-74e3-4b6b-9265-2b163fc40e08.png)

**Example files**
[test.xlsx](https://github.com/ycphs/openxlsx/files/8150977/test.xlsx)

**Comment by JanMarvin** [comment]
This should be fixed in development as well. Please let me know if it works as intended :)

**Comment by michael-m52** [comment]
This works perfectly in the development branch

**Comment by JanMarvin** [comment]
Thanks for testing and glad that we've fixed it
