### ISSUE TITLE
Protect specific cells/columns from editing

### ISSUE THREAD

**Issue by Alik-V** [ycphs/openxlsx#343]
Hi, thanks for this great package!
I was looking in the documentation of `protectWorksheet` and couldn't find a way to lock only specific columns leaving the rest free to edit. For example, I have column_1 and column_2 with very rigid structure and I don't want user to be able to edit that, however the rest of the sheet should be user editable.
Essentially the kind of functionality [pictured here](https://www.co.lucas.oh.us/DocumentCenter/View/44910/How-to-protect-only-certain-Cells-In-Excel-?bidId=#:~:text=Press%20the%20Keyboard%20Shortcut%20Ctrl,that%20you%20want%20to%20protect.) 

Is it possible to do in the current version of the package? Thanks!

**Comment by JanMarvin** [comment]
Hi @Alik-V , the feature you are looking for is a special style with cell protection:

```XML
<xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyProtection=\"1\"><protection hidden=\"1\"/></xf>
```

The man page suggests that `createStyle(locked=TRUE)` might work with a protected worksheet. Haven't tested it
