### ISSUE TITLE
How to shift column direction right-to-left when using openxlsx functions in R?

### ISSUE THREAD

**Issue by user5426** [ycphs/openxlsx#345]
Hello, author,

with thanks, Here is the question:

https://stackoverflow.com/questions/71877156/how-to-shift-column-direction-when-using-openxlsx-functions-in-r

**Comment by JanMarvin** [comment]
Hi @user5426 ,

we do not yet provide an option to do so. You can request this setting per worksheet like this:

```R
library(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, "Cars")
writeData(wb, "Cars", cars)
# the default + rightToLeft=\"1\" 
wb$worksheets[[1]]$sheetViews <- '"<sheetViews><sheetView workbookViewId=\"0\" zoomScale=\"100\" showGridLines=\"1\" tabSelected=\"1\" rightToLeft=\"1\" /></sheetViews>"'
saveWorkbook(wb, "rightToLeft.xlsx", overwrite = TRUE)
openXL("rightToLeft.xlsx")
```

But please don't open issues like this. You could have easily added the entire stackoverflow question here.
