### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by klar-C** [ycphs/openxlsx#346]
Hi,

Are there any plans to include charts at one point?

Christian

**Comment by JanMarvin** [comment]
Hello @klar-C , thanks for the question. The short answer is no. The long answer is a definite maybe, but not in the foreseeable future. Unless someone comes forward and submits a (well tested) pull request, afaik there is no work being done on this at the moment. I have this on my "someday I'll get around to it" list, but that list is long and right now there are other things taking up my time. In theory we just need some xml files, but someone needs to research how to create them, implement the functions, and think of many other things along the way. For example, there are a variety of charts, there are different options, etc. etc.
