### ISSUE TITLE
Issues since Office update (Excel 16.6)

### ISSUE THREAD

**Issue by marinalaforgia** [ycphs/openxlsx#348]
I've been using openxlsx to perform weekly data merges involving reading an excel file in R, merging with new data, and then writing the new file. My code was working perfectly up until yesterday when I updated my Office suite. Now when attempting to read in the same data file that I was reading previous to the update, I get "Warning: No data found on worksheet." I also get errors writing the data file regardless of whether any changes have been made. write.xlsx produces an excel file, however when attempting to open the file I get the following error: "We found a problem with some content in 'workbook.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes." Could this be a compatibility issue with the current version of Excel and the openxlsx package?

**Comment by JanMarvin** [comment]
Hi @marinalaforgia , well ... hard to say without seeing your code or the file you write. Any simple example to reproduce the issue, code and maybe the xlsx file created as output are required.
I use MS365 Excel for testing as well as Excel 16 at work and no specific issue is known to me (reading and writing lots of sheets and data). Maybe your weekly data contains some stuff that wasn't there previously or you switched folders (there was an issue where someone had an `&` in their path), or updated to R 4.2 or whatever. Countless possibilities.

**Comment by JanMarvin** [comment]
Closed due to no answer. Please let us know if there is anything new to the issue.
