### ISSUE TITLE
saveWorkbook() changing format of empty cells below data

### ISSUE THREAD

**Issue by victorrssx** [ycphs/openxlsx#355]
**Bug (?)**
Hi! I have a workbook that contains some data and I would like to format the empty cells below it with a specific format. When I make it manually and then run a script that uses openxlsx functions (like writeData and addStyle) the pre-existing format disappears returning to Excel default. Some tests  bring me to the fact that uses loadWorkbook and then saveWorkbook in sequence produces this result, ie, the problem arises by simply open and close the workbook. Is this a bug or a expected result? Thanks in advance!

The code I use to write data:

    wb <- loadWorkbook(file = "./Teste1.xlsx")
    options(openxlsx.dateFormat = "mmm/yy")
    
      for (i in abas) {
        col_ini = 2
        row_ini = 10
        
        if (is.data.frame(get(i)) == F) {
          for (j in 1:length(get(i))) {
          writeData(wb, sheet = i, x = max(get(i)[[1]]$date), xy = c(5, 4))
          addStyle(wb, sheet = i, style = createStyle(numFmt = "DATE", halign = "center", fontSize = 12, textDecoration = "bold"), rows = 10:(10 + nrow(get(i)[[j]])), cols = col_ini)
          writeData(wb, sheet = i, x = cbind(get(i)[[j]]["date"], select(as.data.frame(get(i)[[j]]), (contains("PIB") | contains("Real")))), xy = c(col_ini, row_ini), keepNA = T, colNames = F)
          col_ini = col_ini + ncol(select(as.data.frame(get(i)[[j]]), (contains("PIB") | contains("Real")))) + 2
          }
        } else {
          writeData(wb, sheet = i, x = max(get(i)$date), xy = c(5, 4))
          addStyle(wb, sheet = i, style = createStyle(numFmt = "DATE", halign = "center", fontSize = 12, textDecoration = "bold"), rows = 10:(10 + nrow(get(i))), cols = 2)
          writeData(wb, sheet = i, x = cbind(get(i)["date"], select(as.data.frame(get(i)), (contains("PIB") | contains("Real")))), xy = c(2, 10), keepNA = T, colNames = F)
        }
        print(i)
      }
      saveWorkbook(wb, file = "./Teste1.xlsx", overwrite = TRUE)

**Comment by JanMarvin** [comment]
Hi @victorrssx , there is to much going on in the code snippet above. Generally speaking `openxlsx` has some known issues with styles. Iirc certain empty rows are entirely simply skipped by `loadWorkbook()` therefore they can never be written again afterwards. You could have a look if `openxlsx2` does a better job with these, though I'm not really sure how/if we handle writing empty cells.
