### ISSUE TITLE
A method to return the 'used extent' on a worksheet

### ISSUE THREAD

**Issue by sch56** [ycphs/openxlsx#356]
I need to know what the 'last written row' in a worksheet that I have read in, so that I can add data after that.

Just reading the data and counting the rows doesn't work as this depends on many other factors.

I have found that the following works, but could be made more apparent: `max(wb$worksheets[[sn]]$sheet_data$rows)`. (This also requires additional checking for an empty sheet as max returns -Inf.)

A method to return this would be very useful when writing report sections down a page, or appending rows to a table already present.

The following code shows the trickiness when reading the attached workbook.
```
library(openxlsx)
wb <- loadWorkbook('XLRowExample.xlsx')
sn <- 1
data1 <- readWorkbook(wb, sheet = sn, startRow = 1)
nrow(data1)
#[1] 9
data2 <- readWorkbook(wb, sheet = sn, startRow = 1, skipEmptyRows = FALSE, colNames = FALSE )
nrow(data2)
#[1] 12
data3 <- readWorkbook(wb, sheet = sn, startRow = 3, colNames = TRUE)
nrow(data3)
#[1]  8
max(max(wb$worksheets[[sn]]$sheet_data$rows))
#[1] 13
#Also
max(max(wb$worksheets[[sn]]$sheet_data$cols))
#[1] 4
```
If I write anywhere before `startRow = 14` then I overwrite existing data.
[XLRowExample.xlsx](https://github.com/ycphs/openxlsx/files/8886760/XLRowExample.xlsx)

**Comment by vorpalvorpal** [comment]
I came here to see if there was a way to do this for a very similar problem. An openxlsx function to do this would be great. @ycphs is this something you would consider?

First draft of a function:
```
sheetExtent <- function(wb, sheet){
  checkmate::assert_class(wb, "Workbook")
  if (is.numeric(sheet)) {
    sheetX <- wb$validateSheet(sheet)
  } else {
    sheetX <- wb$validateSheet(openxlsx:::replaceXMLEntities(sheet))
  }
  n_rows <- suppressWarnings(max(wb$worksheets[[sheetX]]$sheet_data$rows))
  if(n_rows == -Inf) n_rows <- 0
  n_cols <- suppressWarnings(max(wb$worksheets[[sheetX]]$sheet_data$cols))
  if(n_cols == -Inf) n_cols <- 0
  return(c(n_rows, n_cols))
}
```
