### ISSUE TITLE
How to prevent "NA" strings when saving workbooks

### ISSUE THREAD

**Issue by deschen1** [ycphs/openxlsx#359]
Disclaimer: I yet have to figure out how to make a reproducible example (because as of now I can't, well, reproduce with a small toy example the issue in one of my files).

But here's the problem:

- I create a workbook in R with `createWorkbook` => `addWorksheet` => `writeData` => `saveWorkbook`.
- The data passed via writeData has missings. Saving the workbook just doesn't print them, i.e. leaves the missings as empty cells (good).
- I re-import the Excel file with `loadWorkbook`.
- Saving the file again with `saveWorkbook` now has replaced the blanks with NA.

Not sure if that is intended or a feature or if there's a setting how I can prevent it.

What is weird is that the only place where I can do something about missings is in writeData. But the problem occurs already when simply loading and saving a workbook (without doing any changes).

**Comment by JanMarvin** [comment]
Hi @deschen1 , it's a known behavior. If an empty field is found, `openxlsx` adds `NA_character_`. I reference the line that causes this behavior in another maybe closed issue. I haven't changed it, because it is around for so long, that I considered it expected behavior.

**Comment by deschen1** [comment]
Interesting. And thanks for the quick reply.

Any chance you'd at least add an optional argument? Because in its current form, it's quite inconsistent, no? I.e. saving first round doesn't add NA strings, but second round (after loadWorkbook) adds NA strings.

**Comment by JanMarvin** [comment]
Hi @deschen1 , I do not plan to add this. Though, I would support a pull request which will optionally change the behavior. The lines that cause the issue are the following, though the fix might be incomplete: https://github.com/JanMarvin/openxlsx/commit/c47948fdbfe04753180a2c044dbb7a32bc5eb86b.

**Comment by deschen1** [comment]
OK, I did a pull request and simply added an optional argument to loadWorkbook. https://github.com/deschen1/openxlsx/commit/beae41b14eaf3cdef6f76fbb5dd88730d73d738b The Fix seems to work at first glance.

**Comment by gelisol** [comment]
Hi @JanMarvin. If you were to be compensated monetarily (by me) for your time and effort to add deschen1's request in your next versioning of openxlsx, would you be willing to add it? It would be much appreciated by many users of your openxlsx package to have an additional parameter like the one deschen1 specified in his pull request. Thanks!

**Comment by JanMarvin** [comment]
Hi @gelisol , thanks for the kind offer, but if I remember correctly, the PR is already merged in development. Once the next release is drafted, it should be on CRAN. In the meantime, I'm actively developing `openxlsx2` which does not have this issue

**Comment by deschen1** [comment]
@JanMarvin do you have any insight in when the next version might be released? Like is it a matter of days? Weeks? Or "maybe sometime."?

**Comment by JanMarvin** [comment]
No, sorry, I don't. It's whenever @ycphs decides it's time. I'm just contributing to this project and maybe keeping it alive lately (and I may have caused a few issues along the way myself when I fixed things inadequately), and I like to keep ownership/maintenance separate :)

There are a few open PR that should be merged #341, #375, and #376. I'm not even sure we'll pass CRAN without something like #376, but my time is limited. Someone should clean up and merge the open pull requests and then get everything ready for a new release. That someone, unfortunately, is probably myself.

**Comment by deschen1** [comment]
I wouldn't say it's "unfortunate" that you probably have to get it ready. You seem to be the active maintainer here, that's already something I'd say. But I agree that at some point the "external" people are probably only of limited help, i.e. we can probably contribute on some code, but everything beyond is more something for the core team. Having said that. Leaving 341 and 375 aside, do I see that right that 376 is mainly for getting some consistent code formatting? I don't know if it needs to follow some formal route, but I can maybe double check the changes mentioned in 376 if it helps speeding up the release process a bit.

**Comment by JanMarvin** [comment]
In a way yes. I have to clean it a bit, I started it on top of 375 afaik, but it should be independent of that.
When I said it's unfortunate, I was simply referring to the fact that it will consume time and it's a tedious task as well. We'll get it done. Checking a few things here and there is always welcome

**Comment by gelisol** [comment]
Thanks, JanMarvin, for clarifying that the change will eventually be available! : ) I'm also looking forward to your release of openxlsx2. Thanks!

**Comment by TobiSonne** [comment]
> Hi [@deschen1](https://github.com/deschen1) , I do not plan to add this. Though, I would support a pull request which will optionally change the behavior. The lines that cause the issue are the following, though the fix might be incomplete: [JanMarvin@c47948f](https://github.com/JanMarvin/openxlsx/commit/c47948fdbfe04753180a2c044dbb7a32bc5eb86b).

Thank you so much!!!

**Comment by JanMarvin** [comment]
Hi @TobiSonne , just though you know, there is `openxlsx2` which is the successor of this package. Many of quirks from `openxlsx` have been ironed out. Its stable, actively developed and used. Apart from legacy code there should be no reason to stick with `openxlsx`.

[Edit] The writing reflects my state of mind ... I intended to write: "just so you know"
