### ISSUE TITLE
loadWorkbook & saveWorkbook erases any format and contents

### ISSUE THREAD

**Issue by sigbertklinke** [ycphs/openxlsx#361]
Hi,

I'am running under Ubuntu 20.04.4 LTS, R version 4.2.0 and install of openxlsx from github a small program with a loop

```
for (i in 1:n) {
  wb <- loadWorkbook(file[i])
  cloneWorksheet(wb, sheet[i], clonedSheet="Vorlage")
  writeData(wb, sheet = sheet[i], x = who, startCol = 2, startRow = 1, colNames = FALSE)
  saveWorkbook(wb, file[i])
}
```

The files contain all the cloned sheets, but any formating or content in a sheet is erased.

Best Sigbert

**Comment by JanMarvin** [comment]
Hi @sigbertklinke , afaik that is not supposed to happen. What kind of formatting do you have? Background colors, number formats, font colors etc or text cells with highlighting? Only the latter should not be available after cloning and replacing, the rest should remain (maybe not 100%).

**Comment by sigbertklinke** [comment]
Hi, most of it: Background colors, number formats, formulas and text cells with highlighting, I can try tomorrow to simplify my Excel template and report back. Thanks Sigbert

**Comment by victorrssx** [comment]
@sigbertklinke @JanMarvin any news? I have a similar problem with these functions (already open an issue)

**Comment by JanMarvin** [comment]
Hi @victorrssx , I've commented on #355 but please do not high jack other issues.

**Comment by sigbertklinke** [comment]
Hi, I deleted all formatting in my sheet "Vorlage" and set the font to Calibri 11 (standard Excel font as far as I know). Still the same result. I want to try it once more with Excel under Windows, since I'am using  LibreOffice with Ubuntu.

What actually works is: load the workbook, write the data and save the workbook. Of course, instead of having one workbook with n sheets, I have now n workbooks :(

**Comment by JanMarvin** [comment]
Well you write `file[I]` guess that's expected. Otherwise the load workbook should be outside of the loop and the save workbook after the loop. Please add a minimal example if possible. A formatted file and the code you want to run.

**Comment by JanMarvin** [comment]
Follow up, @sigbertklinke mailed me his minimal working example and I could check that the file looks alright when working with `openxlsx2` therefore I consider the issue solved on my end. Please refrain from mailing me other files, this was a one time exception :)

Btw. @sigbertklinke , after I replied to you I realised that cell "B2" would be a better place for the name.
