### ISSUE TITLE
retrieve wb data

### ISSUE THREAD

**Issue by joedaffy** [ycphs/openxlsx#369]
As far as I'm aware, there's no easy way to see what's in my wb object without writing and saving to an Excel document. For debugging and checking purposes, it would be helpful to have a function where I can input the wb object, the sheet and the cell range, which returns a dataframe of what currently sits in the wb object in the specified range.

**Comment by JanMarvin** [comment]
Hi @joedaffy , that would be `read.xlsx(wb)` or `readWorkbook(wb)` which is the same.

**Comment by joedaffy** [comment]
Thanks @JanMarvin!
