### ISSUE TITLE
Opening a wb object that was loaded from xlsx causes content problems

### ISSUE THREAD

**Issue by jzadra** [ycphs/openxlsx#370]
**Describe the bug**
If you create a wb from scratch and open it in excel, it works fine.  If you instead load a wb from an existin xlsx file and then try to open in in excel, it causes an excel alert regarding problematic conent.

**To Reproduce**
``` r
library(tidyverse)
library(openxlsx)

wb <- loadWorkbook(file = system.file("extdata", "loadExample.xlsx", package = "openxlsx"))

openXL(wb)
```
![image](https://user-images.githubusercontent.com/25590353/179849223-e6b014bc-cc15-495a-b82d-86bd52e365fa.png)
 
Clicking "yes" yields:

![image](https://user-images.githubusercontent.com/25590353/179849349-3dbc5d6d-d4d4-4f0a-b5d6-ded85cd44fea.png)

**Expected behavior**
The workbook should open, and should be identical to the original workbook.

─ Session info ────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22)
 os       macOS Monterey 12.4
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Denver
 date     2022-07-19
 rstudio  2022.02.3+492 Prairie Trillium (desktop)
 pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────
 ! package     * version date (UTC) lib source
   assertthat    0.2.1   2019-03-21 [2] CRAN (R 4.2.0)
   backports     1.4.1   2021-12-13 [2] CRAN (R 4.2.0)
   broom         0.8.0   2022-04-13 [2] CRAN (R 4.2.0)
   callr         3.7.0   2021-04-20 [2] CRAN (R 4.2.0)
   cellranger    1.1.0   2016-07-27 [2] CRAN (R 4.2.0)
   cli           3.3.0   2022-04-25 [2] CRAN (R 4.2.0)
   clipr         0.8.0   2022-02-22 [2] CRAN (R 4.2.0)
   colorspace    2.0-3   2022-02-21 [2] CRAN (R 4.2.0)
 P crayon        1.5.1   2022-03-26 [?] CRAN (R 4.2.0)
   DBI           1.1.3   2022-06-18 [2] CRAN (R 4.2.0)
   dbplyr        2.1.1   2021-04-06 [2] CRAN (R 4.2.0)
   digest        0.6.29  2021-12-01 [2] CRAN (R 4.2.0)
   dplyr       * 1.0.9   2022-04-28 [2] CRAN (R 4.2.0)
   ellipsis      0.3.2   2021-04-29 [2] CRAN (R 4.2.0)
   evaluate      0.15    2022-02-18 [2] CRAN (R 4.2.0)
   fansi         1.0.3   2022-03-24 [2] CRAN (R 4.2.0)
   fastmap       1.1.0   2021-01-25 [2] CRAN (R 4.2.0)
   forcats     * 0.5.1   2021-01-27 [2] CRAN (R 4.2.0)
   fs            1.5.2   2021-12-08 [2] CRAN (R 4.2.0)
   generics      0.1.2   2022-01-31 [2] CRAN (R 4.2.0)
   ggplot2     * 3.3.6   2022-05-03 [2] CRAN (R 4.2.0)
   glue          1.6.2   2022-02-24 [2] CRAN (R 4.2.0)
   gtable        0.3.0   2019-03-25 [2] CRAN (R 4.2.0)
   haven         2.5.0   2022-04-15 [2] CRAN (R 4.2.0)
   highr         0.9     2021-04-16 [2] CRAN (R 4.2.0)
   hms           1.1.1   2021-09-26 [2] CRAN (R 4.2.0)
   htmltools     0.5.2   2021-08-25 [2] CRAN (R 4.2.0)
   httr          1.4.3   2022-05-04 [2] CRAN (R 4.2.0)
   jsonlite      1.8.0   2022-02-22 [2] CRAN (R 4.2.0)
   knitr         1.39    2022-04-26 [2] CRAN (R 4.2.0)
   lifecycle     1.0.1   2021-09-24 [2] CRAN (R 4.2.0)
   lubridate     1.8.0   2021-10-07 [2] CRAN (R 4.2.0)
   magrittr      2.0.3   2022-03-30 [2] CRAN (R 4.2.0)
   modelr        0.1.8   2020-05-19 [2] CRAN (R 4.2.0)
   munsell       0.5.0   2018-06-12 [2] CRAN (R 4.2.0)
   openxlsx    * 4.2.5   2021-12-14 [2] CRAN (R 4.2.0)
   pillar        1.7.0   2022-02-01 [2] CRAN (R 4.2.0)
   pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.2.0)
   processx      3.6.1   2022-06-17 [2] CRAN (R 4.2.0)
   ps            1.7.1   2022-06-18 [2] CRAN (R 4.2.0)
   purrr       * 0.3.4   2020-04-17 [2] CRAN (R 4.2.0)
   R.cache       0.15.0  2021-04-30 [2] CRAN (R 4.2.0)
   R.methodsS3   1.8.1   2020-08-26 [2] CRAN (R 4.2.0)
   R.oo          1.24.0  2020-08-26 [2] CRAN (R 4.2.0)
   R.utils       2.11.0  2021-09-26 [2] CRAN (R 4.2.0)
   R6            2.5.1   2021-08-19 [2] CRAN (R 4.2.0)
   Rcpp          1.0.8.3 2022-03-17 [2] CRAN (R 4.2.0)
   readr       * 2.1.2   2022-01-30 [2] CRAN (R 4.2.0)
   readxl        1.4.0   2022-03-28 [2] CRAN (R 4.2.0)
   renv          0.15.4  2022-03-03 [1] CRAN (R 4.2.0)
   reprex        2.0.1   2021-08-05 [2] CRAN (R 4.2.0)
   rlang         1.0.3   2022-06-27 [2] CRAN (R 4.2.0)
   rmarkdown     2.14    2022-04-25 [2] CRAN (R 4.2.0)
   rstudioapi    0.13    2020-11-12 [2] CRAN (R 4.2.0)
   rvest         1.0.2   2021-10-16 [2] CRAN (R 4.2.0)
   scales        1.2.0   2022-04-13 [2] CRAN (R 4.2.0)
   sessioninfo   1.2.2   2021-12-06 [2] CRAN (R 4.2.0)
   stringi       1.7.6   2021-11-29 [2] CRAN (R 4.2.0)
   stringr     * 1.4.0   2019-02-10 [2] CRAN (R 4.2.0)
   styler        1.7.0   2022-03-13 [2] CRAN (R 4.2.0)
   tibble      * 3.1.7   2022-05-03 [2] CRAN (R 4.2.0)
   tidyr       * 1.2.0   2022-02-01 [2] CRAN (R 4.2.0)
   tidyselect    1.1.2   2022-02-21 [2] CRAN (R 4.2.0)
   tidyverse   * 1.3.1   2021-04-15 [2] CRAN (R 4.2.0)
   tzdb          0.3.0   2022-03-28 [2] CRAN (R 4.2.0)
   utf8          1.2.2   2021-07-24 [2] CRAN (R 4.2.0)
   vctrs         0.4.1   2022-04-13 [2] CRAN (R 4.2.0)
   withr         2.5.0   2022-03-03 [2] CRAN (R 4.2.0)
   xfun          0.31    2022-05-10 [2] CRAN (R 4.2.0)
   xml2          1.3.3   2021-11-30 [2] CRAN (R 4.2.0)
   yaml          2.3.5   2022-02-21 [2] CRAN (R 4.2.0)
   zip           2.2.0   2021-05-31 [2] CRAN (R 4.2.0)

 [1] /Users/jzadra41/Library/Caches/org.R-project.R/R/renv/library/integral-private-a6fa20d8/R-4.2/x86_64-apple-darwin17.0
 [2] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

 P ── Loaded and on-disk path mismatch.

**Comment by jzadra** [comment]
Oddly enough, I have my own .xlsx file in my package that when I load initially using the same method as the loadWorkbook example for the xlsx file packed into the openxlsx package, it will initially open just fine using `openXL(wb)` just fine.  But if I then save it, and use `loadWorkbook()` again for the saved file, I get the same content issue.  

So it isn't entirely using loadWorkbook that causes the issue it seems.

**Comment by jzadra** [comment]
This has now been replicated by a colleague on a windows machine.

**Comment by JanMarvin** [comment]
Hi @jzadra , most likely some extlst issue. Any slicers in the sheet, they are known to cause issues.

**Comment by JanMarvin** [comment]
workbook objects are not 1:1 copies of the original file. there is a lot of stuff going on behind the scenes and sometimes `openxlsx` creates output that Excel does not understand. What makes it difficult, Excel is bad at telling what causes the issue and worse at fixing mistakes.

**Comment by jzadra** [comment]
I've just verified that it does work with 4.2.4 (the original example with the excel file bundled with the package), ie:

```
library(tidyverse)
library(openxlsx)

wb <- loadWorkbook(file = system.file("extdata", "loadExample.xlsx", package = "openxlsx"))

openXL(wb)
```

**Comment by JanMarvin** [comment]
You could see if reverting this commit solves the issue: https://github.com/ycphs/openxlsx/commit/312ea6c22c5f49da25c5bc4e9e82d085d2dd5f2c IIRC I enabled reading extlst, but openxlsx might try to add another extlst if slicers are available. But it's been 9 months since that commit so that's not really something I'm sure of.

Another attempt might be to erase all duplicated extlst entries. There was another issue regarding the same issue. Maybe it's even solved in development. A lot has happened since that commit.

**Comment by JanMarvin** [comment]
I've opened a pull request in #371 fingers crossed that it solves the issue. Could you please give it a try, with our file and with your own?
PS: tidyverse is completely unrelated to the issue.

**Comment by jzadra** [comment]
I installed #371 and re-ran with the package file and it works.  I already modified my own after it was determined that what was causing the problem on our file was hyperlinks.  Once we deleted them, the problem went away. So I can't do a proper test on my file any more (dont' have time to go back)

**Comment by JanMarvin** [comment]
Well thanks anyways!
