### ISSUE TITLE
writeDataTable() not constructed as error suggests

### ISSUE THREAD

**Issue by millermc38** [ycphs/openxlsx#372]
In version 4.2.5 of openxlsx, if you do writeDataTable() with two variables that have the same name but different capitalization/casing, you get the following error: "colNames must be a unique vector (case sensitive)". Change assert_unique(...,case_sensitive=TRUE), which is currently set to false.

Example: 

```r

test_df<-data.frame(hi=1,Hi=2)

#Libraries
library(openxlsx)

#Overwrite any other workbooks open/initiate a new one.
wb <- createWorkbook()

addWorksheet(wb = wb,
             sheetName = "test")

writeDataTable(wb = wb,
               sheet = 1,
               x = test_df,
               tableStyle = "none",)


```

**Comment by TheSoundOfSnowCrunchingUnderYourFeet** [comment]
I am having the same issue in version 4.2.5.2 of openxlsx. When will this bug be fixed?
