### ISSUE TITLE
setColWidths(..., widths='auto')

### ISSUE THREAD

**Issue by phkraght** [ycphs/openxlsx#38]
## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.
wb<-loadWorkbook('ColWidthBug.xlsx')  # see attached file
setColWidths(wb, 1, 1, widths='auto')
saveWorkbook('ColWidthsBug2.xlsx')  # this spreadsheet has a column width of 250
  2.
  
  3.

## sessionInfo()

  - Version of openxlsx: 4.1.4
  - Version of R: 3.6.2
[ColWidthBug.xlsx](https://github.com/ycphs/openxlsx/files/4105236/ColWidthBug.xlsx)

**Comment by ycphs** [comment]
Please test with the current development version
