### ISSUE TITLE
add sheet without number

### ISSUE THREAD

**Issue by Larbo53** [ycphs/openxlsx#380]
Hello,
I want to create sheets with the following code:
"For i in range(0,len(customers)):
      workbook=Workbook()
     if i==0:
                sheet = workbook.active
                sheet.title = str(customers[i])
            else:
                Num=str(i)
               sheetNum=workbook.create_sheet(title=str(customers)[i])"
but I get an error back.
How can I proceed because in my processing, I don't know the number of customers?
Thanks for your feedback.
Sincerely

**Comment by JanMarvin** [comment]
Sorry, but this does not look like R to me. Are you looking for openpyxl?
