### ISSUE TITLE
Could `mergeCells` have the same behaviour as in Excel, i.e. merging AND centering effect by default?

### ISSUE THREAD

**Issue by olivier7121** [ycphs/openxlsx#388]

**Comment by JanMarvin** [comment]
I assume the answer is yes. All it would need would be a addStyle call with center on the merged cell. Would you like to create a pull request for this?

**Comment by olivier7121** [comment]
Thanks for the quick reply, @JanMarvin.

Yes, that's what I did: I called `mergeCells` and then applied a centering style with `addStyle`.
My proposal (and it was just an enhancement proposal, not an issue, I hope I got this right) was simply to embed this centering feature by default within `mergeCells` - so as to replicate the behaviour in Excel.
Of course not a high priority request.
