### ISSUE TITLE
Can't update XLSX file with pivot table with last CRAN version 4.1.4

### ISSUE THREAD

**Issue by alainaa** [ycphs/openxlsx#39]
## Expected Behavior

Keep pivot table pointing at a 'Data' sheet OK after updating this data.

## Actual Behavior

I load a file ('FileWithPivot' in the following) with 2 sheets: data ('Data'), and a pivot table. I update the data with a new table 'UPData' (same format, column names, with only dates, strings and numbers, consisting in a few thousands of lines + 20 columns)):

wb <- loadWorkbook(FileWithPivot)
removeWorksheet(wb, 'Data')
addWorksheet(wb, 'Data')
writeData(wb, 'Data', UPData, colNames=T) 
openXL(wb) 

The result is an XLSX file, with updated Data, but pivot table broken.

The same code + data works fine with previous version of open xlsx 4.1.0.1 (R version 3.6.1), but the pivot table gets broken with 4.1.2 (CRAN version).

## Steps to Reproduce the Problem 
(please attach an example xlsx file if possible)

  1.
  
  2.
  
  3.

## sessionInfo()

  - Version of openxlsx: 4.1.2
  - Version of R: 3.6.2

**Comment by alainaa** [comment]
Sorry, I wrote 4.1.2 but it is wrong. The correct openxlsx version is 4.1.4! Any help appreciated... Thank you very much in advance.

**Comment by ycphs** [comment]
I think it might work, if you update data directly.

```
wb <- loadWorkbook(FileWithPivot)
writeData(wb, 'Data', UPData, colNames=T)
openXL(wb)

```

If you delete the "Data" sheet and and a new one with the same name, it might haben, that the internal reverence breaks. 

A simple update of the "Data" sheet is maybe a solution. Unfortunately the package has no support for creating or changing pivot tables.

**Comment by alainaa** [comment]
I've tried to update the data directly, but unfortunatly the result is exactly the same... It's a shame, because the thing has been working for almost 2 years! 
I'll have to find a workaround:
- installing a previous version of openxlslx that works perfectly (the 4.1.0.1 I've got on some other machine)
- or writing my data to some database, and then update the pivot table directly from there
I'm quite busy and it will take me a few weeks before I get that done. So I would prefer to stick to openxlsx, a great package, by the way. If you can find out anything new, please let me know.
Best regards.

**Comment by alainaa** [comment]
Hello,

Yesterday I finally could install the 4.1.0.1 version instead of the 4.1.4... And everything works, as always, like a charm. So there must be some kinf of bug in the most recent version(s) of the package. If possible, please confirm if it gets fixed. Thank you very much in advance.

**Comment by ycphs** [comment]
If you provide a example file, I can try to have a deeper look into.
