### ISSUE TITLE
Automatic font colour

### ISSUE THREAD

**Issue by minifiemj** [ycphs/openxlsx#395]
In the createStyle function, could the fontColour option be allowed to be set to automatic? In terms of spreadsheet accessibility, setting the font colour to automatic is supposed to be the best option.

**Comment by matt-dray** [comment]
I'm also interested in this from an accessibility perspective. Note that [{openxlsx2}]() has [an option for automatic font colouring in `wb_colour(auto = "1")`](https://janmarvin.github.io/openxlsx2/reference/wbColour.html), so you can do something [like this](https://gist.github.com/matt-dray/3910663e0c7cbf499d65ee3a73efcb88#file-openxlsx2-auto-font-test-r).
