### ISSUE TITLE
Update NEWS for 4.1.2

### ISSUE THREAD

**Issue by GegznaV** [ycphs/openxlsx#4]
The current version of **openxlsx** on CRAN is 4.1.2.  Unfortunately, the last record in NEWS are for version 4.1.1 (https://cran.rstudio.com/web/packages/openxlsx/NEWS). I expect this file to be updated: at least it should be announced that there is a new maintainer.

**Comment by iagogv3** [comment]
And even for 4.1.0 here: https://cran.r-project.org/web/packages/openxlsx/NEWS
It is strange.

**Comment by ycphs** [comment]
I will correct it with the next CRAN release.
