### ISSUE TITLE
Chart in Excel does not show merged cells even after merging using openxlsx

### ISSUE THREAD

**Issue by wspagnola** [ycphs/openxlsx#408]
Hello,

I'm trying to export data into an excel file and create a file that looks this

![column_chart_merged](https://user-images.githubusercontent.com/17279380/219097753-d5775a67-39df-403b-bff2-537d625f35e7.png)

I use this code to create a report and use the mergeCells function to merge ela and math into one cell 

``
wb <- createWorkbook()
addWorksheet(wb, "Report")
writeData(wb, "Report", school_report, startCol = 1, startRow = 1, rowNames = FALSE)

mergeCells(wb, "Report", cols = 1, rows = 2:(length(grades)+1))
mergeCells(wb, "Report", cols = 1, rows = (length(grades)+2):(nrow(school_report)+1))

saveWorkbook(wb, file = paste0(path, "school_report.xlsx"), TRUE)
``
However, when I create the save file and create a chart the subject in the x-axis appears unmerged even though the cells in the sheet are clearly merged.  If I manually unmerge and re-merge the cells the chart appears the way I want it to.

![column_chart_unmerged](https://user-images.githubusercontent.com/17279380/219098251-c3bfa8c8-6df7-4f9c-a8a4-c18310fdf837.PNG)

I was wondering if there is something I can do in R to fix this or if this is excel issue.

**Comment by JanMarvin** [comment]
Just a guess: it might be because every merged cell still contains data. You could try to erase the duplicated cells and keep only a single cell value. mergeCell simply sets the XML string that tells excel to combine the cells. If you unmerge the cells you see a value in every cell.
