### ISSUE TITLE
colWidths = "auto" should also consider the space taken by the filter button

### ISSUE THREAD

**Issue by retodomax** [ycphs/openxlsx#425]
**Describe the bug**
`colWidths = "auto"` adjusts the columns widths but does not take the into account the space taken by the filter button

**To Reproduce**
```
df <- data.frame(columnTitle1 = 1:4,
                 columnTitle2 = c("a", "b", "c", "d"))
openxlsx::write.xlsx(x = df, file = "test1.xlsx", asTable = TRUE,
                     colWidths = "auto", withFilter = TRUE)
```

Open the excel file shows the problem:

![image](https://user-images.githubusercontent.com/36004669/235936065-278de794-69d9-4df0-9c96-3065f451440c.png)

**Expected behavior**
If argument `withFilter = TRUE` then there should be some extra space for the filter button

**Comment by Napoleongl** [comment]
This would definitely be a welcome addition as today you have to count chars and add some space manually and hope there isn’t an excess of m’s or i’s in some of the names.
