### ISSUE TITLE
Some value are reconize like int or like Char on different sheet

### ISSUE THREAD

**Issue by hedjour** [ycphs/openxlsx#43]
**Describe the bug**
At first thank you and thanks to the team for this very good and useful package.

My issue is this : I have data like "0.25", on a sheet this will recognize like a int by read.xlsx and on a second sheet it will be recognize like a char.

I think the bug come from Excel and the metadata of the cell some cell are left-align (char cell) and the other are right align (int cell).

Is it possible to unconsidered the excel formatting cell ? and base the type of vector on the recognition of data ? like for a CSV ? 

Maybe my demand is much a feature development and not a bug ? sorry if is it.

By the way sorry for my english I'm not nativ  english speaker.

**To Reproduce**
This ecm file reproduce the bug :
[ecm.xlsx](https://github.com/ycphs/openxlsx/files/4231040/ecm.xlsx)

**Expected behavior**
Have in the data frame all values in int type and not some char and some numeric

**Comment by ycphs** [comment]
Hi,

In the following document you can find a general help for [formating sheets.](https://cran.r-project.org/web/packages/openxlsx/vignettes/formatting.pdf)

**Comment by hedjour** [comment]
I don't want writing the xlsx but read them correctly. Maybe I misunderstood your answers.
I try to execute this code on the ecm above :

```
readxlsfiles <- function(files, lastsheet, firstsheet = 1, byrow = TRUE, rowskeep = NULL){
  library("openxlsx")
  library("dplyr")
  readlist <- list()
  for (i in firstsheet:lastsheet) {
    readlist[[i]] <- openxlsx::read.xlsx(files,sheet = i, rows = rowskeep)
  }
  if (byrow) {
    return( dplyr::bind_rows(readlist) )
  } else {
    return( dplyr::bind_cols(readlist) )
  }
}
```

**Comment by ycphs** [comment]
Can you provide example files?
