### ISSUE TITLE
Saving HTML tables (rvest) as Excel files

### ISSUE THREAD

**Issue by Mkranj** [ycphs/openxlsx#450]
I'm downloading a certain HTML table using the rvest package. Currently, I'm transforming it to a regular dataframe and then saving it as .xlsx. However, the table in question has a lot of merged cells. When transforming to a dataframe, all the spaces a merged cell occupies get filled with its text, leading to many duplicates.
Is there a way to directly save a HTML table as an Excel file? Since Excel and openxlsx support merged cells, this would lead to a true-to-original output. I believe this would be a very useful feature :)
From what I've tried, the rvest table is in a xml_node format.

Thanks for the great work!

**Comment by JanMarvin** [comment]
Sorry @Mkranj, but merged html tables and merged celles in ooxml work a little different. This would require a html to ooxml parser. What works though, save the html table as xls or xlsx and open it with excel. The spreadsheet software will complain that the file format doesn’t match the input, but the table will appear.

I was experimenting with html to ooxml to be able to write more output directly from R to `openxlsx2` worksheets. E.g. `gt` writes only html iirc. But this was always just toying around and nothing to show. A complete html parser seems to be a thesis project and also isn’t something I wanted to work on.
