### ISSUE TITLE
Protected excel corrupt

### ISSUE THREAD

**Issue by marciz** [ycphs/openxlsx#47]
**Describe the bug**
Protected excel corrupt when loading and saving

**To Reproduce**
```
library(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, "S1")
protectWorkbook(wb, protect = TRUE, password = "Password", lockStructure = TRUE)
saveWorkbook(wb, "WorkBook_Protection.xlsx",overwrite=TRUE)
# ok
# system2("open", "WorkBook_Protection.xlsx")
wb <- loadWorkbook(file = "WorkBook_Protection.xlsx")
saveWorkbook(wb, file = "WorkBook_Protection_1.xlsx", overwrite = TRUE)
# fail
# system2("open", "WorkBook_Protection_1.xlsx")
```

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Oracle Linux Server 7.7
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> other attached packages:
> [1] openxlsx_4.1.4.9000
> loaded via a namespace (and not attached):
> [1] compiler_3.6.0 tools_3.6.0    Rcpp_1.0.3     stringi_1.4.6  zip_2.0.4

**Comment by ycphs** [comment]
Please try to use the example:

``` 
wb <- createWorkbook()
addWorksheet(wb, "S1")
protectWorkbook(wb, protect = TRUE, password = "Password", lockStructure = TRUE)
## Not run: saveWorkbook(wb, "WorkBook_Protection.xlsx",overwrite=TRUE)
# Remove the protection
protectWorkbook(wb, protect = FALSE)
## Not run: saveWorkbook(wb, "WorkBook_Protection_unprotected.xlsx",overwrite=TRUE)
```
If you have further questions, please also get in contact with @kainhofer. He is the author of this function.

**Comment by marciz** [comment]
Thanks @ycphs. The problem here is that user cannot open saved workbook with protection, i.e., after 
```
wb <- loadWorkbook(file = "WorkBook_Protection.xlsx")
protectWorkbook(wb, protect = FALSE)
saveWorkbook(wb, file = "WorkBook_Protection_1.xlsx", overwrite = TRUE)
```
