### ISSUE TITLE
CRAN requests a new release 

### ISSUE THREAD

**Issue by JanMarvin** [ycphs/openxlsx#476]
Hi @ycphs ,

CRAN sees ERRORs with R-devel and your mail apparently is unresponsive. They don’t want to archive the package due to the many dependencies, which would be archived subsequently.

They’ve requested me to push a new release with a fix and I can do so, but I first wanted to let you know. What I definitely don’t want to do, is take over development. It would be a submission only to avoid getting the package archived.

Please let me know what you think.

Best regards,
Marvin

**Comment by PhS-Orivado** [comment]
Hi @JanMarvin,

Yes they contacted me, but I hadn't the time to read the mails.

If you could push a fix to the release it would be great.

**Comment by ycphs** [comment]
Hi @JanMarvin,

Yes they contacted me, but I hadn't the time to read the mails.

If you could push a fix to the release it would be great.

**Comment by JanMarvin** [comment]
Release is live, but a new test is failing -.-
