### ISSUE TITLE
Warning message in any(rows): “coercing argument of type 'double' to logical”

### ISSUE THREAD

**Issue by gregmuellegger** [ycphs/openxlsx#485]
**Describe the bug**

The row `if (any(rows) < 1L) {` ([in groupRows](https://github.com/ycphs/openxlsx/blob/d86a54ef2f4d2f105f846389eba8a053555f1391/R/wrappers.R#L4614)) triggers a warning:

```
Warning message in any(rows):
“coercing argument of type 'double' to logical”
```

**To Reproduce**
A [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of either an R script to reproduce the issue or otherwise precise steps to reproduce the behavior:

With any workbook and sheet, run:

```r
        groupRows(
            rows = c(1),
            sheet = sheet,
            wb = wb
        )
```

**Expected behavior**

No warning should be triggered.

I assume that changing the line to the following avoids the warning

```r
if (any(rows < 1L)) {
```

As far as I can tell, the check that only values >=1 are valid works in the current state. However the warning is not nice to look at :smile:

**Comment by JanMarvin** [comment]
Hi @gregmuellegger , thanks, could you open a pr including a test that triggers the warning in current code?

**Comment by gregmuellegger** [comment]
Thanks for taking the action on it :tada:
