### ISSUE TITLE
Version 4.2.6 or 4.2.7 breaks reading of *.xlsm files in read.xlsx

### ISSUE THREAD

**Issue by deschen1** [ycphs/openxlsx#497]
I installed openxlsx version 4.2.7 today and since then I can't read in xlsm files with read.xlsx anymore. Switching back to version 4.2.5 works fine. So I guess any of the changes in either 4.2.6 or 4.2.7 does break things.

**Comment by JanMarvin** [comment]
Sorry, cannot reproduce.

``` r
library(openxlsx)
packageVersion("openxlsx")
#> [1] '4.2.7'

tmp <- tempfile(fileext = ".xlsm")

write.xlsx(mtcars, tmp)

read.xlsx(tmp)
#>     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1  21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> 2  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> 3  22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> 4  21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
...

read.xlsx("https://statistik.arbeitsagentur.de/Statistikdaten/Detail/Aktuell/iiia7/kurzarbeit-zr2/kurzarbeit-zr2-dwolkraa-0-xlsm.xlsm?__blob=publicationFile&v=1")
#>                                             Erstellungsdatum
#> 1                                                BM Anzeigen
...
```

**Comment by deschen1** [comment]
I will invest some time later this week trying to create a reprex. I guess it has something to do with the structure of the file itself. Maybe it's missing values/empty cells etc., i.e. any of the things that were touched by one of the Updates.

**Comment by JanMarvin** [comment]
I have pushed a fix for a date issue and would like to make a CRAN patch release this week. If you find the time, please have a look if the issue remains

**Comment by deschen1** [comment]
Can you help me how to install the openxlsx version that has the fix in place (it's been a while since I messed around with dev versions of packages)? The version you referred to in this other data bug, unfortunately throws an error on my machine:

```
remotes::install_github("ycphs/openxlsx#500")

Downloading GitHub repo ycphs/openxlsx@gh_issue_498
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/ycphs/openxlsx/tarball/gh_issue_498'
```

**Comment by JanMarvin** [comment]
Sure, the fix should already be in the r-universe build so either:

```R
# works similar to install.packages()
install.packages("openxlsx", repos = c("https://ycphs.r-universe.dev", "https://cloud.r-project.org"))
```

or

```R
# requires rtools installation
remotes::install_github("ycphs/openxlsx")
```

**Comment by deschen1** [comment]
I can confirm that the issue is gone with the current version (4.2.7.1). So your guess was probably right that the reading function was broken due to some date handling changes and was not based on problems with .xlsm files.

**Comment by JanMarvin** [comment]
Thanks for testing! I close the issue
