### ISSUE TITLE
Create a pkgdown website

### ISSUE THREAD

**Issue by GegznaV** [ycphs/openxlsx#5]
Create a [pkgdown](https://pkgdown.r-lib.org/) website and publish it as GitHub pages. Functions [`usethis::use_pkgdown_travis()`](https://usethis.r-lib.org/reference/use_pkgdown.html), [`pkgdown::deploy_site_github()`](https://pkgdown.r-lib.org/reference/deploy_site_github.html) and [`travis::use_travis_deploy()`](https://ropenscilabs.github.io/travis/reference/use_travis_deploy.html) are really helpful. 
**NOTE:** some steps should be done outside RStudio so read all the instructions before applying them.

**Comment by ycphs** [comment]
I published a very basic pkgdown website.

I looking forward for tips to improve the site. @GegznaV

**Comment by GegznaV** [comment]
Could you add the link of this website instead of:
![image](https://user-images.githubusercontent.com/12725868/68309957-eccb8f00-00b7-11ea-8095-814be65c4e00.png)

**Comment by GegznaV** [comment]
By the way, is the URL https://ycphs.github.io/openxlsx/? It does not work for me, yet.
