### ISSUE TITLE
Excel Array Formulas

### ISSUE THREAD

**Issue by khorovatin** [ycphs/openxlsx#50]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate the creation of a survey workbook that incorporates Excel Tables for data input. I currently manually create array formulas to add an automatically-updated visible entry number to the table. My workbook now has dozens of tables, so the array formula creation is becoming burdensome.

**Describe the solution you'd like**
I would like to be able to use openxlsx to create these array formulas as part of my automation.

**Describe alternatives you've considered**
I cannot think of alternatives other than continuing manual array formula creation.

**Comment by ycphs** [comment]
Thank you for the idea. I agree it would be beneficial to have this features.

Can you try to implement it and create a pull request?
