### ISSUE TITLE
Setting read.xlsx() argument detectDates = TRUE cannot run

### ISSUE THREAD

**Issue by KimberlyHinz** [ycphs/openxlsx#504]
When trying to read in a XLSX file with dates and using `detectDates = TRUE`, the console seems to freeze. It will not complete running, nor can I escape out of the code to stop it. R has to be either closed or forced closed through Task Manager.

I've been using `as_date()` with `origin = "1899-12-30"` as a workaround for the time being, but detectDates is more convenient.

**Comment by JanMarvin** [comment]
Hi, this should be fixed with 4.2.7.1. could you please try this?

**Comment by KimberlyHinz** [comment]
Hi, this worked! Thank you for the quick response!

**Comment by JanMarvin** [comment]
Thanks for reporting and testing. This was caused by some strange windows only bug.
