### ISSUE TITLE
setRowHeights produces a warning when applied after setColWidths (Version 4.2.7.1), if the data.frame contains large numbers

### ISSUE THREAD

**Issue by mkammer19** [ycphs/openxlsx#506]
Using the function setRowHeights after defining column widths width setColWidths produces a warning message in openxlsx Version 4.2.7.1 if the data.frame to be written contains large numbers.

**Example**

```
# data.frame to be written to Excel-file
my_table <- data.frame(ID = seq(13274112109, length.out = 4), NAME = c("A", "B", "C", "D"))
# Create Workbook
wb <- createWorkbook()
addWorksheet(wb, "TABLE", orientation = "portrait")
# Write data.frame to workbook
writeData(wb, "TABLE", my_table, startRow = 1)
# Set column widths
setColWidths(wb, "TABLE", c(1, 2), widths = 20)
# Set row heights
setRowHeights(wb, "TABLE", seq(1, 5),  20)
# Warning message:
# In unlist(wb$sharedStrings[as.integer(val)[typ] + 1]) :
# NAs introduced by coercion to integer range
```

**Expected behavior**
setRowHeights should not return a warning message.

Thank you for this very useful package. I know that this isn't a critical bug, but it is quite annoying.

**Comment by JanMarvin** [comment]
Thanks, fixed. Caused by overflow in `as.integer()`
