### ISSUE TITLE
corrupted file if & in sheet name

### ISSUE THREAD

**Issue by elfunesto** [ycphs/openxlsx#508]
**Describe the bug**
The bug is similar to closed #277 : a file with a sheet including "&" is corrupted

**To Reproduce**
```
library(openxlsx)
file=loadWorkbook("test.xlsx)
saveWorkook(file,"test_new.xlsx)
```

The file test_new.xlsx is corrupted

**Expected behavior**
The file should not be corrupted and be exactly the same as "test.xlsx". If the sheet "Components & input parameter" is removed from test.xlsx, then

```
library(openxlsx)
file=loadWorkbook("test.xlsx)
saveWorkook(file,"test_new.xlsx)
```

works as expected

**Example files**
[test.xlsx](https://github.com/user-attachments/files/17558812/test.xlsx)

**Additional context**
```
> packageVersion("openxlsx")
[1] ‘4.2.7.1’
```

**Comment by JanMarvin** [comment]
Hi @elfunesto , I would accept a pull request, but there’s no development from my side regarding this.

**Comment by elfunesto** [comment]
Hi @JanMarvin , I have just discovered openxlsx2 which is not affected by the bug. Easier (and probably wiser) to migrate to this new package

**Comment by JanMarvin** [comment]
If this works for you, perfect!
