### ISSUE TITLE
Custom Input Messages and Error Alerts for Validations

### ISSUE THREAD

**Issue by khorovatin** [ycphs/openxlsx#51]
**Is your feature request related to a problem? Please describe.**
I'm creating validations that require custom input messages and error alerts, but the current implementation of validations does not appear to support either type of custom message.

**Describe the solution you'd like**
I would like to be able to add a custom input message, titles, and error alert to validations.

**Describe alternatives you've considered**
I've tried using addComment for the Input Message, but that doesn't produce exactly the result I'm looking for. I can see no alternative for a custom Error Alert.

**Comment by ycphs** [comment]
Thank you for the idea. I agree it would be beneficial to have this features.

**Comment by ycphs** [comment]
Can you try to implement it and create a pull request?

**Comment by khorovatin** [comment]
I'm not really a programmer, but will give it a try.
