### ISSUE TITLE
Add "centerContinuous" to the halign style property.

### ISSUE THREAD

**Issue by egenteman** [ycphs/openxlsx#510]
**Is your feature request related to a problem? Please describe.**
Within excel there is a "Center Across Selection" functionality that is similar to "merge cells" but it keeps the independence of those cells.  Right now, openxlsx does not allow "center across selection" but only a function to merge cells.

**Describe the solution you'd like**
It looks like the createStyle function in wrappers.R has validation over the options that halign will take "left", "right", "center" and "justify".  Is adding this feature as simple as adding "centerContinuous" to the validation?  Or are there other code changes needed?

**Comment by JanMarvin** [comment]
Should be enough, but you have to assign this to every cell. 

`openxlsx2`example (I previously wasn't even aware that this might be possible)

``` r
library(openxlsx2)
dim_dat <- wb_dims(x = USPersonalExpenditure, row_names = TRUE, from_row = 2)
dim_hed <- wb_dims(x = USPersonalExpenditure[0,], row_names = TRUE, 
                   above = 1, select = "col_names", from_dims = dim_dat)

wb <- wb_workbook() %>%
  wb_add_worksheet("test") %>%
  wb_add_data(x = USPersonalExpenditure, row_names = TRUE, dims = dim_dat) %>%
  wb_add_data(x = "USPersonalExpenditure", dims = dim_hed) %>%
  # wb_merge_cells(dims = dim_hed) %>%
  wb_add_cell_style(dims = dim_hed, horizontal = "centerContinuous")

if (interactive()) wb$open()
```

<img width="351" alt="Screenshot 2024-11-23 at 15 02 36" src="https://github.com/user-attachments/assets/40797ad2-38e7-4169-8003-b5b32ae85569">

**Comment by egenteman** [comment]
Thanks, this is exactly what I needed!
