### ISSUE TITLE
Creating columns from openxlsx

### ISSUE THREAD

**Issue by iagogv3** [ycphs/openxlsx#52]
It would be great if there was a funtion to add/create new columns in a loaded workbook.

For example
```
myfile <- "..."
library(openxlsx)
tlW <- loadWorkbook(myfile)
addCol(tlW, mtcars$cyl, afterCol = 3, colNames = FALSE)
saveWorkbook(tlW, myfile,overwrite = TRUE)
```

**Comment by ycphs** [comment]
I am not sure how this feature would work in a more complicated sheet.

Could you please be more specific about the purpose of the feature request?

Why isn't it possible to write the data in new sheet and delete the old sheet?

**Comment by iagogv3** [comment]
> Could you please be more specific about the purpose of the feature request?

Maybe a year ago I could be more specific, but now I feel that it's all on the FR. Just, it would be faster and more comfortable to add a column in that way than adding it by hand on excel/Calc software or through getting the sheet as a data frame and manipulating it (I believe this answers your last question; it is possible, but a longer way).

**Comment by JanMarvin** [comment]
Another hint: Even if it's possible, there is a high risk of breaking things elsewhere. Modifying all formulas and recalculating values in every open Excel sheet of a process once things change, is the cause of why Excel is slow after all. Currently we do not track formulas, but for something like this, it would be a requirement.
