### ISSUE TITLE
Use formula as table header

### ISSUE THREAD

**Issue by samuel-rosa** [ycphs/openxlsx#54]
I would like to use formulas in all cells of the first row of a sheet. This is because I need the column header to be linked to another sheet. As the second sheet changes, so do column headers in the first sheet.

Perhaps this feature is already implemented. However, I have not been able to find it in the package.

**Comment by nathanckuhn** [comment]
You can use openxlsx::writeFormula() to add formulas to any cell of a sheet, including the first row. 
See the documentation for how to use it.
I have done what you suggest to create dynamic headers on one sheet that can be changed from a different sheet. 
Does that help?
