### ISSUE TITLE
sort functions alphabetical in r documentation

### ISSUE THREAD

**Issue by Danfro** [ycphs/openxlsx#55]
The R-documentation for [openxlsx](https://www.rdocumentation.org/packages/openxlsx/versions/4.1.4) package does list all functions. But, at least to me, they seem to be at random order.

I believe it would be much more useful to have the functions there in alphabetical order. The package documentation that is provided within R-Studio does list functions in alphabetical order though. :thinking:

**Comment by ycphs** [comment]
Please use the relevant github page: 

[github page](https://ycphs.github.io/openxlsx/)

If you find a way to sort it by default, please provide a PR.
