### ISSUE TITLE
writeFormula only accepts english formula names

### ISSUE THREAD

**Issue by Danfro** [ycphs/openxlsx#56]
R v3.6.1
R-Studio v1.2.1335
openxlsm v4.1.4
Excel 2016

I am using the `writeFormula` function. When writing `"=SUMME(T17:T18)"` to the formula Excel does give me a `#NAME?` error. After entering the cell with F2 and pressing return to confirm the German formula, the formula is accepted and the value is calculated.

When using the English syntax `"=SUM(T17:T18)"` the formula is accepted by excel straight away.

I think a note in the documentation would be helpful. Idealy using a locale formula would be allowed too.

**Comment by ycphs** [comment]
It is already fixed.
[commit containing the  #changes](https://github.com/ycphs/openxlsx/commit/5683b45bd064ac8fa91cf487c675edee38c52715)

**Comment by Danfro** [comment]
Great! Thanks a lot.
So I may as well close this issue.
