### ISSUE TITLE
writeFormula does put r-script at pause until excel file is closed

### ISSUE THREAD

**Issue by Danfro** [ycphs/openxlsx#59]
R v3.6.1
R-Studio v1.2.1335
openxlsm v4.1.4
Excel 2016

I am writing data from an r-script to an existing excel file. Loading the workbook, reading sheets, doing some `writeData` and a `saveWorkbook` at the end works fine. Then in the script I am opening the so edited file using `system(filename)`. 

*expected behaviour:*

The r-script does run through to the end including editing the excel file and opening it up in excel.

*actual behaviour:*

If I add a `writeFormula` function to the r-script, the r-script pauses where the file is opened by the system call. The excel file is opened. Only after closing the excel file, the r-script continues to the end.

**Comment by ycphs** [comment]
The file can only be edited from the R-Script if it is closed.
If that is the problem, then it works as expected?

**Comment by Danfro** [comment]
General write access is not the problem. The data is written to the Excel file. I try to open it after the data is written to the file.

I am running the following script:

```
#basefolder
basefolder <- "C:\\my\\folder\\R-data"
#file for output
file <- paste(basefolder,"/test.xlsx", sep= "")

#Excel output####
#using openxls
library(openxlsx)

wb <- loadWorkbook(file) #load workbook
sheet <- getSheetNames(file)[1] #get first worksheet

writeData(wb,sheet,"something",startCol = 1,startRow = 6,na.string = "???")
writeFormula(wb,sheet,x="=SUM(A1:B2)",1,10)

saveWorkbook(wb,file, overwrite = TRUE) #save data to workbook

#open file in Excel
system(paste("\"C:\\Program Files (x86)\\Microsoft Office\\Office16\\Excel.exe\" ","\"",file,"\"",sep = ""))

#do something after opening the file
file
sheet

```

The script proceeds to the `system` call and stops.

But doing some more testing right now, I could narrow down the behaviour.

Only if there is no Excel file already open, the *hold* does happen. Then it does hold even without using any commands from openxlsx package.

If there is another Excel file/window open, the script proceeds regardless of the usage of any openxlsx commands.

So this seems to be more a `system` related issue. Sorry for bothering you. I will therefore close this issue.

**Comment by Danfro** [comment]
And just for your information too:

When writing a faulty formula to Excel, this might result in a broken document.
For test purposes I did write `=sum()` to my test Excel file. This came up broken after that.

I am aware that it will be almost impossible to test formulas for valid calls. So just so you know about it. An example of a broken Excel file is here:

[test - broken.xlsx](https://github.com/ycphs/openxlsx/files/4581268/test.-.broken.xlsx)

**Comment by ycphs** [comment]
Yes, that's true. 
You are more than welcomed to provide a pull request to solve the issue. Or part of it.
