### ISSUE TITLE
getTables() -> Error looking for worksheet containing & ( &amp; )

### ISSUE THREAD

**Issue by allanbides** [ycphs/openxlsx#61]
Hello, guys,

I am using the function getTables(), to discover the tables on Sheet "T&O", but I receive the message that this sheet does not exist.

        getTables(wb,"T&O")
        Error: Sheet 'T&amp;O' does not exist.

The function in some way looks for the sheet 'T& amp;O' , changing the '&' by ' & amp;'(I needed to put a space here for the conversion to & note happening).

Any suggestions?

Thanks in advance!

Allan

sessionInfo()
Version of openxlsx: 4.1.4
Version of R: 3.4.3

**Comment by ycphs** [comment]
I hope the current development  version solves your issue.
