### ISSUE TITLE
open + write workbook does delete existing print area

### ISSUE THREAD

**Issue by Danfro** [ycphs/openxlsx#66]
The print area of an existing Excel (xlsx) file is deleted when opening and saving with R using openxlsx package.

**Steps to reproduce the behavior:**
1. create a new Excel file
2. define a print area
3. run R script with loadWorkbook, getSheetNames and saveWorkbook commands
4. reopen Excel file => the print area is gone

reproducabel: always

**Expected behavior:**
The file does still contain the print area.

**Verions:**
- OS: Windows 10
- R: 3.6.1
- R-studio: 1.2.1335
- Excel: 2016
- openxlsx: 4.1.4

**Comment by Danfro** [comment]
I did some more tests on this. The print area is actually not deleted.
But I could pinpoint the issue.

Print area definitions (within Excel) do include the sheet name they belong to.
If the sheet name does contain special characters like äöü, those do get converted wrongly.
Spaces do not cause problems.
In my case the sheet name was `2018 übernommen`. This got changed to `2018 Ã¼bernommen`.
And because the print area definition would then not match the sheets name anymore, my print area was invalid and therefore ignore.

**Comment by ycphs** [comment]
Do you have a minimal example to test the behavior?

**Comment by Danfro** [comment]
[test.xlsx](https://github.com/ycphs/openxlsx/files/4586556/test.xlsx)
This Excel file contains screenshots before running R script and after running R script.

Script can be as simple as this without any actions:

```
#basefolder
basefolder <- "C:\\somefolder\\R-Statistik"
#file for output
file <- paste(basefolder,"/test.xlsx", sep= "")

#Excel output####
#using openxls
library(openxlsx)

wb <- loadWorkbook(file) #load workbook
sheet <- getSheetNames(file)[1] #get first worksheet

saveWorkbook(wb,file, overwrite = TRUE) #save data to workbook
```

**Comment by Danfro** [comment]
If you do have a workbook without print areas, you can actually create one by running the following command from R:

`createNamedRegion(wb, sheet, 1:5, 1:5, "_xlnm.Print_Area")`
This will fail if an print area is already defined because the name "print area" is not unique.

If you then check page layout or name manager the area is there - but (sadly) it is ignored when doing a print preview.

This excel file contains a print area created by the above command.

[test.xlsx](https://github.com/ycphs/openxlsx/files/4586625/test.xlsx)

**Comment by ycphs** [comment]
@Danfro thank you for your support.

It would be great if you can add a function to create a print area. Could you create a pull request? If not please let me know, because having support for the print area in the package would be beneficial.

**Comment by JanMarvin** [comment]
Hi @Danfro , just tested it and it works as expected:

```R
library(openxlsx)
wb <- createWorkbook()
addWorksheet(wb, "Cars")

# add the print area as you suggested
createNamedRegion(wb, "Cars", 1:5, 1:5, "_xlnm.Print_Area")
getNamedRegions(wb)

# save the file (looks like your working image)
saveWorkbook(wb, "/tmp/test.xlsx", TRUE)
openXL("/tmp/test.xlsx")

# load the file again (looks the same to me)
wb <- loadWorkbook("/tmp/test.xlsx")
openXL(wb)
```

In your file there is some strange looking encoding. Not sure what caused this, but most likely it causes the broken print area in Excel. Might be some UTF-8 encoding bug from Windows and R?
```XML
<definedName name="_xlnm.Print_Area" localSheetId="0">[1]geÃ¤ndert!$A$1:$D$9</definedName>
```
This should be:
```XML
<definedName name="_xlnm.Print_Area" localSheetId="0">geändert!$A$1:$D$9</definedName>
```

**Comment by Danfro** [comment]
@JanMarvin thanks for looking into this. But that is likely part of the problem.

In my [first comment](https://github.com/ycphs/openxlsx/issues/66#issuecomment-621933186) I described that the sheet name got renamed by the openxlsx command (was `2018 übernommen` changed to `2018 Ã¼bernommen`).

So maybe the encoding does get changed somehow?

I admit, I did not had time to try that recently. I can only do that at work.

**Comment by JanMarvin** [comment]
Oh, hehe, must have been sleeping... entirely missed it. I was under the impression that the print area was the issue, not the Umlaut. Since R 4.2 everything should be Unicode on modern windows, therefore we might have a good chance that all encoding issues will be gone in ~15-20 years when support for the last red hat release supporting R 4.1 will run out ;)
