### ISSUE TITLE
saveWorkbook() always returns TRUE

### ISSUE THREAD

**Issue by rmanfredi** [ycphs/openxlsx#71]
The saveWorkbook() routine always returns TRUE.  Its return status is not documented, and rightfully so since it is constant!

However, on Windows platforms (precisely where openxlsx is likely to be used....), if you happen to have the targeted file opened in Excel, the write operation will fail!!

It would be useful for saveWorkbook() to at least return a boolean "success status" and yield FALSE when saving fails.  Another option would be to add an argument (FALSE by default, to not overcomplicate the logic for those who do not care much) to trigger an exception when writing fails.

**Comment by ycphs** [comment]
Thank you for your input. It would definitely make sense to have a return value. 

I thought of two possible ways:
1. as described by you
2. return a more comprehensive error message to get easier to the root of the problem.

What's your opinion?

**Comment by rmanfredi** [comment]
I would say it all depends on the "API level" of the saveWorkbook() routine in your mind.

If it is, as I view it from here, a rather low-level API call, then the behaviour I described would be what would be called for.  It's annoying for low-level calls which return a success status to decide to emit an error message which might not be suitable: let the caller decide what to do, perhaps there is a contigency plan to retry saving with an alternate name, for instance.

In that case (low-level routine made available to users), all high-level API calls which rely on saveWorkbook() must be taught to handle the error status accordingly.  Factorizing the exception generation at the lowest level was precisely what I was thinking about when I suggested adding this extra parameter...

If it is a user-visible front API, then yes, a detailed user message describing the problem is probably called for because the user would expect the routine to succeed, so it would be an exception if it does not fulfill its contract.  Then internal calls you may be making to saveWorkbook() do not need to change.

It's a design decision.  If it were my code, I would do what I initially suggested, because it's cleaner and more flexible that way.

**Comment by ycphs** [comment]
could you please check out the new pull request: #93 
I would like to welcome you to review mine PR. Please provide also PRs, if you miss some features.
