### ISSUE TITLE
Load and saveWorkbook with existing Data Validation corrupts file

### ISSUE THREAD

**Issue by mghoff** [ycphs/openxlsx#74]
**Describe the bug**
Load any workbook with an existing Data Validation (allowing list, although other types may cause this issue as well), save with overwrite = TRUE & open in Excel - the file is corrupted and the tab originally containing the Data Validation is empty

**To Reproduce**
1. Load an excel workbook that contains cells with any data validation
Example Data: [R_data_validation_test.xlsx](https://github.com/ycphs/openxlsx/files/4610621/R_data_validation_test.xlsx)

2. wb <- loadWorkbook("R_data_validation_test.xlsx")
3. saveWorkbook(wb, "R_data_validation_test.xlsx", overwrite = T)
4. openXL(wb)

**NOTE:** even without using the `openXL()` function, double-clicking on the file after saving returns the same corrupted results.

**Expected behavior**
The file should not have become corrupted, and the Data Validation on the 'summ' tab should have remained.

**Screenshots**
![Excel Corruption Error](https://user-images.githubusercontent.com/15792640/81581827-453c5b80-937d-11ea-9077-a7af25a2f34e.PNG)

**sessionInfo**
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.1.5.1

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    Rcpp_1.0.4.6   stringi_1.4.6  zip_2.0.4

**Additional Information**
See other issue post here: https://github.com/awalker89/openxlsx/issues/510

**Comment by luis-zapata-b** [comment]
i have the same problem!

**Comment by ycphs** [comment]
The file you provided is already corrupt. I can't open it without an error massage.

Without the example file I am not able to find the error.

**Comment by mghoff** [comment]
My apologies - file below should work.
[R_data_validation_test.xlsx](https://github.com/ycphs/openxlsx/files/4649978/R_data_validation_test.xlsx)

Quick Description: In C2 of 'summ' tab, there is a Data Validation list drop-down to selectively sum the information from the 'data' tab in cell C3.

**Comment by jacksonsj** [comment]
We're also having this same issue.

**Comment by EverThingy** [comment]
Seems like data validated cells cause saveWorkbook() to produce a corrupted excel file.
