### ISSUE TITLE
addStyle with number format as "0.00" produces error

### ISSUE THREAD

**Issue by sy20082010** [ycphs/openxlsx#75]
**Describe the bug**
Exception from a specific sequence of cell formatting operations (see below).  

**To Reproduce**

> wb = openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, "sheet1")
df = data.frame(Dataset=c("A","B"), Value=c(100, 200))#  c(67588936, 39183979))
openxlsx::writeData(wb, "sheet1", df,
                    startCol=1, startRow=1,
                    colNames = TRUE,
                    rowNames = FALSE,
                    withFilter=FALSE)
style = openxlsx::createStyle(textDecoration = "bold")
openxlsx::addStyle(wb, "sheet1", style, rows=1, cols=1:2, gridExpand=TRUE, stack=TRUE)
style = openxlsx::createStyle(numFmt="0.00")
openxlsx::addStyle(wb, "sheet1", style, rows=2:3, cols=2, gridExpand=TRUE, stack=TRUE)

The last addStyle command gives this error:

> Error in max(c(sapply(wb$styleObjects, function(i) as.integer(i$style$numFmt$numFmtId)),  : 
  invalid 'type' (list) of argument

For some reason, the error does not happen if the first call to addStyle is excluded.  It also does not happen if we use a numFmt that is not numeric, like "GENERAL" or "PERCENTAGE"

**Additional context**
Using openxlsx version 4.1.5.1 in RStudio

**Comment by ycphs** [comment]
Please check with the current version. (4.2.0)

On my system it works fine.
