### ISSUE TITLE
Add custom filters to worksheet

### ISSUE THREAD

**Issue by zerweck** [ycphs/openxlsx#76]
**Is your feature request related to a problem? Please describe.**
I would like to not only activate filter headers via `withFilters` but also set them to predefined filter settings

**Describe the solution you'd like**
A parametrized way to pass filters and their settings into the writeData function.

**Describe alternatives you've considered**
-
**Additional context**

When diffing a file (I used mtcars) with a filter header but no activated filtering going to the same file with an activated filter (I added mpg > 20), it looks like the following things happen in the `xl/worksheets/sheet1.xml`:
- The tag `<sheetPr filterMode="1" />` is added before the `dimension` tag
- Rows hidden by the filter gain the attribute `hidden="1"`
- The following tag 
```XML  
<autoFilter ref="A1:K1" xr:uid="{3421DF08-ACE9-4865-AEE1-5A0086290328}" /> 
```
gets expanded to:

```XML
 <autoFilter ref="A1:K33" xr:uid="{3421DF08-ACE9-4865-AEE1-5A0086290328}">
        <filterColumn colId="0">
            <customFilters>
                <customFilter operator="greaterThan" val="20" />
            </customFilters>
        </filterColumn>
    </autoFilter>
```

It seems like this is doable with your approach of writing the XML directly to file. However, I must admit I am not knowledgeable enough about the way this package works to write a PR for this feature myself. If someone can point me into the direction of methods that should be used to implement this, I will try my hand at it.

**Comment by ycphs** [comment]
This seems quite complicated, but a recently merged PR #147 might help. At least it should be a reasonable starting point.
