### ISSUE TITLE
WriteData cannot find sheet whose name contains "<" sign

### ISSUE THREAD

**Issue by shengchaohou** [ycphs/openxlsx#78]
**Describe the bug**
writeData function cannot find a sheet whose name contains "<" sign.

**To Reproduce**
> library(openxlsx)
> sheetname = "<24h"
> wb <- createWorkbook()
> addWorksheet(wb, sheetname) 
> writeData(wb, sheetname, "test") 
Error: Sheet '<24h' does not exist.

**Expected behavior**
Write data to the assigend sheet.

**Desktop (please complete the following information):**
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

> packageVersion("openxlsx")
[1] ‘4.1.5’

**Comment by jsavinc** [comment]
I've experienced the same issue but posted at the old repo: (https://github.com/awalker89/openxlsx/issues/508)

Using openxslsx version 4.1.5 and R 4.0.0.

See below example:

```
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, sheet = "a < 1")  # this works
openxlsx::writeData(wb, sheet = "a < 1", jams)  # this returns an error
```


I can add a worksheet containing a special character, but when using writeData(), the sheet name first gets validated using validateSheet() which renames special characters using replaceIllegalCharacters(), but then checks against the existing sheet names (containing said character) and doesn't find the matching sheet. I don't know why the characters get replaced in one method but not the other?

**Comment by ycphs** [comment]
it is solved in the current dev version
