### ISSUE TITLE
For createNamedRegion(), add ability to create from an Excel function.

### ISSUE THREAD

**Issue by nathanckuhn** [ycphs/openxlsx#79]
**Is your feature request related to a problem? Please describe.**
The current createNamedRegion() function works well for specifying a region strictly by row & column. However, in Excel you can create a dynamic named region by creating it with an Excel function instead. Example (and yes this is older, but the basic idea still works): https://www.contextures.com/xlDataVal08.html

**Describe the solution you'd like**
An added argument to createNamedRegion() called "function" that can be filled in INSTEAD of specifying rows & columns.

**Describe alternatives you've considered**
At the moment, I do not know a way to create dynamic named ranges in Excel from R.

**Additional context**
This is an awesome package! Thank you all for all the work!

**Comment by ycphs** [comment]
If you use R variables you can create dynamic named ranges. But as soon as you are creating the named region it will not change anymore.

**Comment by ycphs** [comment]
I am looking forward to receive a pull request with this new feature.
