### ISSUE TITLE
writing to existing excel workbook corrupts excel file 

### ISSUE THREAD

**Issue by dory-maguire** [ycphs/openxlsx#81]
**Describe the bug**
First of all, thanks more making such a great package. I used it last year and it was an amazing help. This is my first bug posting, so please forgive me if I am missing any relevant details. 

I am writing data to an existing excel workbook. In the old version of the workbook, which DID contain some data validations etc, it worked fine. I was able to open the file after running it through openxlsx with no issues. I am now working with a very similar excel workbook this year, nothing major changed in it, but for some reason no matter what I do, even creating another version of the file, I get an error message in excel saying the file is corrupted and unrepairable after running it through openxlsx. Running the old excel file, again no issues at all. The file sizes are about the same between the old and new templates. Again, nothing major got added to this new template that I would have reason to believe is interfering. I have searched through all of the openxlsx help files, and no matter how I change the template cannot find the source of the problems. 

**To Reproduce**
I am working in latest openxlsx development package version 4.1.5.1. 
1. Here are the two workbook template files: 
[Workbook Template new.xlsx](https://github.com/ycphs/openxlsx/files/4879159/Workbook.Template.new.xlsx)
[Workbook Template old.xlsx](https://github.com/ycphs/openxlsx/files/4879163/Workbook.Template.old.xlsx)

test=c("3", "2.5", "1")
wb <- openxlsx::loadWorkbook("Workbook Template new.xlsx") 
#One row of data just to illustrate problem. 
openxlsx::writeData(wb,"Basic inputs", test[1], startRow=2,startCol=3, colNames=F)
openxlsx::saveWorkbook(wb, file=paste("test", "abc",".xlsx",sep=""), overwrite=T)
#I get error messages here saying the file has been corrupted. 

**Expected behavior**
Expected result occurs when I do the following with the old workbook. 
test=c("3", "2.5", "1")
wb <- openxlsx::loadWorkbook("Workbook Template old.xlsx") 
#One row of data just to illustrate problem. 
openxlsx::writeData(wb,"Basic inputs", test[1], startRow=2,startCol=3, colNames=F)
openxlsx::saveWorkbook(wb, file=paste("test", "abc",".xlsx",sep=""), overwrite=T)
#This file opens fine. 

**Screenshots**
Below are the errors I get when trying to open the excel file. 
![image](https://user-images.githubusercontent.com/29965969/86597948-54621300-bf94-11ea-9d76-580e372572ca.png)
![image](https://user-images.githubusercontent.com/29965969/86597974-5cba4e00-bf94-11ea-8e8f-e8726f56c4fe.png)

**Desktop (please complete the following information):**
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Matrix products: default
Browser: Chrome

locale:
[1] LC_COLLATE=English_Canada.1252 
[2] LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
 [1] openxlsx_4.1.5.1 zip_2.0.4        Rcpp_1.0.4.6    
 [4] naniar_0.5.2     fuzzyjoin_0.1.6  plyr_1.8.4      
 [7] stringr_1.3.1    assertr_2.6      rJava_0.9-10    
[10] RODBC_1.3-15     lattice_0.20-38  tidyr_1.1.0     
[13] devtools_2.3.0   fansi_0.4.1      usethis_1.6.1   
[16] dplyr_0.8.5     

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  remotes_2.1.1    
 [3] purrr_0.3.4       colorspace_1.4-1 
 [5] vctrs_0.3.1       testthat_2.3.2   
 [7] yaml_2.2.1        rlang_0.4.6      
 [9] pkgbuild_1.0.8    pillar_1.4.4     
[11] glue_1.4.1        withr_2.2.0      
[13] sessioninfo_1.1.1 lifecycle_0.2.0  
[15] munsell_0.5.0     gtable_0.3.0     
[17] memoise_1.1.0     callr_3.4.3      
[19] ps_1.3.3          curl_4.3         
[21] backports_1.1.8   scales_1.0.0     
[23] desc_1.2.0        pkgload_1.1.0    
[25] fs_1.4.2          ggplot2_3.1.0    
[27] digest_0.6.25     stringi_1.4.6    
[29] visdat_0.5.3      processx_3.4.2   
[31] rprojroot_1.3-2   grid_3.5.1       
[33] cli_2.0.2         tools_3.5.1      
[35] magrittr_1.5      lazyeval_0.2.2   
[37] tibble_3.0.1      crayon_1.3.4     
[39] pkgconfig_2.0.3   ellipsis_0.3.1   
[41] prettyunits_1.1.1 assertthat_0.2.1 
[43] rstudioapi_0.11   R6_2.4.1         
[45] compiler_3.5.1   

**Additional context**
Any suggestions about how I can alter the template to be able to work with openxlsx would be much appreciated. I am at a complete loss, I've tried changing the file, I've updated all R packages, I've ensured RTools40 is working properly with my R, but nothing seems to fix this corruption issue. So this leads me to believe its some sort of bug. Thanks in advance. Happy to provide any further information!

Dorothy

**Comment by ycphs** [comment]
Hi,
I have two questions:
- Have you tested open and saving of the new file without adding new data.
- What is the difference between the two files?

**Comment by dory-maguire** [comment]
Hi there Philipp,

I have a bit more insight now as I've done a few more tests.

1. Yes, I cannot even open it, as it is deemed unrepairable and crashes
excel.
2. When I add ANY additional conditional formatting to the excel workbook
template that DOES work, it too immediately stops working/corrupts. So I
suspect thats the cause somehow. However the odd thing is that there is
already SOME conditional formatting in the workbook that does work. But if
I even add so much as a cell of conditional formatting, it no longer works.
As a workaround, I tried adding some conditional formatting via openxlsx,
and that seems to work fine. But then when I add data validation via
openxlsx, that too corrupts the file.

Hopefully that gives more insight? Any other information needed, I'm happy
to provide it!



 Thanks sincerely,


Dorothy :)

**Comment by dory-maguire** [comment]
Something else interesting came up today, and now I'm wondering if it isn't
something to do with Excel 365. I changed a bit of text in the Excel
workbook template (that was working with openxlsx). I then get the same
corruption issue. It seems any change made directly in excel to the
workbook, corrupts it.

Dorothy

**Comment by ycphs** [comment]
If I am correct it is not the caused by the package.

**Comment by dory-maguire** [comment]
Hi there,

I believe it is some incompatibility between the package and excel. Even if
I load the workbook, write nothing to it, and save it as a new workbook in
openxlsx, it corrupts the file. I believe you should be able to replicate
the error with the files and documentation I sent originally?

Dorothy Y Maguire, PhD [image: LinkedIn]
<https://www.linkedin.com/in/dorothy-maguire-mfc-phd-8669a272>
<https://www.epa.ie/>

Scientific Officer | Office of Environmental Sustainability | Environmental
Protection Agency| Ireland



McCumisky House | Clonskeagh Road |Dublin 14 | D14 YR62

Tel: +353 1 268 0120 | email: d.maguire@epa.ie | twitter: @EPAWasteRes



*Click below to view Ireland’s national waste statistics*

<https://www.epa.ie/nationalwastestatistics/>

*Walk. **Cycle. **Turn down. **Switch off. **Use Less. **Engage. **C**H**A*
*N**G**E*

**Comment by ycphs** [comment]
If you know which change of your xslx file causes the problem, I will take deeper look into the issue myself. If you get further with your analysis, I am also happy to receive a pull request for the package to fix your problem. 

Maintaining packages is quite a lot of work and it would be great if more people contribute also with code, not only creating issues and expecting others to fix it.

**Comment by dory-maguire** [comment]
Thanks Philipp for your response,

It seems that the issue happens as soon as I do anything with the Excel
file and then save it, e.g. even adding text to the file (changing one cell
from 2018 to 2019 for example) and then saving it, causes it to then
corrupt upon interaction with openxlsx. When I make that same text change
in R itself using openxlsx, it works just fine.

I'm afraid my expertise when it comes to xml is farrrrr too limited to
understand what is going on there. To me it maybe (?) has to be something
to do with a slight difference in excel file structure with Excel 365?
That's the only thing I can think might be happening.

I completely understand your point about contributing code. I would be
happy to take a look, but without any knowledge of xml code, I feel like I
wouldn't have the expertise to understand what is causing the corruption.
Maybe you could point me in the right direction?

Anyway, thanks very much for looking into this, much appreciated.


Dorothy Y Maguire, PhD [image: LinkedIn]
<https://www.linkedin.com/in/dorothy-maguire-mfc-phd-8669a272>
<https://www.epa.ie/>

Scientific Officer | Office of Environmental Sustainability | Environmental
Protection Agency| Ireland



McCumisky House | Clonskeagh Road |Dublin 14 | D14 YR62

Tel: +353 1 268 0120 | email: d.maguire@epa.ie | twitter: @EPAWasteRes



*Click below to view Ireland’s national waste statistics*

<https://www.epa.ie/nationalwastestatistics/>

*Walk. **Cycle. **Turn down. **Switch off. **Use Less. **Engage. **C**H**A*
*N**G**E*

**Comment by JanMarvin** [comment]
#133 improves the file from this issue. The file looks better in LibreOffice and Google Sheets, though it can not yet be opened in Excel. I tried reducing the differences between the original and the `openxlsx` written file, but the original is simply to huge, to spot anything specific. Maybe `xl/calcChain.xml` needs to be implemented, but it could be something entirely different.
Edit: There are still a few id, uri and similar xml attributes in `drawing[1-2].xml`. Might be that Excel is searching for them and unable to find.

**Comment by JMPivette** [comment]
On my computer, PR #133 solved this issue.

Below is the output file after loading and saving it:
[Workbook_Template_new_out.xlsx](https://github.com/ycphs/openxlsx/files/5786011/Workbook_Template_new_out.xlsx)

Opening this file on my computer doesn't create any error. 
Here is my version of Excel: 
- Microsoft Excel for Mac
- Version 16.43 (20110804)

**Comment by JMPivette** [comment]
Opening it on microsoft windows is OK too:
- Microsoft Excel Version 2009 (build 13231.20390) 64 bits

However I get an error when opening with Excel for Android:
- Microsoft Excel for Android 16.0.13530.20130

**Comment by JMPivette** [comment]
It looks like both Excel for Mac and Excel for Windows silently repair the xlsx file whereas Excel for Android is unable to do it.

If I open and save the file with Excel for Mac, I get the following new file that can be read by Excel for Android:
[Workbook_Template_new_out_2.xlsx](https://github.com/ycphs/openxlsx/files/5786224/Workbook_Template_new_out_2.xlsx)

I just need to figure out what changes have been made silently between `Workbook_Template_new_out.xlsx`and `Workbook_Template_new_out_2.xlsx`
