### ISSUE TITLE
Delete/Overwrite named regions functionality

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [ycphs/openxlsx#86]
Hi, 

The deleteNamedRegions function was announced for version 4.1.0 but doesn't appear to have been included. Could you please advise on the status of this functionality? 

Thanks

**Comment by ycphs** [comment]
It is in the news, but I couldn't find any function to cover the functionality. Maybe it was a planned feature, but I can't find it in the former or current repo.

I am happy, if you could provide a pull request to add the functionality to the package.
