### ISSUE TITLE
dataValidation multiple cols pick not working properly 

### ISSUE THREAD

**Issue by hjia222** [ycphs/openxlsx#87]
When useing dataValidation add same drop down list to multiple columns, cols = c(5, 10, 15) are expected to apply the drop down list to coulmns 5, 10, 15, but it applies to columns 5:15.

```
library(openxlsx)

df <- bind_cols(iris, iris, iris)

# create workbook
wb <- createWorkbook()

# initialize worksheet
addWorksheet( wb = wb, sheetName = "Sheet1" )

# add df to Sheet1
writeData( wb = wb
           , sheet = "Sheet1"
           , x = df
)

## Add dropdown list

addWorksheet(wb, "comment values")

comment <- data.frame(comments = unique(iris$Species))
col_n <- which(str_detect(names(df), "Species"))

writeData(wb, sheet = "comment values", comment, startCol = 1)

dataValidation(wb, 1, cols = col_n, rows = 2:(nrow(df)+1),
               type = "list", value = "'comment values'!$A$2:$A$4")

openXL( file = wb )
```

Drop down list should apply to coulmn 5, 10, 15,  namely: Species, Species1, Species2.

But it applied to column 5:15

![image](https://user-images.githubusercontent.com/22818458/89367911-388f8100-d6a8-11ea-9988-16429cc43b76.png)

**Desktop**
 - OS: Window 8

**sessionInfo()**

Version of openxlsx: 4.0.29 & 4.1.5
Version of R: 3.6.1

**Comment by ycphs** [comment]
Currently only a connected area for data validation is supported.

I welcome you to provide a pull request to enable the new feature.

**Comment by hjia222** [comment]
Thanks for your quick response! I was able to solve this with multiple dataValidation in `openxlsx_4.2.0`, this won't work in lower version of openxlsx.

```
library(purrr)

map(col_n, ~ dataValidation(wb, 1, cols = .x, rows = 2:(nrow(df)+1),
               type = "list", value = "'comment values'!$A$2:$A$4")
)
```
Of course if dataValidation allow discrete columns pick would be more desirable.

**Comment by ycphs** [comment]
You are welcome. If it is solved with the current version, then the issue can be closed.

Thank you for your input.
