### ISSUE TITLE
notContainsText (and other types?

### ISSUE THREAD

**Issue by r2evans** [ycphs/openxlsx#94]
**Is your feature request related to a problem? Please describe.**

Conditional formatting in Excel supports multiple types. For "cells that contains", in addition to `"containsText"` that you currently support, it also supports `"notContainsText"`, `"beginsWith"`, and `"endsWith"`. 

(Impetus for this FR: https://stackoverflow.com/q/63470115/3358272)

**Describe the solution you'd like**

It would be nice to include at least "not", and I suggest adding three is just as straight-forward.

**Describe alternatives you've considered**

I tried to mimic it with:

```lang-r
conditionalFormatting(wb, "mtcars", cols=4, rows=2:33, type='expression', rule='iserror(search("4",D2))', style=style)
```

i.e., injecting the raw expression rule. Unfortunately, the code prepends the cell address to the rule, so that comes out as roughly

```
<formula>D2iserror(search("4",D2)</formula>
```

**Additional context**

After playing with some of the rules in *"cells that contains"* and *"specific text"*, I see the rule formation is straight-forward for all of them:

```
<conditionalFormatting sqref="B2:C33">
  <cfRule type="containsText" dxfId="4" priority="5" operator="containsText" text="4"><formula>NOT(ISERROR(SEARCH("4", B2)))</formula></cfRule>
</conditionalFormatting>
<conditionalFormatting sqref="J2:N33">
  <cfRule type="expression" dxfId="3" priority="4"><formula>J2&lt;&gt; 4</formula></cfRule>
</conditionalFormatting>
<conditionalFormatting sqref="E2:E33">
  <cfRule type="notContainsText" dxfId="2" priority="3" operator="notContains" text="4"><formula>ISERROR(SEARCH("4",E2))</formula></cfRule>
</conditionalFormatting>
<conditionalFormatting sqref="F2:F33">
  <cfRule type="beginsWith" dxfId="1" priority="2" operator="beginsWith" text="3"><formula>LEFT(F2,LEN("3"))="3"</formula></cfRule>
</conditionalFormatting>
<conditionalFormatting sqref="G2:G33">
  <cfRule type="endsWith" dxfId="0" priority="1" operator="endsWith" text="4"><formula>RIGHT(G2,LEN("4"))="4"</formula></cfRule>
</conditionalFormatting>
```

**Comment by ycphs** [comment]
Please check the current version: [commit](https://github.com/ycphs/openxlsx/commit/7bb7c0c576b54807c7af5c9d561a18a001435f4c)

please try to use the development version:
```
install.packages(c("Rcpp", "devtools"), dependencies = TRUE)
require(devtools)
install_github("ycphs/openxlsx")
```


If it works as expected, please close the issue.

**Comment by r2evans** [comment]
That was incredibly fast, thank you @ycphs!
