### ISSUE TITLE
CRAN removal? checks fail on R-devel

### ISSUE THREAD

**Issue by zeehio** [ycphs/openxlsx#99]
As Maintainer of the condformat package, which depends on openxlsx, I have received an email from CRAN maintainers warning me that openxlsx will be removed from CRAN on 2020-09-25 unless the errors listed on https://cran.r-project.org/web/checks/check_results_openxlsx.html are fixed. My package (and other packages) would be removed as well since it imports openxlsx.

Are you aware of this issue? Would you have the time to submit a fix before the deadline?

Thanks

**Comment by rkrug** [comment]
I got the same message (dmdScheme package). My fix for the moment is to move openxlsx into the suggest section as nothing breaks, but I would very much like to have openxlsx reliably on CRAN again.

**Comment by ycphs** [comment]
Thank you for your massage. I am working on a patch to fix the errors. 

It was a bit busy the last weeks.

Best regards
Philipp

**Comment by ycphs** [comment]
The new version is accepted and published on CRAN and the errors for the devel versions are solved.
